use signal_hardware::{
    AudioSampleFormat, BackendHealth, HardwareBackendIdentity, LinuxAudioBackendKind,
};
use signal_runtime::*;

pub(crate) fn sample_integrated_acceptance_host_io() -> RuntimeHostIoSummary {
    RuntimeHostIoSummary {
        hardware: RuntimeHostHardwareSummary {
            backend_identity: HardwareBackendIdentity::CoreAudio,
            backend_name: "coreaudio".into(),
            linux_backend_identity: RuntimeHostHardwareSummary::classify_linux_backend_identity(
                HardwareBackendIdentity::CoreAudio,
            ),
            linux_backend_portability:
                RuntimeHostHardwareSummary::classify_linux_backend_portability(
                    HardwareBackendIdentity::CoreAudio,
                    false,
                    BackendHealth::Healthy,
                    0,
                    0,
                    0,
                ),
            device_id: "device:integrated-acceptance".into(),
            device_name: "Integrated Acceptance Device".into(),
            sample_rate: 48_000,
            buffer_size: 256,
            input_channels: 0,
            output_channels: 2,
            sample_format: AudioSampleFormat::F32,
            simulated: false,
            backend_health: BackendHealth::Healthy,
            xrun_count: 0,
            callback_overrun_count: 0,
            device_loss_count: 0,
            restart_attempt_count: 0,
            restart_failure_count: 0,
        },
        audio_pump: RuntimeHostAudioPumpSummary {
            stream_state: RuntimeHostAudioStreamState::Running,
            transfer_policy: RuntimeHostAudioTransferPolicy {
                max_callback_frames: 256,
                max_transfer_channels: 2,
                zero_fill_unwritten_output: true,
            },
            callback_count: 12,
            total_callback_frames: 3_072,
            total_runtime_output_frames: 3_072,
            copied_output_samples: 6_144,
            zero_filled_output_samples: 0,
            dropped_output_samples: 0,
            last_callback_output_peak: Some(0.35),
            last_runtime_graph_id: Some("graph:integrated-acceptance".into()),
        },
        clocking: RuntimeHostClockingSummary {
            clock_source: RuntimeHostClockSource::Internal,
            ownership: RuntimeHostLifecycleOwnership::HostDrivenCallback,
            restart_policy: RuntimeHostRestartPolicy::HostMustRestart,
            processing_sample_rate_hz: 44_100,
            hardware_sample_rate_hz: 48_000,
            clock_domain: RuntimeHostClockDomain::CrossClock,
            fallback_state: RuntimeHostClockFallbackState::RuntimeResampled,
            transition_state: RuntimeHostClockTransitionState::EnteredCrossClockFallback,
            drift_state: RuntimeHostClockDriftState::CrossClockManaged,
            discontinuity_state: RuntimeHostClockDiscontinuityState::Reconfigured,
            duplex_mismatch_state: RuntimeHostDuplexMismatchState::CrossClockDiverged,
            endpoint_topology: RuntimeHostEndpointTopology::Duplex,
            linux_clocking_parity: RuntimeLinuxAudioBackendClockingParityBand::Unsupported,
            linux_duplex_parity: RuntimeLinuxAudioBackendDuplexParityState::Unsupported,
            linux_endpoint_topology_parity:
                RuntimeLinuxAudioBackendEndpointTopologyParityState::Unsupported,
            partial_availability: false,
            crossing_required: true,
            callback_interval_ms: 5.333,
        },
        latency: RuntimeHostLatencySummary {
            input_latency_samples: Some(128),
            output_latency_samples: 256,
            round_trip_latency_samples: Some(384),
            graph_latency_samples: 24,
            estimated_output_latency_samples: 280,
            estimated_round_trip_latency_samples: Some(408),
            output_latency_ms: 5.333,
            graph_latency_ms: 0.5,
            estimated_output_latency_ms: 5.833,
            estimated_round_trip_latency_ms: Some(8.5),
        },
        runtime_graph_id_matches_pump: true,
    }
}

pub(crate) fn sample_g07_acceptance_host_io() -> RuntimeHostIoSummary {
    let linux_backend_identity = RuntimeHostHardwareSummary::classify_linux_backend_identity(
        HardwareBackendIdentity::Linux(LinuxAudioBackendKind::Alsa),
    );
    let linux_parity = RuntimeHostIoSummary::linux_parity_input(
        linux_backend_identity,
        BackendHealth::Healthy,
        RuntimeHostAudioStreamState::Running,
        RuntimeHostClockDomain::SameClock,
        RuntimeHostClockFallbackState::Direct,
        RuntimeHostClockTransitionState::Stable,
        RuntimeHostClockDriftState::Stable,
        RuntimeHostClockDiscontinuityState::Continuous,
        RuntimeHostDuplexMismatchState::Aligned,
        RuntimeHostEndpointTopology::Duplex,
        false,
    );
    RuntimeHostIoSummary {
        hardware: RuntimeHostHardwareSummary {
            backend_identity: HardwareBackendIdentity::Linux(LinuxAudioBackendKind::Alsa),
            backend_name: "alsa".into(),
            linux_backend_identity,
            linux_backend_portability:
                RuntimeHostHardwareSummary::classify_linux_backend_portability(
                    HardwareBackendIdentity::Linux(LinuxAudioBackendKind::Alsa),
                    false,
                    BackendHealth::Healthy,
                    0,
                    0,
                    0,
                ),
            device_id: "alsa:g07-integrated".into(),
            device_name: "ALSA Integrated Acceptance Device".into(),
            sample_rate: 48_000,
            buffer_size: 256,
            input_channels: 2,
            output_channels: 2,
            sample_format: AudioSampleFormat::F32,
            simulated: false,
            backend_health: BackendHealth::Healthy,
            xrun_count: 0,
            callback_overrun_count: 0,
            device_loss_count: 0,
            restart_attempt_count: 0,
            restart_failure_count: 0,
        },
        audio_pump: RuntimeHostAudioPumpSummary {
            stream_state: RuntimeHostAudioStreamState::Running,
            transfer_policy: RuntimeHostAudioTransferPolicy {
                max_callback_frames: 256,
                max_transfer_channels: 2,
                zero_fill_unwritten_output: true,
            },
            callback_count: 16,
            total_callback_frames: 4_096,
            total_runtime_output_frames: 4_096,
            copied_output_samples: 8_192,
            zero_filled_output_samples: 0,
            dropped_output_samples: 0,
            last_callback_output_peak: Some(0.42),
            last_runtime_graph_id: Some("graph:g07-integrated-acceptance".into()),
        },
        clocking: RuntimeHostClockingSummary {
            clock_source: RuntimeHostClockSource::Internal,
            ownership: RuntimeHostLifecycleOwnership::HostDrivenCallback,
            restart_policy: RuntimeHostRestartPolicy::HostMustRestart,
            processing_sample_rate_hz: 48_000,
            hardware_sample_rate_hz: 48_000,
            clock_domain: RuntimeHostClockDomain::SameClock,
            fallback_state: RuntimeHostClockFallbackState::Direct,
            transition_state: RuntimeHostClockTransitionState::Stable,
            drift_state: RuntimeHostClockDriftState::Stable,
            discontinuity_state: RuntimeHostClockDiscontinuityState::Continuous,
            duplex_mismatch_state: RuntimeHostDuplexMismatchState::Aligned,
            endpoint_topology: RuntimeHostEndpointTopology::Duplex,
            linux_clocking_parity: RuntimeHostIoSummary::classify_linux_clocking_parity(
                linux_parity,
            ),
            linux_duplex_parity: RuntimeHostIoSummary::classify_linux_duplex_parity(linux_parity),
            linux_endpoint_topology_parity:
                RuntimeHostIoSummary::classify_linux_endpoint_topology_parity(
                    linux_backend_identity,
                    BackendHealth::Healthy,
                    RuntimeHostClockTransitionState::Stable,
                    RuntimeHostClockDiscontinuityState::Continuous,
                    RuntimeHostDuplexMismatchState::Aligned,
                    RuntimeHostEndpointTopology::Duplex,
                    false,
                ),
            partial_availability: false,
            crossing_required: false,
            callback_interval_ms: 5.333,
        },
        latency: RuntimeHostLatencySummary {
            input_latency_samples: Some(128),
            output_latency_samples: 128,
            round_trip_latency_samples: Some(256),
            graph_latency_samples: 24,
            estimated_output_latency_samples: 152,
            estimated_round_trip_latency_samples: Some(280),
            output_latency_ms: 2.667,
            graph_latency_ms: 0.5,
            estimated_output_latency_ms: 3.167,
            estimated_round_trip_latency_ms: Some(5.833),
        },
        runtime_graph_id_matches_pump: true,
    }
}
