use signal_runtime::{
    RuntimeAuditionSinkAuthority, RuntimeAuditionSinkClass, RuntimeMediaAuditionContinuityOutcome,
    RuntimeMediaAuditionOrchestrationAuthority, RuntimeMediaAuditionOrchestrationPosture,
    RuntimeObservationReport, RuntimePreviewBrowserQueueClass, RuntimePreviewBrowserQueueOutcome,
    RuntimePreviewBrowserQueuePosture, RuntimePreviewOutputRoutingPosture,
    RuntimePreviewTransformReadiness, RuntimePreviewTransformSchedulingAuthority,
    RuntimePreviewTransformSchedulingOutcome, RuntimePreviewTransformSchedulingPosture,
    RuntimePreviewTransformServiceClass,
};

pub(crate) fn assert_preview_transform_observation(observation: &RuntimeObservationReport) {
    assert_eq!(observation.preview_transform_snapshot.clip_count, 1);
    assert_eq!(observation.preview_transform_snapshot.ready_clip_count, 1);
    assert_eq!(
        observation
            .preview_transform_snapshot
            .active_audition_clip_count,
        1
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_device_policy
            .routing_posture,
        RuntimePreviewOutputRoutingPosture::GuardedPreviewOutputRouting
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_device_policy
            .audition_sink_class,
        RuntimeAuditionSinkClass::GuardedPreviewSink
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_device_policy
            .audition_sink_authority,
        RuntimeAuditionSinkAuthority::RuntimeDefault
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_device_policy
            .low_latency_device_policy_class,
        signal_runtime::RuntimeLowLatencyDevicePolicyClass::GuardedLowLatencyDevicePolicy
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_device_policy
            .low_latency_device_policy_outcome,
        signal_runtime::RuntimeLowLatencyDevicePolicyOutcome::ObserveOnlyPreview
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_workflow
            .queue_posture,
        RuntimePreviewBrowserQueuePosture::SingleActivePreviewQueue
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_workflow
            .queue_class,
        RuntimePreviewBrowserQueueClass::SingleAssetAuditionQueue
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_workflow
            .queue_outcome,
        RuntimePreviewBrowserQueueOutcome::PreserveActivePreviewRequest
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_workflow
            .audition_posture,
        RuntimeMediaAuditionOrchestrationPosture::DirectRuntimeAuditionOrchestration
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_workflow
            .audition_authority,
        RuntimeMediaAuditionOrchestrationAuthority::RuntimeDefault
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_workflow
            .audition_continuity_outcome,
        RuntimeMediaAuditionContinuityOutcome::PreserveActiveAudition
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_workflow
            .transform_scheduling_posture,
        RuntimePreviewTransformSchedulingPosture::DirectRuntimeTransformScheduling
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_workflow
            .transform_scheduling_authority,
        RuntimePreviewTransformSchedulingAuthority::PreviewDemandDerived
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .preview_workflow
            .transform_scheduling_outcome,
        RuntimePreviewTransformSchedulingOutcome::PreferArtifactBackedPreview
    );
    assert_eq!(
        observation
            .preview_transform_snapshot
            .artifact_backed_clip_count,
        1
    );
    assert_eq!(
        observation.preview_transform_snapshot.clips[0].service_class,
        RuntimePreviewTransformServiceClass::ArtifactBacked
    );
    assert_eq!(
        observation.preview_transform_snapshot.clips[0].readiness,
        RuntimePreviewTransformReadiness::Ready
    );
    assert!(observation.preview_transform_snapshot.clips[0].audition_active);
}
