[package]
name = "signal-hardware"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Common hardware and device abstractions for Signal."

[lints]
workspace = true

[dependencies]
signal-primitives = { workspace = true }
