use super::runtime_contracts::*;

pub(crate) const INTEGRATED_ACCEPTANCE_REQUIRED_TASKS: &[&str] = &[
    INTERRUPTION_ACCEPTANCE_TASK,
    FAULT_DIAGNOSTIC_ACCEPTANCE_TASK,
    CRITICAL_PATH_ACCEPTANCE_TASK,
    DEFERRED_WORK_POLICY_ACCEPTANCE_TASK,
    PLUGIN_CONTINUITY_ACCEPTANCE_TASK,
    CROSS_ADAPTER_PARITY_ACCEPTANCE_TASK,
    DEVICE_SUPERVISION_ACCEPTANCE_TASK,
    CLOCK_TOPOLOGY_ACCEPTANCE_TASK,
    EXTERNAL_IO_ACCEPTANCE_TASK,
    MEDIA_SERVICE_ACCEPTANCE_TASK,
    ANALYSIS_METADATA_ACCEPTANCE_TASK,
];
pub(crate) const INTEGRATED_ACCEPTANCE_ADVISORY_TASKS: &[&str] = &[
    RECORDING_CONTINUITY_ACCEPTANCE_TASK,
    OFFLINE_RENDER_CONTINUITY_ACCEPTANCE_TASK,
    VST3_ACCEPTANCE_TASK,
    AU_ACCEPTANCE_TASK,
    GENERIC_EVENT_ACCEPTANCE_TASK,
    RECALL_PORTABILITY_ACCEPTANCE_TASK,
];
pub(crate) const RECOVERY_AND_FAULT_REQUIRED_TASKS: &[&str] = &[
    INTERRUPTION_ACCEPTANCE_TASK,
    FAULT_DIAGNOSTIC_ACCEPTANCE_TASK,
    DEVICE_SUPERVISION_ACCEPTANCE_TASK,
];
pub(crate) const RECOVERY_AND_FAULT_ADVISORY_TASKS: &[&str] = &[
    RECORDING_CONTINUITY_ACCEPTANCE_TASK,
    OFFLINE_RENDER_CONTINUITY_ACCEPTANCE_TASK,
];
pub(crate) const SCHEDULING_AND_PRESSURE_REQUIRED_TASKS: &[&str] = &[
    CRITICAL_PATH_ACCEPTANCE_TASK,
    DEFERRED_WORK_POLICY_ACCEPTANCE_TASK,
];
pub(crate) const SCHEDULING_AND_PRESSURE_ADVISORY_TASKS: &[&str] = &[BLOCK_TIMING_ACCEPTANCE_TASK];
pub(crate) const ADAPTER_AND_PORTABILITY_REQUIRED_TASKS: &[&str] = &[
    PLUGIN_CONTINUITY_ACCEPTANCE_TASK,
    CROSS_ADAPTER_PARITY_ACCEPTANCE_TASK,
];
pub(crate) const ADAPTER_AND_PORTABILITY_ADVISORY_TASKS: &[&str] = &[
    VST3_ACCEPTANCE_TASK,
    AU_ACCEPTANCE_TASK,
    GENERIC_EVENT_ACCEPTANCE_TASK,
    RECALL_PORTABILITY_ACCEPTANCE_TASK,
];
pub(crate) const HARDWARE_AND_EXTERNAL_IO_REQUIRED_TASKS: &[&str] = &[
    DEVICE_SUPERVISION_ACCEPTANCE_TASK,
    CLOCK_TOPOLOGY_ACCEPTANCE_TASK,
    EXTERNAL_IO_ACCEPTANCE_TASK,
];
pub(crate) const HARDWARE_AND_EXTERNAL_IO_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const MEDIA_AND_LIBRARY_REQUIRED_TASKS: &[&str] = &[
    MEDIA_SERVICE_ACCEPTANCE_TASK,
    ANALYSIS_METADATA_ACCEPTANCE_TASK,
];
pub(crate) const MEDIA_AND_LIBRARY_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const G07_ACCEPTANCE_REQUIRED_TASKS: &[&str] = &[
    MULTICHANNEL_ACCEPTANCE_TASK,
    SIDECHAIN_ACCEPTANCE_TASK,
    MULTI_BUS_ACCEPTANCE_TASK,
    SPATIAL_ACCEPTANCE_TASK,
    LINUX_PLUGIN_PARITY_ACCEPTANCE_TASK,
    LINUX_AUDIO_BACKEND_ACCEPTANCE_TASK,
    LINUX_BACKEND_CLOCK_TOPOLOGY_ACCEPTANCE_TASK,
    EXTERNAL_MIDI_ACCEPTANCE_TASK,
    CONTROLLER_EXPRESSION_ACCEPTANCE_TASK,
    CONTROL_SURFACE_ACCEPTANCE_TASK,
    ADVANCED_HARDWARE_ACCEPTANCE_TASK,
    STRETCH_ACCEPTANCE_TASK,
    MARKER_ANALYSIS_ACCEPTANCE_TASK,
    TRANSFORM_ARTIFACT_ACCEPTANCE_TASK,
    PREVIEW_TRANSFORM_ACCEPTANCE_TASK,
];
pub(crate) const G07_ACCEPTANCE_ADVISORY_TASKS: &[&str] =
    &[COMPLEX_IO_ACCEPTANCE_TASK, LV2_ACCEPTANCE_TASK];
pub(crate) const G07_ROUTING_REQUIRED_TASKS: &[&str] = &[
    MULTICHANNEL_ACCEPTANCE_TASK,
    SIDECHAIN_ACCEPTANCE_TASK,
    MULTI_BUS_ACCEPTANCE_TASK,
    SPATIAL_ACCEPTANCE_TASK,
];
pub(crate) const G07_ROUTING_ADVISORY_TASKS: &[&str] = &[COMPLEX_IO_ACCEPTANCE_TASK];
pub(crate) const G07_LINUX_REQUIRED_TASKS: &[&str] = &[
    LINUX_PLUGIN_PARITY_ACCEPTANCE_TASK,
    LINUX_AUDIO_BACKEND_ACCEPTANCE_TASK,
    LINUX_BACKEND_CLOCK_TOPOLOGY_ACCEPTANCE_TASK,
];
pub(crate) const G07_LINUX_ADVISORY_TASKS: &[&str] = &[LV2_ACCEPTANCE_TASK];
pub(crate) const G07_CONTROL_REQUIRED_TASKS: &[&str] = &[
    EXTERNAL_MIDI_ACCEPTANCE_TASK,
    CONTROLLER_EXPRESSION_ACCEPTANCE_TASK,
    CONTROL_SURFACE_ACCEPTANCE_TASK,
    ADVANCED_HARDWARE_ACCEPTANCE_TASK,
];
pub(crate) const G07_CONTROL_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const G07_STRETCH_REQUIRED_TASKS: &[&str] = &[
    STRETCH_ACCEPTANCE_TASK,
    MARKER_ANALYSIS_ACCEPTANCE_TASK,
    TRANSFORM_ARTIFACT_ACCEPTANCE_TASK,
    PREVIEW_TRANSFORM_ACCEPTANCE_TASK,
];
pub(crate) const G07_STRETCH_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const DEVICE_WORKFLOW_ACCEPTANCE_REQUIRED_TASKS: &[&str] = &[
    EXTERNAL_MIDI_ACCEPTANCE_TASK,
    CONTROLLER_EXPRESSION_ACCEPTANCE_TASK,
    CONTROL_SURFACE_ACCEPTANCE_TASK,
    ADVANCED_HARDWARE_ACCEPTANCE_TASK,
];
pub(crate) const DEVICE_WORKFLOW_ACCEPTANCE_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const DEVICE_WORKFLOW_LIVE_PROTOCOL_REQUIRED_TASKS: &[&str] = &[
    EXTERNAL_MIDI_ACCEPTANCE_TASK,
    CONTROLLER_EXPRESSION_ACCEPTANCE_TASK,
];
pub(crate) const DEVICE_WORKFLOW_LIVE_PROTOCOL_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const DEVICE_WORKFLOW_CONTROL_REQUIRED_TASKS: &[&str] = &[
    CONTROL_SURFACE_ACCEPTANCE_TASK,
    ADVANCED_HARDWARE_ACCEPTANCE_TASK,
];
pub(crate) const DEVICE_WORKFLOW_CONTROL_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const DEVICE_WORKFLOW_HOST_EDGE_REQUIRED_TASKS: &[&str] = &[
    EXTERNAL_MIDI_ACCEPTANCE_TASK,
    CONTROL_SURFACE_ACCEPTANCE_TASK,
    ADVANCED_HARDWARE_ACCEPTANCE_TASK,
];
pub(crate) const DEVICE_WORKFLOW_HOST_EDGE_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const LINUX_LIVE_ACCEPTANCE_REQUIRED_TASKS: &[&str] = &[
    LINUX_LIVE_OWNERSHIP_ACCEPTANCE_TASK,
    JACK_COORDINATION_ACCEPTANCE_TASK,
    PIPEWIRE_ALSA_PARITY_ACCEPTANCE_TASK,
    LINUX_BACKEND_CLOCK_TOPOLOGY_ACCEPTANCE_TASK,
];
pub(crate) const LINUX_LIVE_ACCEPTANCE_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const LINUX_LIVE_OWNERSHIP_REQUIRED_TASKS: &[&str] = &[
    LINUX_LIVE_OWNERSHIP_ACCEPTANCE_TASK,
    LINUX_BACKEND_CLOCK_TOPOLOGY_ACCEPTANCE_TASK,
];
pub(crate) const LINUX_LIVE_OWNERSHIP_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const LINUX_LIVE_BACKEND_PROTOCOL_REQUIRED_TASKS: &[&str] = &[
    JACK_COORDINATION_ACCEPTANCE_TASK,
    PIPEWIRE_ALSA_PARITY_ACCEPTANCE_TASK,
];
pub(crate) const LINUX_LIVE_BACKEND_PROTOCOL_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const LINUX_LIVE_HOST_EDGE_REQUIRED_TASKS: &[&str] = &[
    LINUX_LIVE_OWNERSHIP_ACCEPTANCE_TASK,
    JACK_COORDINATION_ACCEPTANCE_TASK,
    PIPEWIRE_ALSA_PARITY_ACCEPTANCE_TASK,
];
pub(crate) const LINUX_LIVE_HOST_EDGE_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const IMMERSIVE_ACCEPTANCE_REQUIRED_TASKS: &[&str] = &[SPATIAL_ACCEPTANCE_TASK];
pub(crate) const IMMERSIVE_ACCEPTANCE_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const IMMERSIVE_RENDER_REQUIRED_TASKS: &[&str] = &[SPATIAL_ACCEPTANCE_TASK];
pub(crate) const IMMERSIVE_RENDER_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const IMMERSIVE_MONITORING_REQUIRED_TASKS: &[&str] = &[SPATIAL_ACCEPTANCE_TASK];
pub(crate) const IMMERSIVE_MONITORING_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const IMMERSIVE_HOST_EDGE_REQUIRED_TASKS: &[&str] = &[SPATIAL_ACCEPTANCE_TASK];
pub(crate) const IMMERSIVE_HOST_EDGE_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const CONTROL_PREVIEW_WORKFLOW_ACCEPTANCE_REQUIRED_TASKS: &[&str] = &[
    ADVANCED_HARDWARE_ACCEPTANCE_TASK,
    PREVIEW_TRANSFORM_ACCEPTANCE_TASK,
];
pub(crate) const CONTROL_PREVIEW_WORKFLOW_ACCEPTANCE_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const CONTROL_WORKFLOW_REQUIRED_TASKS: &[&str] = &[ADVANCED_HARDWARE_ACCEPTANCE_TASK];
pub(crate) const CONTROL_WORKFLOW_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const PREVIEW_WORKFLOW_REQUIRED_TASKS: &[&str] = &[PREVIEW_TRANSFORM_ACCEPTANCE_TASK];
pub(crate) const PREVIEW_WORKFLOW_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const CONTROL_PREVIEW_HOST_EDGE_REQUIRED_TASKS: &[&str] = &[
    ADVANCED_HARDWARE_ACCEPTANCE_TASK,
    PREVIEW_TRANSFORM_ACCEPTANCE_TASK,
];
pub(crate) const CONTROL_PREVIEW_HOST_EDGE_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const INTEGRATED_LIVE_WORKFLOW_ACCEPTANCE_REQUIRED_TASKS: &[&str] = &[
    LINUX_LIVE_ACCEPTANCE_TASK,
    DEVICE_WORKFLOW_ACCEPTANCE_TASK,
    IMMERSIVE_ACCEPTANCE_TASK,
    CONTROL_PREVIEW_WORKFLOW_ACCEPTANCE_TASK,
];
pub(crate) const INTEGRATED_LIVE_WORKFLOW_ACCEPTANCE_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const INTEGRATED_LIVE_AND_DEVICE_REQUIRED_TASKS: &[&str] =
    &[LINUX_LIVE_ACCEPTANCE_TASK, DEVICE_WORKFLOW_ACCEPTANCE_TASK];
pub(crate) const INTEGRATED_LIVE_AND_DEVICE_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const INTEGRATED_IMMERSIVE_AND_PREVIEW_REQUIRED_TASKS: &[&str] = &[
    IMMERSIVE_ACCEPTANCE_TASK,
    CONTROL_PREVIEW_WORKFLOW_ACCEPTANCE_TASK,
];
pub(crate) const INTEGRATED_IMMERSIVE_AND_PREVIEW_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const INTEGRATED_CROSS_SURFACE_REQUIRED_TASKS: &[&str] = &[
    LINUX_LIVE_ACCEPTANCE_TASK,
    DEVICE_WORKFLOW_ACCEPTANCE_TASK,
    IMMERSIVE_ACCEPTANCE_TASK,
    CONTROL_PREVIEW_WORKFLOW_ACCEPTANCE_TASK,
];
pub(crate) const INTEGRATED_CROSS_SURFACE_ADVISORY_TASKS: &[&str] = &[];
pub(crate) const INTEGRATED_GROUPED_EXPORT_REQUIRED_TASKS: &[&str] = &[
    LINUX_LIVE_ACCEPTANCE_TASK,
    DEVICE_WORKFLOW_ACCEPTANCE_TASK,
    IMMERSIVE_ACCEPTANCE_TASK,
    CONTROL_PREVIEW_WORKFLOW_ACCEPTANCE_TASK,
];
pub(crate) const INTEGRATED_GROUPED_EXPORT_ADVISORY_TASKS: &[&str] = &[];
