use super::super::super::*;
use super::fixtures::ArcSurfaceCases;

pub(super) fn assert_guarded_refined_and_deferred(cases: &ArcSurfaceCases) {
    assert_eq!(
        cases.guarded_refined.continuity.arc,
        TempoContinuityArc::Recovering
    );
    assert_eq!(
        cases.guarded_refined.continuity.arc_rationale,
        TempoContinuityArcRationale::RefreshStrength
    );
    assert_eq!(
        cases.guarded_refined.continuity.arc_decision.recommendation,
        TempoContinuityArcRecommendation::MonitorRecovery
    );
    assert_eq!(
        cases.guarded_refined.continuity.arc_decision.action,
        TempoContinuityArcAction::ReacquireCurrentTempo
    );
    assert_eq!(
        cases.guarded_refined.continuity.arc_decision.severity,
        TempoContinuitySeverity::Fragile
    );
    assert_eq!(
        cases
            .guarded_refined
            .continuity
            .arc_decision
            .fallback_action,
        TempoContinuityArcAction::ClearTempo
    );
    assert_eq!(
        cases
            .guarded_refined
            .continuity
            .arc_decision
            .downgrade_rationale,
        TempoContinuityArcDowngradeRationale::AmbiguityCarry
    );
    assert_eq!(
        cases
            .guarded_refined
            .continuity
            .arc_decision
            .downgrade_trend,
        TempoContinuityArcDowngradeTrend::Easing
    );
    assert_eq!(
        cases
            .guarded_refined
            .continuity
            .arc_decision
            .downgrade_trend_rationale,
        TempoContinuityArcDowngradeTrendRationale::AmbiguityCarry
    );
    assert_eq!(
        cases
            .guarded_refined
            .continuity
            .arc_decision
            .downgrade_inflection
            .stage,
        TempoContinuityArcDowngradeInflectionStage::NextStage
    );
    assert_eq!(
        cases
            .guarded_refined
            .continuity
            .arc_decision
            .downgrade_inflection
            .competing_stage,
        Some(TempoContinuityArcDowngradeInflectionStage::TerminalClear)
    );
    assert_eq!(
        cases
            .guarded_refined
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .primary
            .dominant,
        TempoContinuityArcDowngradeStageRationale::AmbiguityCarry
    );
    assert!(matches!(
        cases
            .guarded_refined
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .competing
            .map(|weights| weights.dominant),
        Some(TempoContinuityArcDowngradeStageRationale::EvidenceLoss)
            | Some(TempoContinuityArcDowngradeStageRationale::AmbiguityCarry)
            | Some(TempoContinuityArcDowngradeStageRationale::StabilityWindow)
            | None
    ));
    assert!(
        cases
            .guarded_refined
            .continuity
            .arc_decision
            .downgrade_inflection
            .balance
            .competing_weight
            .0
            >= 0.0
    );
    assert!(
        cases
            .guarded_refined
            .continuity
            .arc_decision
            .downgrade_support
            .ambiguity_pressure
            .0
            > cases
                .guarded_refined
                .continuity
                .arc_decision
                .downgrade_support
                .failed_revalidation_pressure
                .0
    );
    assert_eq!(
        cases.guarded_refined.continuity.arc_decision.provenance,
        TempoContinuityProvenance::GuardedRefinedEstimate
    );

    assert_eq!(
        cases.deferred.continuity.arc,
        TempoContinuityArc::Collapsing
    );
    assert_eq!(
        cases.deferred.continuity.arc_rationale,
        TempoContinuityArcRationale::EvidenceLoss
    );
    assert_eq!(
        cases.deferred.continuity.arc_decision.recommendation,
        TempoContinuityArcRecommendation::Clear
    );
    assert_eq!(
        cases.deferred.continuity.arc_decision.action,
        TempoContinuityArcAction::ClearTempo
    );
    assert_eq!(
        cases.deferred.continuity.arc_decision.severity,
        TempoContinuitySeverity::Cleared
    );
    assert_eq!(
        cases.deferred.continuity.arc_decision.fallback_action,
        TempoContinuityArcAction::ClearTempo
    );
    assert_eq!(
        cases.deferred.continuity.arc_decision.downgrade_rationale,
        TempoContinuityArcDowngradeRationale::EvidenceLoss
    );
    assert_eq!(
        cases.deferred.continuity.arc_decision.downgrade_trend,
        TempoContinuityArcDowngradeTrend::Stable
    );
    assert_eq!(
        cases
            .deferred
            .continuity
            .arc_decision
            .downgrade_trend_rationale,
        TempoContinuityArcDowngradeTrendRationale::FlatCollapse
    );
    assert_eq!(
        cases
            .deferred
            .continuity
            .arc_decision
            .downgrade_inflection
            .stage,
        TempoContinuityArcDowngradeInflectionStage::FlatWindow
    );
    assert_eq!(
        cases
            .deferred
            .continuity
            .arc_decision
            .downgrade_inflection
            .competing_stage,
        None
    );
    assert_eq!(
        cases
            .deferred
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .primary
            .dominant,
        TempoContinuityArcDowngradeStageRationale::EvidenceLoss
    );
    assert_eq!(
        cases
            .deferred
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .competing,
        None
    );
    assert_eq!(
        cases
            .deferred
            .continuity
            .arc_decision
            .downgrade_inflection
            .balance
            .unattributed_weight,
        Confidence::new(1.0)
    );
    assert!(
        cases
            .deferred
            .continuity
            .arc_decision
            .downgrade_support
            .evidence_loss_pressure
            .0
            > cases
                .deferred
                .continuity
                .arc_decision
                .downgrade_support
                .ambiguity_pressure
                .0
    );
    assert_eq!(
        cases.deferred.continuity.arc_decision.provenance,
        TempoContinuityProvenance::NoTempo
    );
}
