use super::super::super::*;
use super::fixtures::ArcSurfaceCases;

pub(super) fn assert_integer_and_core_window(cases: &ArcSurfaceCases) {
    assert_eq!(cases.integer.continuity.arc, TempoContinuityArc::Recovering);
    assert_eq!(
        cases.integer.continuity.arc_rationale,
        TempoContinuityArcRationale::RefreshStrength
    );
    assert_eq!(
        cases.integer.continuity.arc_decision.recommendation,
        TempoContinuityArcRecommendation::KeepLock
    );
    assert_eq!(
        cases.integer.continuity.arc_decision.action,
        TempoContinuityArcAction::LockCurrentTempo
    );
    assert_eq!(
        cases.integer.continuity.arc_decision.severity,
        TempoContinuitySeverity::Confirmed
    );
    assert_eq!(
        cases.integer.continuity.arc_decision.fallback_action,
        TempoContinuityArcAction::ReacquireCurrentTempo
    );
    assert_eq!(
        cases.integer.continuity.arc_decision.downgrade_rationale,
        TempoContinuityArcDowngradeRationale::StabilityWindowEnd
    );
    assert_eq!(
        cases.integer.continuity.arc_decision.downgrade_trend,
        TempoContinuityArcDowngradeTrend::Easing
    );
    assert_eq!(
        cases
            .integer
            .continuity
            .arc_decision
            .downgrade_trend_rationale,
        TempoContinuityArcDowngradeTrendRationale::StabilityWindowCarry
    );
    assert_eq!(
        cases
            .integer
            .continuity
            .arc_decision
            .downgrade_inflection
            .stage,
        TempoContinuityArcDowngradeInflectionStage::NextStage
    );
    assert_eq!(
        cases
            .integer
            .continuity
            .arc_decision
            .downgrade_inflection
            .competing_stage,
        Some(TempoContinuityArcDowngradeInflectionStage::TerminalClear)
    );
    assert_eq!(
        cases
            .integer
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .primary
            .dominant,
        TempoContinuityArcDowngradeStageRationale::StabilityWindow
    );
    assert!(matches!(
        cases
            .integer
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .competing
            .map(|weights| weights.dominant),
        Some(TempoContinuityArcDowngradeStageRationale::EvidenceLoss)
            | Some(TempoContinuityArcDowngradeStageRationale::StabilityWindow)
            | None
    ));
    assert!(
        cases
            .integer
            .continuity
            .arc_decision
            .downgrade_inflection
            .balance
            .competing_weight
            .0
            >= 0.0
    );
    assert!(
        cases
            .integer
            .continuity
            .arc_decision
            .downgrade_support
            .stability_window_pressure
            .0
            > cases
                .integer
                .continuity
                .arc_decision
                .downgrade_support
                .failed_revalidation_pressure
                .0
    );
    assert_eq!(
        cases.integer.continuity.arc_decision.provenance,
        TempoContinuityProvenance::IntegerSnap
    );

    assert_eq!(
        cases.core_window.continuity.arc,
        TempoContinuityArc::Stalling
    );
    assert_eq!(
        cases.core_window.continuity.arc_rationale,
        TempoContinuityArcRationale::BoundaryDrift
    );
    assert_eq!(
        cases.core_window.continuity.arc_decision.recommendation,
        TempoContinuityArcRecommendation::MonitorRecovery
    );
    assert_eq!(
        cases.core_window.continuity.arc_decision.action,
        TempoContinuityArcAction::PreferCoreWindowTempo
    );
    assert_eq!(
        cases.core_window.continuity.arc_decision.severity,
        TempoContinuitySeverity::Guarded
    );
    assert_eq!(
        cases.core_window.continuity.arc_decision.fallback_action,
        TempoContinuityArcAction::PreservePriorTempo
    );
    assert_eq!(
        cases
            .core_window
            .continuity
            .arc_decision
            .downgrade_rationale,
        TempoContinuityArcDowngradeRationale::BoundaryDrift
    );
    assert_eq!(
        cases.core_window.continuity.arc_decision.downgrade_trend,
        TempoContinuityArcDowngradeTrend::Rising
    );
    assert_eq!(
        cases
            .core_window
            .continuity
            .arc_decision
            .downgrade_trend_rationale,
        TempoContinuityArcDowngradeTrendRationale::BoundaryEscalation
    );
    assert_eq!(
        cases
            .core_window
            .continuity
            .arc_decision
            .downgrade_inflection
            .stage,
        TempoContinuityArcDowngradeInflectionStage::NextStage
    );
    assert_eq!(
        cases
            .core_window
            .continuity
            .arc_decision
            .downgrade_inflection
            .competing_stage,
        Some(TempoContinuityArcDowngradeInflectionStage::TerminalClear)
    );
    assert_eq!(
        cases
            .core_window
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .primary
            .dominant,
        TempoContinuityArcDowngradeStageRationale::BoundaryDrift
    );
    assert!(matches!(
        cases
            .core_window
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .competing
            .map(|weights| weights.dominant),
        Some(TempoContinuityArcDowngradeStageRationale::EvidenceLoss)
            | Some(TempoContinuityArcDowngradeStageRationale::BoundaryDrift)
            | Some(TempoContinuityArcDowngradeStageRationale::StabilityWindow)
            | None
    ));
    assert!(
        cases
            .core_window
            .continuity
            .arc_decision
            .downgrade_inflection
            .balance
            .primary_weight
            .0
            >= cases
                .core_window
                .continuity
                .arc_decision
                .downgrade_inflection
                .balance
                .competing_weight
                .0
    );
    assert!(
        cases
            .core_window
            .continuity
            .arc_decision
            .downgrade_support
            .boundary_drift_pressure
            .0
            > cases
                .core_window
                .continuity
                .arc_decision
                .downgrade_support
                .stability_window_pressure
                .0
    );
    assert_eq!(
        cases.core_window.continuity.arc_decision.provenance,
        TempoContinuityProvenance::CoreWindowEstimate
    );
}
