use super::*;

pub(super) fn bar_transition_surface_cases() -> Vec<(RhythmPreset, f32, Option<usize>, f32, f32)> {
    vec![
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::Pickup),
            120.0,
            Some(4),
            0.7,
            0.1,
        ),
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::LateShift),
            120.0,
            Some(4),
            0.7,
            0.12,
        ),
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::MixedLength),
            120.0,
            None,
            0.45,
            0.08,
        ),
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::Modulation),
            120.0,
            None,
            0.45,
            0.08,
        ),
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::Reentry),
            120.0,
            Some(4),
            0.65,
            0.1,
        ),
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::CadentialElongation),
            120.0,
            None,
            0.45,
            0.08,
        ),
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::ReentryHarmonicShift),
            120.0,
            Some(4),
            0.65,
            0.1,
        ),
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::ReentryDenseFill),
            120.0,
            Some(4),
            0.6,
            0.12,
        ),
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::ReentryAcceleratingHarmony),
            120.0,
            Some(4),
            0.6,
            0.1,
        ),
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::ReentryDeceleratingHarmony),
            120.0,
            Some(4),
            0.6,
            0.1,
        ),
        (
            RhythmPreset::BarTransition120(
                BarTransitionVariant::ReentryAcceleratingHarmonyDenseFill,
            ),
            120.0,
            Some(4),
            0.58,
            0.12,
        ),
        (
            RhythmPreset::BarTransition120(
                BarTransitionVariant::ReentryDeceleratingHarmonyDenseFill,
            ),
            120.0,
            Some(4),
            0.58,
            0.12,
        ),
        (
            RhythmPreset::BarTransition120(
                BarTransitionVariant::ReentryAcceleratingHarmonyAccentShift,
            ),
            120.0,
            None,
            0.48,
            0.14,
        ),
        (
            RhythmPreset::BarTransition120(
                BarTransitionVariant::ReentryDeceleratingHarmonyAccentShift,
            ),
            120.0,
            None,
            0.48,
            0.14,
        ),
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::ReentryAcceleratingHarmonyReset),
            120.0,
            None,
            0.54,
            0.12,
        ),
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::ReentryDeceleratingHarmonyReset),
            120.0,
            None,
            0.54,
            0.12,
        ),
        (
            RhythmPreset::BarTransition120(
                BarTransitionVariant::ReentryAcceleratingHarmonySustainedReset,
            ),
            120.0,
            Some(4),
            0.56,
            0.12,
        ),
        (
            RhythmPreset::BarTransition120(
                BarTransitionVariant::ReentryDeceleratingHarmonySustainedReset,
            ),
            120.0,
            Some(4),
            0.56,
            0.12,
        ),
        (
            RhythmPreset::BarTransition120(
                BarTransitionVariant::ReentryAcceleratingHarmonyCadentialReanchor,
            ),
            120.0,
            None,
            0.56,
            0.12,
        ),
        (
            RhythmPreset::BarTransition120(
                BarTransitionVariant::ReentryDeceleratingHarmonyCadentialReanchor,
            ),
            120.0,
            None,
            0.56,
            0.12,
        ),
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::ModulationDenseFill),
            120.0,
            None,
            0.45,
            0.1,
        ),
        (
            RhythmPreset::BarTransition120(BarTransitionVariant::ModulationDenseFillExtended),
            120.0,
            None,
            0.42,
            0.12,
        ),
    ]
}
