use super::transition_fixtures::build_reentry_transition_fixture;
use super::*;

pub(super) fn build_bar_transition_reentry(
    sample_rate: u32,
    bpm: f32,
    variant: BarTransitionVariant,
) -> Option<AudioBuffer> {
    let sections: Option<Vec<GrooveSection>> = match variant {
        BarTransitionVariant::Reentry => Some(vec![GrooveSection {
            bars: 4,
            beat_pattern: [0.62, 0.24, 0.42, 0.26],
            chord_cycle: CHORD_CYCLE_ABCD,
            chord_every_bars: 1,
            section_marker: Some((0, CHORD_D, 1.1)),
            bar_patterns: None,
            bar_chords: None,
            dropout_bars: &[],
        }]),
        BarTransitionVariant::ReentryHarmonicShift => Some(vec![GrooveSection {
            bars: 4,
            beat_pattern: [0.62, 0.24, 0.42, 0.26],
            chord_cycle: CHORD_CYCLE_ABCD,
            chord_every_bars: 1,
            section_marker: Some((0, CHORD_D, 1.1)),
            bar_patterns: None,
            bar_chords: Some(REENTRY_HARMONIC_SHIFT_BAR_CHORDS),
            dropout_bars: &[],
        }]),
        BarTransitionVariant::ReentryDenseFill => Some(vec![GrooveSection {
            bars: 4,
            beat_pattern: [0.58, 0.26, 0.4, 0.26],
            chord_cycle: CHORD_CYCLE_ABCD,
            chord_every_bars: 1,
            section_marker: Some((0, CHORD_D, 1.12)),
            bar_patterns: Some(DENSE_FILL_BAR_PATTERNS),
            bar_chords: Some(DENSE_FILL_BAR_CHORDS),
            dropout_bars: &[],
        }]),
        BarTransitionVariant::ReentryAcceleratingHarmony => Some(vec![
            GrooveSection {
                bars: 2,
                beat_pattern: [0.56, 0.24, 0.38, 0.24],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 2,
                section_marker: Some((0, CHORD_B, 1.02)),
                bar_patterns: None,
                bar_chords: None,
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 2,
                beat_pattern: [0.62, 0.24, 0.42, 0.26],
                chord_cycle: CHORD_CYCLE_ABCD,
                chord_every_bars: 1,
                section_marker: Some((0, CHORD_D, 1.12)),
                bar_patterns: None,
                bar_chords: Some(REENTRY_ACCELERATING_STAGE_BAR_CHORDS),
                dropout_bars: &[],
            },
        ]),
        BarTransitionVariant::ReentryDeceleratingHarmony => Some(vec![
            GrooveSection {
                bars: 2,
                beat_pattern: [0.62, 0.24, 0.42, 0.26],
                chord_cycle: CHORD_CYCLE_ABCD,
                chord_every_bars: 1,
                section_marker: Some((0, CHORD_D, 1.12)),
                bar_patterns: None,
                bar_chords: Some(REENTRY_DECELERATING_STAGE_BAR_CHORDS),
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 2,
                beat_pattern: [0.56, 0.24, 0.38, 0.24],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 2,
                section_marker: Some((0, CHORD_B, 1.02)),
                bar_patterns: None,
                bar_chords: None,
                dropout_bars: &[],
            },
        ]),
        BarTransitionVariant::ReentryAcceleratingHarmonyDenseFill => Some(vec![
            GrooveSection {
                bars: 2,
                beat_pattern: [0.56, 0.24, 0.38, 0.24],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 2,
                section_marker: Some((0, CHORD_B, 1.02)),
                bar_patterns: Some(REENTRY_ACCELERATING_DENSE_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 2,
                beat_pattern: [0.62, 0.24, 0.42, 0.26],
                chord_cycle: CHORD_CYCLE_ABCD,
                chord_every_bars: 1,
                section_marker: Some((0, CHORD_D, 1.14)),
                bar_patterns: Some(REENTRY_DECELERATING_DENSE_BAR_PATTERNS),
                bar_chords: Some(REENTRY_ACCELERATING_STAGE_BAR_CHORDS),
                dropout_bars: &[],
            },
        ]),
        BarTransitionVariant::ReentryDeceleratingHarmonyDenseFill => Some(vec![
            GrooveSection {
                bars: 2,
                beat_pattern: [0.62, 0.24, 0.42, 0.26],
                chord_cycle: CHORD_CYCLE_ABCD,
                chord_every_bars: 1,
                section_marker: Some((0, CHORD_D, 1.14)),
                bar_patterns: Some(REENTRY_DECELERATING_DENSE_BAR_PATTERNS),
                bar_chords: Some(REENTRY_DECELERATING_STAGE_BAR_CHORDS),
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 2,
                beat_pattern: [0.56, 0.24, 0.38, 0.24],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 2,
                section_marker: Some((0, CHORD_B, 1.02)),
                bar_patterns: Some(REENTRY_ACCELERATING_DENSE_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
        ]),
        BarTransitionVariant::ReentryAcceleratingHarmonyAccentShift => Some(vec![
            GrooveSection {
                bars: 2,
                beat_pattern: [0.3, 0.64, 0.3, 0.58],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 2,
                section_marker: Some((1, CHORD_B, 1.02)),
                bar_patterns: Some(REENTRY_ACCELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 2,
                beat_pattern: [0.28, 0.66, 0.3, 0.6],
                chord_cycle: CHORD_CYCLE_ABCD,
                chord_every_bars: 1,
                section_marker: Some((1, CHORD_D, 1.12)),
                bar_patterns: Some(REENTRY_DECELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: Some(REENTRY_ACCELERATING_STAGE_BAR_CHORDS),
                dropout_bars: &[],
            },
        ]),
        BarTransitionVariant::ReentryDeceleratingHarmonyAccentShift => Some(vec![
            GrooveSection {
                bars: 2,
                beat_pattern: [0.28, 0.66, 0.3, 0.6],
                chord_cycle: CHORD_CYCLE_ABCD,
                chord_every_bars: 1,
                section_marker: Some((1, CHORD_D, 1.12)),
                bar_patterns: Some(REENTRY_DECELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: Some(REENTRY_DECELERATING_STAGE_BAR_CHORDS),
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 2,
                beat_pattern: [0.3, 0.64, 0.3, 0.58],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 2,
                section_marker: Some((1, CHORD_B, 1.02)),
                bar_patterns: Some(REENTRY_ACCELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
        ]),
        _ => None,
    };

    sections.map(|sections| build_reentry_transition_fixture(sample_rate, bpm, &sections))
}
