use super::transition_fixtures::build_reentry_transition_fixture;
use super::*;

pub(super) fn build_bar_transition_reentry_extended(
    sample_rate: u32,
    bpm: f32,
    variant: BarTransitionVariant,
) -> Option<AudioBuffer> {
    let sections: Option<Vec<GrooveSection>> = match variant {
        BarTransitionVariant::ReentryAcceleratingHarmonyReset => Some(vec![
            GrooveSection {
                bars: 2,
                beat_pattern: [0.3, 0.64, 0.3, 0.58],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 2,
                section_marker: Some((1, CHORD_B, 1.02)),
                bar_patterns: Some(REENTRY_ACCELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 2,
                beat_pattern: [0.28, 0.66, 0.3, 0.6],
                chord_cycle: CHORD_CYCLE_ABCD,
                chord_every_bars: 1,
                section_marker: Some((1, CHORD_D, 1.12)),
                bar_patterns: Some(REENTRY_DECELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: Some(REENTRY_ACCELERATING_STAGE_BAR_CHORDS),
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 4,
                beat_pattern: [0.62, 0.24, 0.42, 0.24],
                chord_cycle: CHORD_CYCLE_A,
                chord_every_bars: 1,
                section_marker: Some((0, CHORD_A, 1.12)),
                bar_patterns: Some(REENTRY_HARMONIC_RESET_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
        ]),
        BarTransitionVariant::ReentryDeceleratingHarmonyReset => Some(vec![
            GrooveSection {
                bars: 2,
                beat_pattern: [0.28, 0.66, 0.3, 0.6],
                chord_cycle: CHORD_CYCLE_ABCD,
                chord_every_bars: 1,
                section_marker: Some((1, CHORD_D, 1.12)),
                bar_patterns: Some(REENTRY_DECELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: Some(REENTRY_DECELERATING_STAGE_BAR_CHORDS),
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 2,
                beat_pattern: [0.3, 0.64, 0.3, 0.58],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 2,
                section_marker: Some((1, CHORD_B, 1.02)),
                bar_patterns: Some(REENTRY_ACCELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 4,
                beat_pattern: [0.62, 0.24, 0.42, 0.24],
                chord_cycle: CHORD_CYCLE_A,
                chord_every_bars: 1,
                section_marker: Some((0, CHORD_A, 1.12)),
                bar_patterns: Some(REENTRY_HARMONIC_RESET_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
        ]),
        BarTransitionVariant::ReentryAcceleratingHarmonySustainedReset => Some(vec![
            GrooveSection {
                bars: 2,
                beat_pattern: [0.3, 0.64, 0.3, 0.58],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 2,
                section_marker: Some((1, CHORD_B, 1.02)),
                bar_patterns: Some(REENTRY_ACCELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 2,
                beat_pattern: [0.28, 0.66, 0.3, 0.6],
                chord_cycle: CHORD_CYCLE_ABCD,
                chord_every_bars: 1,
                section_marker: Some((1, CHORD_D, 1.12)),
                bar_patterns: Some(REENTRY_DECELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: Some(REENTRY_ACCELERATING_STAGE_BAR_CHORDS),
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 6,
                beat_pattern: [0.64, 0.24, 0.44, 0.24],
                chord_cycle: CHORD_CYCLE_A,
                chord_every_bars: 1,
                section_marker: Some((0, CHORD_A, 1.14)),
                bar_patterns: Some(REENTRY_SUSTAINED_RESET_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
        ]),
        BarTransitionVariant::ReentryAcceleratingHarmonyLongSustainedReset => Some(vec![
            GrooveSection {
                bars: 2,
                beat_pattern: [0.3, 0.64, 0.3, 0.58],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 2,
                section_marker: Some((1, CHORD_B, 1.02)),
                bar_patterns: Some(REENTRY_ACCELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 2,
                beat_pattern: [0.28, 0.66, 0.3, 0.6],
                chord_cycle: CHORD_CYCLE_ABCD,
                chord_every_bars: 1,
                section_marker: Some((1, CHORD_D, 1.12)),
                bar_patterns: Some(REENTRY_DECELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: Some(REENTRY_ACCELERATING_STAGE_BAR_CHORDS),
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 8,
                beat_pattern: [0.64, 0.24, 0.44, 0.24],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 1,
                section_marker: Some((0, CHORD_A, 1.14)),
                bar_patterns: None,
                bar_chords: None,
                dropout_bars: &[],
            },
        ]),
        BarTransitionVariant::ReentryDeceleratingHarmonySustainedReset => Some(vec![
            GrooveSection {
                bars: 2,
                beat_pattern: [0.28, 0.66, 0.3, 0.6],
                chord_cycle: CHORD_CYCLE_ABCD,
                chord_every_bars: 1,
                section_marker: Some((1, CHORD_D, 1.12)),
                bar_patterns: Some(REENTRY_DECELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: Some(REENTRY_DECELERATING_STAGE_BAR_CHORDS),
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 2,
                beat_pattern: [0.3, 0.64, 0.3, 0.58],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 2,
                section_marker: Some((1, CHORD_B, 1.02)),
                bar_patterns: Some(REENTRY_ACCELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 6,
                beat_pattern: [0.64, 0.24, 0.44, 0.24],
                chord_cycle: CHORD_CYCLE_A,
                chord_every_bars: 1,
                section_marker: Some((0, CHORD_A, 1.14)),
                bar_patterns: Some(REENTRY_SUSTAINED_RESET_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
        ]),
        BarTransitionVariant::ReentryAcceleratingHarmonyCadentialReanchor => Some(vec![
            GrooveSection {
                bars: 2,
                beat_pattern: [0.3, 0.64, 0.3, 0.58],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 2,
                section_marker: Some((1, CHORD_B, 1.02)),
                bar_patterns: Some(REENTRY_ACCELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 2,
                beat_pattern: [0.28, 0.66, 0.3, 0.6],
                chord_cycle: CHORD_CYCLE_ABCD,
                chord_every_bars: 1,
                section_marker: Some((1, CHORD_D, 1.12)),
                bar_patterns: Some(REENTRY_DECELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: Some(REENTRY_ACCELERATING_STAGE_BAR_CHORDS),
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 4,
                beat_pattern: [0.72, 0.22, 0.44, 0.24],
                chord_cycle: CHORD_CYCLE_A,
                chord_every_bars: 1,
                section_marker: Some((0, CHORD_D, 1.2)),
                bar_patterns: Some(REENTRY_CADENTIAL_REANCHOR_BAR_PATTERNS),
                bar_chords: Some(REENTRY_CADENTIAL_REANCHOR_BAR_CHORDS),
                dropout_bars: &[],
            },
        ]),
        BarTransitionVariant::ReentryDeceleratingHarmonyCadentialReanchor => Some(vec![
            GrooveSection {
                bars: 2,
                beat_pattern: [0.28, 0.66, 0.3, 0.6],
                chord_cycle: CHORD_CYCLE_ABCD,
                chord_every_bars: 1,
                section_marker: Some((1, CHORD_D, 1.12)),
                bar_patterns: Some(REENTRY_DECELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: Some(REENTRY_DECELERATING_STAGE_BAR_CHORDS),
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 2,
                beat_pattern: [0.3, 0.64, 0.3, 0.58],
                chord_cycle: CHORD_CYCLE_AB,
                chord_every_bars: 2,
                section_marker: Some((1, CHORD_B, 1.02)),
                bar_patterns: Some(REENTRY_ACCELERATING_ACCENT_SHIFT_BAR_PATTERNS),
                bar_chords: None,
                dropout_bars: &[],
            },
            GrooveSection {
                bars: 4,
                beat_pattern: [0.72, 0.22, 0.44, 0.24],
                chord_cycle: CHORD_CYCLE_A,
                chord_every_bars: 1,
                section_marker: Some((0, CHORD_D, 1.2)),
                bar_patterns: Some(REENTRY_CADENTIAL_REANCHOR_BAR_PATTERNS),
                bar_chords: Some(REENTRY_CADENTIAL_REANCHOR_BAR_CHORDS),
                dropout_bars: &[],
            },
        ]),
        _ => None,
    };

    sections.map(|sections| build_reentry_transition_fixture(sample_rate, bpm, &sections))
}
