use super::*;

#[derive(Clone, Debug, PartialEq)]
/// Combines a [`RuntimeObservationReport`] with the host audio I/O summary
/// captured in the same tick.  Used when the host pump is in scope and
/// hardware metrics should be included alongside runtime diagnostics.
pub struct RuntimeHostObservationReport {
    /// Runtime observation report captured in this tick.
    pub observation: RuntimeObservationReport,
    /// Host audio I/O summary captured alongside the observation report.
    pub host_io: RuntimeHostIoSummary,
}

impl RuntimeHostObservationReport {
    /// Constructs a report from separate observation and host I/O summaries.
    pub fn new(observation: RuntimeObservationReport, host_io: RuntimeHostIoSummary) -> Self {
        Self {
            observation,
            host_io,
        }
    }

    /// Renders a single-line summary of the observation and host I/O fields.
    pub fn render_compact(&self) -> String {
        format!(
            "{} host_backend={} host_device={} host_stream_state={:?} host_clock_source={:?} host_clock_domain={:?} host_clock_fallback_state={:?} host_clock_transition_state={:?} host_clock_drift_state={:?} host_clock_discontinuity_state={:?} host_duplex_mismatch_state={:?} host_endpoint_topology={:?} host_partial_availability={} host_clock_crossing_required={} host_clock_processing_sample_rate={} host_clock_hardware_sample_rate={} host_clock_ownership={:?} host_clock_restart_policy={:?} host_callback_interval_ms={:.3} host_output_latency_samples={} host_graph_latency_samples={} host_estimated_output_latency_samples={} host_backend_health={:?} host_backend_xruns={} host_backend_device_losses={} host_backend_restart_attempts={} host_backend_restart_failures={} host_audio_callbacks={} host_audio_frames={} host_audio_copied_samples={} host_audio_zero_filled_samples={} host_audio_dropped_samples={} host_audio_peak={:?} host_audio_graph={:?} host_audio_graph_matches_runtime={}",
            self.observation.render_compact(),
            self.host_io.hardware.backend_name,
            self.host_io.hardware.device_id,
            self.host_io.audio_pump.stream_state,
            self.host_io.clocking.clock_source,
            self.host_io.clocking.clock_domain,
            self.host_io.clocking.fallback_state,
            self.host_io.clocking.transition_state,
            self.host_io.clocking.drift_state,
            self.host_io.clocking.discontinuity_state,
            self.host_io.clocking.duplex_mismatch_state,
            self.host_io.clocking.endpoint_topology,
            self.host_io.clocking.partial_availability,
            self.host_io.clocking.crossing_required,
            self.host_io.clocking.processing_sample_rate_hz,
            self.host_io.clocking.hardware_sample_rate_hz,
            self.host_io.clocking.ownership,
            self.host_io.clocking.restart_policy,
            self.host_io.clocking.callback_interval_ms,
            self.host_io.latency.output_latency_samples,
            self.host_io.latency.graph_latency_samples,
            self.host_io.latency.estimated_output_latency_samples,
            self.host_io.hardware.backend_health,
            self.host_io.hardware.xrun_count,
            self.host_io.hardware.device_loss_count,
            self.host_io.hardware.restart_attempt_count,
            self.host_io.hardware.restart_failure_count,
            self.host_io.audio_pump.callback_count,
            self.host_io.audio_pump.total_callback_frames,
            self.host_io.audio_pump.copied_output_samples,
            self.host_io.audio_pump.zero_filled_output_samples,
            self.host_io.audio_pump.dropped_output_samples,
            self.host_io.audio_pump.last_callback_output_peak,
            self.host_io.audio_pump.last_runtime_graph_id,
            self.host_io.runtime_graph_id_matches_pump,
        )
    }

    /// Renders a multi-line diagnostic string with one field per line.
    pub fn render_multiline(&self) -> String {
        format!(
            concat!(
                "observation={}",
                "\nhost_backend={}",
                "\nhost_device_id={}",
                "\nhost_device_name={}",
                "\nhost_sample_rate={}",
                "\nhost_buffer_size={}",
                "\nhost_output_channels={}",
                "\nhost_sample_format={:?}",
                "\nhost_simulated={}",
                "\nhost_clock_source={:?}",
                "\nhost_clock_domain={:?}",
                "\nhost_clock_fallback_state={:?}",
                "\nhost_clock_transition_state={:?}",
                "\nhost_clock_drift_state={:?}",
                "\nhost_clock_discontinuity_state={:?}",
                "\nhost_duplex_mismatch_state={:?}",
                "\nhost_endpoint_topology={:?}",
                "\nhost_partial_availability={}",
                "\nhost_clock_crossing_required={}",
                "\nhost_clock_processing_sample_rate_hz={}",
                "\nhost_clock_hardware_sample_rate_hz={}",
                "\nhost_clock_ownership={:?}",
                "\nhost_clock_restart_policy={:?}",
                "\nhost_callback_interval_ms={:.3}",
                "\nhost_input_latency_samples={:?}",
                "\nhost_output_latency_samples={}",
                "\nhost_round_trip_latency_samples={:?}",
                "\nhost_graph_latency_samples={}",
                "\nhost_estimated_output_latency_samples={}",
                "\nhost_estimated_round_trip_latency_samples={:?}",
                "\nhost_output_latency_ms={:.3}",
                "\nhost_graph_latency_ms={:.3}",
                "\nhost_estimated_output_latency_ms={:.3}",
                "\nhost_estimated_round_trip_latency_ms={:?}",
                "\nhost_backend_health={:?}",
                "\nhost_backend_xruns={}",
                "\nhost_backend_callback_overruns={}",
                "\nhost_backend_device_losses={}",
                "\nhost_backend_restart_attempts={}",
                "\nhost_backend_restart_failures={}",
                "\nhost_audio_stream_state={:?}",
                "\nhost_audio_callback_count={}",
                "\nhost_audio_total_callback_frames={}",
                "\nhost_audio_total_runtime_output_frames={}",
                "\nhost_audio_copied_output_samples={}",
                "\nhost_audio_zero_filled_output_samples={}",
                "\nhost_audio_dropped_output_samples={}",
                "\nhost_audio_last_callback_output_peak={:?}",
                "\nhost_audio_last_runtime_graph_id={:?}",
                "\nhost_audio_graph_matches_runtime={}",
            ),
            self.observation.render_compact(),
            self.host_io.hardware.backend_name,
            self.host_io.hardware.device_id,
            self.host_io.hardware.device_name,
            self.host_io.hardware.sample_rate,
            self.host_io.hardware.buffer_size,
            self.host_io.hardware.output_channels,
            self.host_io.hardware.sample_format,
            self.host_io.hardware.simulated,
            self.host_io.clocking.clock_source,
            self.host_io.clocking.clock_domain,
            self.host_io.clocking.fallback_state,
            self.host_io.clocking.transition_state,
            self.host_io.clocking.drift_state,
            self.host_io.clocking.discontinuity_state,
            self.host_io.clocking.duplex_mismatch_state,
            self.host_io.clocking.endpoint_topology,
            self.host_io.clocking.partial_availability,
            self.host_io.clocking.crossing_required,
            self.host_io.clocking.processing_sample_rate_hz,
            self.host_io.clocking.hardware_sample_rate_hz,
            self.host_io.clocking.ownership,
            self.host_io.clocking.restart_policy,
            self.host_io.clocking.callback_interval_ms,
            self.host_io.latency.input_latency_samples,
            self.host_io.latency.output_latency_samples,
            self.host_io.latency.round_trip_latency_samples,
            self.host_io.latency.graph_latency_samples,
            self.host_io.latency.estimated_output_latency_samples,
            self.host_io.latency.estimated_round_trip_latency_samples,
            self.host_io.latency.output_latency_ms,
            self.host_io.latency.graph_latency_ms,
            self.host_io.latency.estimated_output_latency_ms,
            self.host_io.latency.estimated_round_trip_latency_ms,
            self.host_io.hardware.backend_health,
            self.host_io.hardware.xrun_count,
            self.host_io.hardware.callback_overrun_count,
            self.host_io.hardware.device_loss_count,
            self.host_io.hardware.restart_attempt_count,
            self.host_io.hardware.restart_failure_count,
            self.host_io.audio_pump.stream_state,
            self.host_io.audio_pump.callback_count,
            self.host_io.audio_pump.total_callback_frames,
            self.host_io.audio_pump.total_runtime_output_frames,
            self.host_io.audio_pump.copied_output_samples,
            self.host_io.audio_pump.zero_filled_output_samples,
            self.host_io.audio_pump.dropped_output_samples,
            self.host_io.audio_pump.last_callback_output_peak,
            self.host_io.audio_pump.last_runtime_graph_id,
            self.host_io.runtime_graph_id_matches_pump,
        )
    }
}
