use super::*;

impl RuntimeHostObservationReport {
    /// Renders this observation report as a JSON object string.
    pub fn render_json(&self) -> String {
        format!(
            "{{\"observation\":{},\"host_io\":{}}}",
            self.observation.render_json(),
            render_host_io_json(&self.host_io),
        )
    }
}

fn render_host_io_json(host_io: &RuntimeHostIoSummary) -> String {
    format!(
        concat!(
            "{{",
            "\"backend_name\":{},",
            "\"linux_backend_identity\":{},",
            "\"linux_backend_portability\":{},",
            "\"linux_clocking_parity\":{},",
            "\"linux_duplex_parity\":{},",
            "\"linux_endpoint_topology_parity\":{},",
            "\"device_id\":{},",
            "\"device_name\":{},",
            "\"sample_rate\":{},",
            "\"buffer_size\":{},",
            "\"output_channels\":{},",
            "\"sample_format\":{},",
            "\"simulated\":{},",
            "\"clock_source\":{},",
            "\"clock_domain\":{},",
            "\"fallback_state\":{},",
            "\"transition_state\":{},",
            "\"drift_state\":{},",
            "\"discontinuity_state\":{},",
            "\"duplex_mismatch_state\":{},",
            "\"endpoint_topology\":{},",
            "\"partial_availability\":{},",
            "\"crossing_required\":{},",
            "\"processing_sample_rate_hz\":{},",
            "\"hardware_sample_rate_hz\":{},",
            "\"ownership\":{},",
            "\"restart_policy\":{},",
            "\"callback_interval_ms\":{},",
            "\"input_latency_samples\":{},",
            "\"output_latency_samples\":{},",
            "\"round_trip_latency_samples\":{},",
            "\"graph_latency_samples\":{},",
            "\"estimated_output_latency_samples\":{},",
            "\"estimated_round_trip_latency_samples\":{},",
            "\"output_latency_ms\":{},",
            "\"graph_latency_ms\":{},",
            "\"estimated_output_latency_ms\":{},",
            "\"estimated_round_trip_latency_ms\":{},",
            "\"backend_health\":{},",
            "\"xrun_count\":{},",
            "\"callback_overrun_count\":{},",
            "\"device_loss_count\":{},",
            "\"restart_attempt_count\":{},",
            "\"restart_failure_count\":{},",
            "\"stream_state\":{},",
            "\"max_callback_frames\":{},",
            "\"max_transfer_channels\":{},",
            "\"zero_fill_unwritten_output\":{},",
            "\"callback_count\":{},",
            "\"total_callback_frames\":{},",
            "\"total_runtime_output_frames\":{},",
            "\"copied_output_samples\":{},",
            "\"zero_filled_output_samples\":{},",
            "\"dropped_output_samples\":{},",
            "\"last_callback_output_peak\":{},",
            "\"last_runtime_graph_id\":{},",
            "\"runtime_graph_id_matches_pump\":{}",
            "}}"
        ),
        json_option_string(Some(host_io.hardware.backend_name.as_str())),
        json_string(&format!("{:?}", host_io.hardware.linux_backend_identity)),
        json_string(&format!("{:?}", host_io.hardware.linux_backend_portability)),
        json_string(&format!("{:?}", host_io.clocking.linux_clocking_parity)),
        json_string(&format!("{:?}", host_io.clocking.linux_duplex_parity)),
        json_string(&format!(
            "{:?}",
            host_io.clocking.linux_endpoint_topology_parity
        )),
        json_option_string(Some(host_io.hardware.device_id.as_str())),
        json_option_string(Some(host_io.hardware.device_name.as_str())),
        host_io.hardware.sample_rate,
        host_io.hardware.buffer_size,
        host_io.hardware.output_channels,
        json_option_string(Some(match host_io.hardware.sample_format {
            AudioSampleFormat::F32 => "F32",
            AudioSampleFormat::I16 => "I16",
            AudioSampleFormat::I32 => "I32",
        })),
        host_io.hardware.simulated,
        json_option_string(Some(match host_io.clocking.clock_source {
            RuntimeHostClockSource::Internal => "Internal",
            RuntimeHostClockSource::ExternalWordClock => "ExternalWordClock",
            RuntimeHostClockSource::DigitalInput => "DigitalInput",
            RuntimeHostClockSource::Virtual => "Virtual",
        })),
        json_option_string(Some(match host_io.clocking.clock_domain {
            RuntimeHostClockDomain::SameClock => "SameClock",
            RuntimeHostClockDomain::CrossClock => "CrossClock",
            RuntimeHostClockDomain::Aggregate => "Aggregate",
            RuntimeHostClockDomain::Degraded => "Degraded",
        })),
        json_option_string(Some(match host_io.clocking.fallback_state {
            RuntimeHostClockFallbackState::Direct => "Direct",
            RuntimeHostClockFallbackState::RuntimeResampled => "RuntimeResampled",
            RuntimeHostClockFallbackState::RecoveryConstrained => "RecoveryConstrained",
            RuntimeHostClockFallbackState::Unconfigured => "Unconfigured",
        })),
        json_option_string(Some(match host_io.clocking.transition_state {
            RuntimeHostClockTransitionState::InitialObservation => "InitialObservation",
            RuntimeHostClockTransitionState::Stable => "Stable",
            RuntimeHostClockTransitionState::EnteredAggregateClock => "EnteredAggregateClock",
            RuntimeHostClockTransitionState::EnteredCrossClockFallback =>
                "EnteredCrossClockFallback",
            RuntimeHostClockTransitionState::EnteredRecoveryFallback => "EnteredRecoveryFallback",
            RuntimeHostClockTransitionState::ReturnedToDirect => "ReturnedToDirect",
            RuntimeHostClockTransitionState::LostConfiguration => "LostConfiguration",
            RuntimeHostClockTransitionState::Reconfigured => "Reconfigured",
        })),
        json_option_string(Some(match host_io.clocking.drift_state {
            RuntimeHostClockDriftState::Stable => "Stable",
            RuntimeHostClockDriftState::CrossClockManaged => "CrossClockManaged",
            RuntimeHostClockDriftState::AggregateManaged => "AggregateManaged",
            RuntimeHostClockDriftState::Resyncing => "Resyncing",
            RuntimeHostClockDriftState::Unconfigured => "Unconfigured",
        })),
        json_option_string(Some(match host_io.clocking.discontinuity_state {
            RuntimeHostClockDiscontinuityState::Continuous => "Continuous",
            RuntimeHostClockDiscontinuityState::Reconfigured => "Reconfigured",
            RuntimeHostClockDiscontinuityState::Recovering => "Recovering",
            RuntimeHostClockDiscontinuityState::LostConfiguration => "LostConfiguration",
            RuntimeHostClockDiscontinuityState::Faulted => "Faulted",
        })),
        json_option_string(Some(match host_io.clocking.duplex_mismatch_state {
            RuntimeHostDuplexMismatchState::NotApplicable => "NotApplicable",
            RuntimeHostDuplexMismatchState::Aligned => "Aligned",
            RuntimeHostDuplexMismatchState::CrossClockDiverged => "CrossClockDiverged",
            RuntimeHostDuplexMismatchState::PartialAvailability => "PartialAvailability",
            RuntimeHostDuplexMismatchState::Degraded => "Degraded",
        })),
        json_option_string(Some(match host_io.clocking.endpoint_topology {
            RuntimeHostEndpointTopology::Unconfigured => "Unconfigured",
            RuntimeHostEndpointTopology::OutputOnly => "OutputOnly",
            RuntimeHostEndpointTopology::InputOnly => "InputOnly",
            RuntimeHostEndpointTopology::Duplex => "Duplex",
            RuntimeHostEndpointTopology::Aggregate => "Aggregate",
        })),
        host_io.clocking.partial_availability,
        host_io.clocking.crossing_required,
        host_io.clocking.processing_sample_rate_hz,
        host_io.clocking.hardware_sample_rate_hz,
        json_option_string(Some(match host_io.clocking.ownership {
            RuntimeHostLifecycleOwnership::HostDrivenCallback => "HostDrivenCallback",
            RuntimeHostLifecycleOwnership::BackendManagedCallback => "BackendManagedCallback",
        })),
        json_option_string(Some(match host_io.clocking.restart_policy {
            RuntimeHostRestartPolicy::HostMustRestart => "HostMustRestart",
            RuntimeHostRestartPolicy::BackendMayRestart => "BackendMayRestart",
        })),
        host_io.clocking.callback_interval_ms,
        json_option_u32(host_io.latency.input_latency_samples),
        host_io.latency.output_latency_samples,
        json_option_u32(host_io.latency.round_trip_latency_samples),
        host_io.latency.graph_latency_samples,
        host_io.latency.estimated_output_latency_samples,
        json_option_u32(host_io.latency.estimated_round_trip_latency_samples),
        host_io.latency.output_latency_ms,
        host_io.latency.graph_latency_ms,
        host_io.latency.estimated_output_latency_ms,
        json_option_f32(host_io.latency.estimated_round_trip_latency_ms),
        json_option_string(Some(match host_io.hardware.backend_health {
            BackendHealth::Healthy => "Healthy",
            BackendHealth::Degraded => "Degraded",
            BackendHealth::Recovering => "Recovering",
        })),
        host_io.hardware.xrun_count,
        host_io.hardware.callback_overrun_count,
        host_io.hardware.device_loss_count,
        host_io.hardware.restart_attempt_count,
        host_io.hardware.restart_failure_count,
        json_option_string(Some(match host_io.audio_pump.stream_state {
            RuntimeHostAudioStreamState::Stopped => "Stopped",
            RuntimeHostAudioStreamState::Running => "Running",
            RuntimeHostAudioStreamState::Faulted => "Faulted",
        })),
        host_io.audio_pump.transfer_policy.max_callback_frames,
        host_io.audio_pump.transfer_policy.max_transfer_channels,
        host_io
            .audio_pump
            .transfer_policy
            .zero_fill_unwritten_output,
        host_io.audio_pump.callback_count,
        host_io.audio_pump.total_callback_frames,
        host_io.audio_pump.total_runtime_output_frames,
        host_io.audio_pump.copied_output_samples,
        host_io.audio_pump.zero_filled_output_samples,
        host_io.audio_pump.dropped_output_samples,
        json_option_f32(host_io.audio_pump.last_callback_output_peak),
        json_option_string(host_io.audio_pump.last_runtime_graph_id.as_deref()),
        host_io.runtime_graph_id_matches_pump,
    )
}
