use super::*;

pub(super) fn json_runtime_linux_backend_session_snapshot(
    snapshot: &RuntimeLinuxBackendSessionSnapshot,
) -> String {
    format!(
        concat!(
            "{{",
            "\"backend_identity\":{},",
            "\"backend_name\":{},",
            "\"portability_band\":{},",
            "\"ownership\":{},",
            "\"lifecycle_state\":{},",
            "\"device_claim_posture\":{},",
            "\"session_role\":{},",
            "\"ownership_fallback\":{},",
            "\"device_id\":{},",
            "\"device_name\":{},",
            "\"stream_state\":{},",
            "\"backend_health\":{},",
            "\"simulated\":{},",
            "\"device_loss_count\":{},",
            "\"restart_attempt_count\":{},",
            "\"restart_failure_count\":{},",
            "\"summary\":{}",
            "}}"
        ),
        json_string(&format!("{:?}", snapshot.backend_identity)),
        json_option_string(Some(snapshot.backend_name.as_str())),
        json_string(&format!("{:?}", snapshot.portability_band)),
        json_string(&format!("{:?}", snapshot.ownership)),
        json_string(&format!("{:?}", snapshot.lifecycle_state)),
        json_string(&format!("{:?}", snapshot.device_claim_posture)),
        json_string(&format!("{:?}", snapshot.session_role)),
        json_string(&format!("{:?}", snapshot.ownership_fallback)),
        json_option_string(Some(snapshot.device_id.as_str())),
        json_option_string(Some(snapshot.device_name.as_str())),
        json_string(&format!("{:?}", snapshot.stream_state)),
        json_string(&format!("{:?}", snapshot.backend_health)),
        snapshot.simulated,
        snapshot.device_loss_count,
        snapshot.restart_attempt_count,
        snapshot.restart_failure_count,
        json_option_string(Some(snapshot.summary.as_str())),
    )
}

pub(super) fn json_runtime_pipewire_alsa_parity_snapshot(
    snapshot: &RuntimePipeWireAlsaParitySnapshot,
) -> String {
    format!(
        concat!(
            "{{",
            "\"backend_identity\":{},",
            "\"backend_name\":{},",
            "\"portability_band\":{},",
            "\"session_role_parity\":{},",
            "\"device_claim_parity\":{},",
            "\"stream_policy_parity\":{},",
            "\"guarded_state\":{},",
            "\"lifecycle_ownership\":{},",
            "\"restart_policy\":{},",
            "\"clock_domain\":{},",
            "\"fallback_state\":{},",
            "\"device_id\":{},",
            "\"device_name\":{},",
            "\"stream_state\":{},",
            "\"backend_health\":{},",
            "\"simulated\":{},",
            "\"device_loss_count\":{},",
            "\"restart_attempt_count\":{},",
            "\"restart_failure_count\":{},",
            "\"summary\":{}",
            "}}"
        ),
        json_string(&format!("{:?}", snapshot.backend_identity)),
        json_option_string(Some(snapshot.backend_name.as_str())),
        json_string(&format!("{:?}", snapshot.portability_band)),
        json_string(&format!("{:?}", snapshot.session_role_parity)),
        json_string(&format!("{:?}", snapshot.device_claim_parity)),
        json_string(&format!("{:?}", snapshot.stream_policy_parity)),
        json_string(&format!("{:?}", snapshot.guarded_state)),
        json_string(&format!("{:?}", snapshot.lifecycle_ownership)),
        json_string(&format!("{:?}", snapshot.restart_policy)),
        json_string(&format!("{:?}", snapshot.clock_domain)),
        json_string(&format!("{:?}", snapshot.fallback_state)),
        json_option_string(Some(snapshot.device_id.as_str())),
        json_option_string(Some(snapshot.device_name.as_str())),
        json_string(&format!("{:?}", snapshot.stream_state)),
        json_string(&format!("{:?}", snapshot.backend_health)),
        snapshot.simulated,
        snapshot.device_loss_count,
        snapshot.restart_attempt_count,
        snapshot.restart_failure_count,
        json_option_string(Some(snapshot.summary.as_str())),
    )
}

pub(super) fn json_runtime_jack_coordination_snapshot(
    snapshot: &RuntimeJackCoordinationSnapshot,
) -> String {
    format!(
        concat!(
            "{{",
            "\"backend_identity\":{},",
            "\"backend_name\":{},",
            "\"portability_band\":{},",
            "\"transport_posture\":{},",
            "\"graph_state\":{},",
            "\"client_role\":{},",
            "\"guarded_state\":{},",
            "\"device_id\":{},",
            "\"device_name\":{},",
            "\"session_state\":{},",
            "\"currently_attached\":{},",
            "\"heartbeat_freshness\":{},",
            "\"dispatch_state\":{},",
            "\"attach_events\":{},",
            "\"detach_requested_events\":{},",
            "\"detached_events\":{},",
            "\"backend_health\":{},",
            "\"simulated\":{},",
            "\"summary\":{}",
            "}}"
        ),
        json_string(&format!("{:?}", snapshot.backend_identity)),
        json_option_string(Some(snapshot.backend_name.as_str())),
        json_string(&format!("{:?}", snapshot.portability_band)),
        json_string(&format!("{:?}", snapshot.transport_posture)),
        json_string(&format!("{:?}", snapshot.graph_state)),
        json_string(&format!("{:?}", snapshot.client_role)),
        json_string(&format!("{:?}", snapshot.guarded_state)),
        json_option_string(Some(snapshot.device_id.as_str())),
        json_option_string(Some(snapshot.device_name.as_str())),
        json_string(&format!("{:?}", snapshot.session_state)),
        snapshot.currently_attached,
        json_string(&format!("{:?}", snapshot.heartbeat_freshness)),
        json_string(&format!("{:?}", snapshot.dispatch_state)),
        snapshot.attach_events,
        snapshot.detach_requested_events,
        snapshot.detached_events,
        json_string(&format!("{:?}", snapshot.backend_health)),
        snapshot.simulated,
        json_option_string(Some(snapshot.summary.as_str())),
    )
}
