use super::*;

mod performance_snapshot_render;
pub(crate) use performance_snapshot_render::runtime_execution_lane_name;
mod performance_snapshot_capture;

#[derive(Clone, Debug, PartialEq)]
pub struct RuntimePerformanceSnapshot {
    pub sample_rate_hz: u32,
    pub block_size: usize,
    pub processed_block_count: u64,
    pub last_block_sequence: Option<u64>,
    pub cpu_load_percent: f32,
    pub graph_latency_ms: f32,
    pub last_block_execution_time_ns: Option<u64>,
    pub last_block_deadline_budget_ns: Option<u64>,
    pub last_block_budget_utilization_percent: Option<f32>,
    pub last_block_budget_overrun_ns: Option<u64>,
    pub last_block_deadline_pressure: RuntimeBlockDeadlinePressure,
    pub budget_overrun_count: u64,
    pub peak_block_execution_time_ns: u64,
    pub peak_block_budget_utilization_percent: f32,
    pub peak_block_budget_overrun_ns: u64,
    pub xrun_count: u64,
    pub scheduler_phase_count: usize,
    pub scheduler_lane_count: usize,
    pub scheduler_dispatch_count: usize,
    pub scheduler_prepared_dispatch_count: usize,
    pub scheduler_realtime_dispatch_count: usize,
    pub scheduler_dispatch_handoff_count: usize,
    pub scheduler_topology_compatible: bool,
    pub scheduler_topology_requires_host_reinterpretation: bool,
    pub scheduler_topology_issue_count: usize,
    pub prework_service_state: RuntimePreworkServiceState,
    pub prework_service_pressure: RuntimePreworkServicePressure,
    pub prework_service_semantic_policy: RuntimePreworkServiceSemanticPolicy,
    pub pending_prework_target_count: usize,
    pub pending_prework_deferred_target_count: usize,
    pub prework_queue_depth: usize,
    pub prework_peak_queue_depth: usize,
    pub prework_service_cycle_count: u64,
    pub prework_service_starvation_count: u64,
    pub prework_service_throttle_count: u64,
    pub prework_service_yield_count: u64,
    pub last_prework_service_effective_cycles: usize,
    pub last_prework_service_budget_per_cycle: Option<usize>,
    pub last_prework_service_effective_budget_per_cycle: Option<usize>,
    pub last_prework_serviced_backlog_class: Option<String>,
    pub transport_gate_active: bool,
    pub plugin_gate_active: bool,
    pub hot_latency_node_id: Option<String>,
    pub hot_latency_node_group: Option<String>,
    pub hot_latency_node_topology_role: Option<String>,
    pub hot_latency_node_plugin_sandbox_id: Option<String>,
    pub hot_latency_node_samples: u32,
    pub hot_latency_group: Option<String>,
    pub hot_latency_group_node_count: usize,
    pub hot_latency_group_total_samples: u32,
    pub critical_path_lane: Option<String>,
    pub critical_path_lane_node_count: usize,
    pub critical_path_lane_plugin_backed_node_count: usize,
    pub critical_path_lane_planning_group_count: usize,
    pub critical_path_lane_total_latency_samples: u32,
    pub worker_lane_summaries: Vec<RuntimeWorkerLaneInstrumentationSummary>,
    pub background_service_class: Option<RuntimeDeferredServiceClass>,
    pub background_service_decision: Option<RuntimeDeferredServiceDecision>,
    pub background_service_reason: Option<RuntimeDeferredServiceReason>,
    pub background_service_priority_band: Option<RuntimeDeferredServicePriorityBand>,
    pub background_service_blocking_priority_band: Option<RuntimeDeferredServicePriorityBand>,
    pub background_service_backpressure_source: Option<RuntimeDeferredServiceBackpressureSource>,
    pub background_service_starvation_risk: bool,
    pub background_service_starved_work_item_count: usize,
    pub background_service_cancellation_cause: Option<RuntimeDeferredServiceCancellationCause>,
    pub background_service_cancelled_work_item_count: usize,
    pub background_queued_work_item_count: usize,
    pub background_deferred_work_item_count: usize,
    pub background_pending_cleanup_work_item_count: usize,
    pub background_pending_retry_work_item_count: usize,
    pub summary: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RuntimeWorkerLaneInstrumentationSummary {
    pub lane: GraphExecutionLane,
    pub node_count: usize,
    pub plugin_backed_node_count: usize,
    pub planning_group_count: usize,
    pub total_latency_samples: u32,
    pub max_node_latency_samples: u32,
}
