use signal_ipc::SharedMemoryTransportPayload;

/// A byte range within a shared-memory mapping.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SharedMemoryRegion {
    /// Byte offset from the start of the mapping.
    pub offset_bytes: u32,
    /// Number of bytes in this region.
    pub size_bytes: u32,
}

/// Describes the layout of all regions within a single shared-memory block mapping.
///
/// All offsets are relative to the start of the mapped buffer. The host and sandbox both hold
/// a copy of the same `SharedMemoryLayout` so they can slice the buffer without communicating
/// offsets on every block.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SharedMemoryLayout {
    /// Region containing audio input samples (host → plugin).
    pub audio_input: SharedMemoryRegion,
    /// Region containing audio output samples (plugin → host).
    pub audio_output: SharedMemoryRegion,
    /// Region containing input events (host → plugin).
    pub event_input: SharedMemoryRegion,
    /// Region containing output events generated by the plugin (plugin → host).
    pub event_output: SharedMemoryRegion,
    /// Region containing the [`BlockProcessingHeader`](crate::BlockProcessingHeader) and [`PluginRenderContext`](crate::PluginRenderContext).
    pub render_context: SharedMemoryRegion,
    /// Region containing the [`BlockProcessResult`](crate::BlockProcessResult).
    pub completion: SharedMemoryRegion,
}

impl SharedMemoryLayout {
    /// Builds a layout for a single-block mapping with the given audio and event byte budgets.
    ///
    /// Regions are laid out contiguously: audio_input → audio_output → event_input →
    /// event_output → render_context (256 bytes) → completion (64 bytes).
    pub fn single_block(total_audio_bytes: u32, total_event_bytes: u32) -> Self {
        let audio_input = SharedMemoryRegion {
            offset_bytes: 0,
            size_bytes: total_audio_bytes,
        };
        let audio_output = SharedMemoryRegion {
            offset_bytes: audio_input.offset_bytes + audio_input.size_bytes,
            size_bytes: total_audio_bytes,
        };
        let event_input = SharedMemoryRegion {
            offset_bytes: audio_output.offset_bytes + audio_output.size_bytes,
            size_bytes: total_event_bytes,
        };
        let event_output = SharedMemoryRegion {
            offset_bytes: event_input.offset_bytes + event_input.size_bytes,
            size_bytes: total_event_bytes,
        };
        let render_context = SharedMemoryRegion {
            offset_bytes: event_output.offset_bytes + event_output.size_bytes,
            size_bytes: 256,
        };
        let completion = SharedMemoryRegion {
            offset_bytes: render_context.offset_bytes + render_context.size_bytes,
            size_bytes: 64,
        };

        Self {
            audio_input,
            audio_output,
            event_input,
            event_output,
            render_context,
            completion,
        }
    }

    /// Returns the total number of bytes required for this layout.
    pub fn total_bytes(self) -> u32 {
        self.completion.offset_bytes + self.completion.size_bytes
    }

    /// Returns an immutable slice of `bytes` corresponding to `region`.
    ///
    /// Returns an error if the region falls outside `bytes`.
    pub fn region_slice<'a>(
        &self,
        bytes: &'a [u8],
        region: SharedMemoryRegion,
    ) -> Result<&'a [u8], &'static str> {
        let start = region.offset_bytes as usize;
        let end = start + region.size_bytes as usize;
        bytes
            .get(start..end)
            .ok_or("shared-memory region exceeds mapped transport size")
    }

    /// Returns a mutable slice of `bytes` corresponding to `region`.
    ///
    /// Returns an error if the region falls outside `bytes`.
    pub fn region_slice_mut<'a>(
        &self,
        bytes: &'a mut [u8],
        region: SharedMemoryRegion,
    ) -> Result<&'a mut [u8], &'static str> {
        let start = region.offset_bytes as usize;
        let end = start + region.size_bytes as usize;
        bytes
            .get_mut(start..end)
            .ok_or("shared-memory region exceeds mapped transport size")
    }
}

/// An active allocation of a shared-memory buffer for a specific processing epoch.
///
/// The lease tracks the buffer contents, the IPC transport handle, and which epochs have been
/// invalidated, allowing the host to detect and reject stale block results.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SharedMemoryLease {
    /// Unique identifier for this lease.
    pub lease_id: String,
    /// The processing epoch this lease was created for.
    pub processing_epoch: u64,
    /// Layout of the regions within the leased buffer.
    pub layout: SharedMemoryLayout,
    transport: Option<SharedMemoryTransportPayload>,
    bytes: Vec<u8>,
    invalidated_epochs: Vec<u64>,
}

impl SharedMemoryLease {
    /// Creates a new lease with a zeroed buffer sized to `layout.total_bytes()`.
    pub fn new(
        lease_id: impl Into<String>,
        processing_epoch: u64,
        layout: SharedMemoryLayout,
    ) -> Self {
        Self {
            lease_id: lease_id.into(),
            processing_epoch,
            layout,
            transport: None,
            bytes: vec![0; layout.total_bytes() as usize],
            invalidated_epochs: Vec::new(),
        }
    }

    /// Attaches an IPC transport handle to this lease.
    pub fn with_transport(mut self, transport: SharedMemoryTransportPayload) -> Self {
        self.transport = Some(transport);
        self
    }

    /// Returns the total number of bytes in the leased buffer.
    pub fn total_bytes(&self) -> u32 {
        self.layout.total_bytes()
    }

    /// Returns a read-only view of the leased buffer.
    pub fn bytes(&self) -> &[u8] {
        &self.bytes
    }

    /// Marks `epoch` as invalidated; returns `false` if it was already invalidated.
    pub fn invalidate_epoch(&mut self, epoch: u64) -> bool {
        if !self.invalidated_epochs.contains(&epoch) {
            self.invalidated_epochs.push(epoch);
            return true;
        }
        false
    }

    /// Returns `true` if `epoch` matches the lease epoch and has not been invalidated.
    pub fn is_epoch_valid(&self, epoch: u64) -> bool {
        self.processing_epoch == epoch && !self.invalidated_epochs.contains(&epoch)
    }

    /// Returns the list of epochs that have been invalidated on this lease.
    pub fn invalidated_epochs(&self) -> &[u64] {
        &self.invalidated_epochs
    }

    /// Binds an IPC transport handle, replacing any previously bound handle.
    pub fn bind_transport(&mut self, transport: SharedMemoryTransportPayload) {
        self.transport = Some(transport);
    }

    /// Returns the bound IPC transport handle, if any.
    pub fn transport(&self) -> Option<&SharedMemoryTransportPayload> {
        self.transport.as_ref()
    }
}
