//! Embeddable runtime orchestration and typed runtime-host interfaces for
//! Signal.
//!
//! The crate owns the control-plane and observation-plane around executable
//! graph processing: graph projection, transport and parameter application,
//! anticipative prework policy, and supervisor-facing runtime snapshots.

mod interfaces;
mod runtime;

pub use interfaces::{
    ActiveTransportConcurrencySession, BackendPolicyOverride, BlockDispatchRecord,
    BlockDispatchStage, BrokerFailureRecord, BrokerFailureStage, BrokerInvalidationRecord,
    BrokerInvalidationStage, CompletionSlotRecord, CompletionSlotStage, DegradedReason,
    EffectiveRuntimeConfig, GraphContractProjection, GraphNodeBufferContractProjection,
    GraphNodeBusEndpointProjection, GraphNodeContractProjection, GraphNodeProjection,
    GraphNodeTopologyProjection, GraphProjection, HandshakeRequest, HandshakeResponse,
    HeartbeatCycleRecord, HeartbeatCycleStage, LeaseRolloverRecord, LingeringCleanupMode,
    LingeringCleanupPlan, LingeringCleanupQueueReceipt, LingeringCleanupTrigger, LoopRegion,
    ParameterBatch, ParameterEvent, PluginBackedNodeBinding, PluginBackedNodeBindingProjection,
    PluginFaultKind, PluginFaultRecord, PluginNodeRender, PluginNodeRenderBatch,
    PluginSandboxInstanceFaultRecord, PluginSandboxInstanceStateRecord,
    PluginSandboxLifecycleRecord, PluginSandboxLifecycleStage, PluginSandboxSpec,
    PluginSandboxTransportRecord, PluginSandboxTransportStage, PluginScanRequest,
    ProjectionReceipt, RecoveryRecord, RecoveryRestartIntent, RestartRequest,
    RuntimeAutomationInterpolation, RuntimeAutomationLaneProjection,
    RuntimeAutomationPointProjection, RuntimeAutomationProjection, RuntimeAutomationResolution,
    RuntimeAutomationSnapshot, RuntimeAutomationTargetProjection, RuntimeClipFadeEnvelope,
    RuntimeClipFadeShape, RuntimeClipGainEnvelope, RuntimeClipGainShape,
    RuntimeClipProcessingPipelineSnapshot, RuntimeClipProcessingReadiness,
    RuntimeClipProcessingRegistration, RuntimeClipProcessingSnapshot, RuntimeClipProcessingStage,
    RuntimeClipRenderInputStage, RuntimeClipRenderRequest, RuntimeClipRenderResult,
    RuntimeConfigRequest, RuntimeDeferredServiceClass, RuntimeDeferredServiceDecision,
    RuntimeDeferredServiceReason, RuntimeDeferredServiceReceipt, RuntimeDiagnosticsSnapshot,
    RuntimeEngineBlockResult, RuntimeEngineBlockSnapshot, RuntimeError, RuntimeErrorKind,
    RuntimeEvent, RuntimeEventRecorder, RuntimeEventSink, RuntimeExecutionPhase,
    RuntimeExecutionTopologySummary, RuntimeHostAudioPumpSummary, RuntimeHostAudioStreamState,
    RuntimeHostAudioTransferPolicy, RuntimeHostClockDomain, RuntimeHostClockFallbackState,
    RuntimeHostClockSource, RuntimeHostClockTransitionState, RuntimeHostClockingSummary,
    RuntimeHostHardwareSummary, RuntimeHostIoSummary, RuntimeHostLatencySummary,
    RuntimeHostLifecycleOwnership, RuntimeHostObservationReport, RuntimeHostRestartPolicy,
    RuntimeHostSupervisorReport, RuntimeLifecycleApi, RuntimeMediaAssetRegistration,
    RuntimeMediaAssetSnapshot, RuntimeMediaAssetState, RuntimeMediaPipelineSnapshot,
    RuntimeMeterSourceRole, RuntimeMeterSourceSnapshot, RuntimeMeteringSnapshot,
    RuntimeObservationApi, RuntimeObservationDiagnostics, RuntimeObservationReport,
    RuntimeOfflineFreezeArtifactPreview, RuntimeOfflineFreezeArtifactRequest,
    RuntimeOfflineFreezeArtifactResult, RuntimeOfflinePluginDelegatedExecutionMerge,
    RuntimeOfflinePluginDelegatedExecutionOutcome, RuntimeOfflinePluginDelegatedExecutionReceipt,
    RuntimeOfflinePluginDelegatedExecutionRequest,
    RuntimeOfflinePluginDelegatedExecutionStageReceipt,
    RuntimeOfflinePluginDelegatedExecutionStageRequest,
    RuntimeOfflinePluginDelegatedExecutionStatus,
    RuntimeOfflinePluginDelegatedFreezeArtifactOutput, RuntimeOfflinePluginDelegatedStemOutput,
    RuntimeOfflinePluginExecutionBoundary, RuntimeOfflinePluginExecutionOwner,
    RuntimeOfflinePluginExecutionStageBoundary, RuntimeOfflinePluginOverrideState,
    RuntimeOfflineRenderArtifactKind, RuntimeOfflineRenderArtifactReceipt,
    RuntimeOfflineRenderCheckpointReceipt, RuntimeOfflineRenderCheckpointStage,
    RuntimeOfflineRenderContractPreview, RuntimeOfflineRenderExecutionCancellationReceipt,
    RuntimeOfflineRenderExecutionProgressReceipt, RuntimeOfflineRenderExecutionReceipt,
    RuntimeOfflineRenderExecutionState, RuntimeOfflineRenderManifest,
    RuntimeOfflineRenderProfilingReceipt, RuntimeOfflineRenderPurgeReceipt,
    RuntimeOfflineRenderPurgeRequest, RuntimeOfflineRenderQueueProgressReceipt,
    RuntimeOfflineRenderQueueResult, RuntimeOfflineRenderReportReceipt,
    RuntimeOfflineRenderRequest, RuntimeOfflineRenderResult, RuntimeOfflineRenderSoakReceipt,
    RuntimeOfflineRenderStemPreview, RuntimeOfflineRenderStemResult,
    RuntimeOfflineRenderStemTarget, RuntimeOfflineRenderTargetKind, RuntimePluginChainSnapshot,
    RuntimePluginChainStageSnapshot, RuntimePluginCompensationState,
    RuntimePluginDiscoveredTypeRecord, RuntimePluginDiscoverySnapshot, RuntimePluginDispatchState,
    RuntimePluginExecutionChainSummary, RuntimePluginLifecycleSnapshot,
    RuntimePluginLifecycleState, RuntimePluginRecallHandoffSelection,
    RuntimePluginRecallHandoffSnapshot, RuntimePluginRecallHandoffStage,
    RuntimePluginRecallHandoffStageId, RuntimePluginRecallPayload, RuntimePluginRecallSnapshot,
    RuntimePluginRecallState, RuntimePluginSandboxSnapshot, RuntimePluginScanReceipt,
    RuntimePreworkBacklogClass, RuntimePreworkCacheState, RuntimePreworkForecastMode,
    RuntimePreworkForecastPolicy, RuntimePreworkForecastProfile,
    RuntimePreworkForecastProfileSelection, RuntimePreworkForecastProfileSource,
    RuntimePreworkFreshnessState, RuntimePreworkInvalidationReason, RuntimePreworkRetirementReason,
    RuntimePreworkServicePressure, RuntimePreworkServiceSemanticPolicy, RuntimePreworkServiceState,
    RuntimePreworkWindowTarget, RuntimeProfilingReceipt, RuntimeProjectionApi, RuntimeReadiness,
    RuntimeRecordingCaptureCommitReceipt, RuntimeRecordingCaptureSnapshot,
    RuntimeRecordingCaptureStartRequest, RuntimeRecordingCaptureState, RuntimeSchedulerSnapshot,
    RuntimeSchedulerState, RuntimeSchedulerTopologyIssue, RuntimeSchedulerTopologySummary,
    RuntimeSoakReceipt, RuntimeSupervisionSnapshot, RuntimeSupervisorApi, RuntimeSupervisorReport,
    RuntimeTempoMapInterpolation, RuntimeTempoMapProjection, RuntimeTempoMapSegmentProjection,
    RuntimeTempoMapSegmentSnapshot, RuntimeTempoMapSnapshot, RuntimeTempoSource,
    RuntimeTimelineSnapshot, RuntimeTransportConcurrencySnapshot,
    RuntimeTransportObservationSnapshot, RuntimeTransportTransitionKind,
    RuntimeWarpClipRegistration, RuntimeWarpClipSnapshot, RuntimeWarpMode,
    RuntimeWarpPipelineSnapshot, RuntimeWarpReadiness, RuntimeWatchdogTrigger, SafeModeRequest,
    SandboxHandle, SandboxOperationFailureRecord, SandboxOperationFailureStage, ScanHandle,
    ScheduleProjection, StopReason, SubscriptionHandle, TransportAttachIntent,
    TransportDispatchState, TransportFaultBoundaryMode, TransportFaultPhase, TransportFaultRecord,
    TransportFaultResource, TransportFaultSource, TransportFaultStage, TransportFaultSummary,
    TransportHeartbeatFreshness, TransportProjection, TransportSessionBoundaryMode,
    TransportSessionProvenance, TransportSessionState, TransportSessionSummary,
    WatchdogRestartRecord,
};
pub use runtime::{RuntimeConfig, RuntimeProfile, SignalRuntime};
