//! Embeddable runtime orchestration and typed runtime-host interfaces for
//! Signal.
//!
//! The crate owns the control-plane and observation-plane around executable
//! graph processing: graph projection, transport and parameter application,
//! anticipative prework policy, and supervisor-facing runtime snapshots.

mod interfaces;
mod runtime;

pub use interfaces::{
    ActiveTransportConcurrencySession, BackendPolicyOverride, BlockDispatchRecord,
    BlockDispatchStage, BrokerFailureRecord, BrokerFailureStage, BrokerInvalidationRecord,
    BrokerInvalidationStage, CompletionSlotRecord, CompletionSlotStage, DegradedReason,
    EffectiveRuntimeConfig, GraphContractProjection, GraphNodeBufferContractProjection,
    GraphNodeBusEndpointProjection, GraphNodeContractProjection, GraphNodeProjection,
    GraphNodeTopologyProjection, GraphProjection, HandshakeRequest, HandshakeResponse,
    HeartbeatCycleRecord, HeartbeatCycleStage, LeaseRolloverRecord, LingeringCleanupMode,
    LingeringCleanupPlan, LingeringCleanupQueueReceipt, LingeringCleanupTrigger, LoopRegion,
    ParameterBatch, ParameterEvent, PluginBackedNodeBinding, PluginBackedNodeBindingProjection,
    PluginFaultKind, PluginFaultRecord, PluginNodeRender, PluginNodeRenderBatch,
    PluginSandboxInstanceFaultRecord, PluginSandboxInstanceStateRecord,
    PluginSandboxLifecycleRecord, PluginSandboxLifecycleStage, PluginSandboxSpec,
    PluginSandboxTransportRecord, PluginSandboxTransportStage, PluginScanRequest,
    ProjectionReceipt, RecoveryRecord, RecoveryRestartIntent, RestartRequest,
    RuntimeAcceptanceReceipt, RuntimeAdvancedHardwareActionClass,
    RuntimeAdvancedHardwareCapabilitySummary, RuntimeAdvancedHardwareDeviceDescriptor,
    RuntimeAdvancedHardwareGraphState, RuntimeAdvancedHardwareSnapshot,
    RuntimeAutomationInterpolation, RuntimeAutomationLaneProjection,
    RuntimeAutomationPointProjection, RuntimeAutomationProjection, RuntimeAutomationResolution,
    RuntimeAutomationSnapshot, RuntimeAutomationTargetProjection, RuntimeAuxiliaryPathKind,
    RuntimeAuxiliaryPathSummary, RuntimeBlockDeadlinePressure, RuntimeBusConnectionAttachmentClass,
    RuntimeBusConnectionFallbackOutcome, RuntimeBusConnectionSummary, RuntimeBusIntent,
    RuntimeBusRole, RuntimeCanonicalChannelLayout, RuntimeChannelRole, RuntimeClipFadeEnvelope,
    RuntimeClipFadeShape, RuntimeClipGainEnvelope, RuntimeClipGainShape,
    RuntimeClipProcessingPipelineSnapshot, RuntimeClipProcessingReadiness,
    RuntimeClipProcessingRegistration, RuntimeClipProcessingSnapshot, RuntimeClipProcessingStage,
    RuntimeClipRenderInputStage, RuntimeClipRenderRequest, RuntimeClipRenderResult,
    RuntimeConfigRequest, RuntimeControlSurfaceCapabilitySummary,
    RuntimeControlSurfaceDeviceDescriptor, RuntimeControlSurfaceFeedbackReadiness,
    RuntimeControlSurfaceGraphState, RuntimeControlSurfaceMappingPosture,
    RuntimeControlSurfaceSnapshot, RuntimeControlSurfaceTransportPosture,
    RuntimeControllerExpressionMidi2Posture, RuntimeControllerExpressionMpePosture,
    RuntimeDeferredServiceBackpressureSource, RuntimeDeferredServiceCancellationCause,
    RuntimeDeferredServiceClass, RuntimeDeferredServiceDecision,
    RuntimeDeferredServicePriorityBand, RuntimeDeferredServiceReason,
    RuntimeDeferredServiceReceipt, RuntimeDeviceFaultBoundaryState, RuntimeDeviceRestartState,
    RuntimeDeviceSupervisionSnapshot, RuntimeDeviceSupervisionState, RuntimeDiagnosticsSnapshot,
    RuntimeEngineBlockResult, RuntimeEngineBlockSnapshot, RuntimeError, RuntimeErrorKind,
    RuntimeEvent, RuntimeEventRecorder, RuntimeEventSink, RuntimeExecutionPhase,
    RuntimeExecutionTopologySummary, RuntimeExternalIoDeviceChangeState,
    RuntimeExternalIoHealthState, RuntimeExternalIoLoopbackState, RuntimeExternalIoMonitoringState,
    RuntimeExternalIoMonitoringTapPoint, RuntimeExternalIoPrimaryRole, RuntimeExternalIoSnapshot,
    RuntimeExternalMidiDeviceDescriptor, RuntimeExternalMidiDeviceLifecycleState,
    RuntimeExternalMidiDiscoveryState, RuntimeExternalMidiEndpointCapabilitySummary,
    RuntimeExternalMidiEndpointDescriptor, RuntimeExternalMidiEndpointDirection,
    RuntimeExternalMidiEndpointGraphSnapshot, RuntimeExternalMidiEndpointLifecycleState,
    RuntimeExternalMidiGraphState, RuntimeExternalMidiRouteState, RuntimeFaultCause,
    RuntimeFaultContributionReceipt, RuntimeFaultDiagnosticAuthority, RuntimeFaultDiagnosticFamily,
    RuntimeFaultDiagnosticReceipt, RuntimeFaultStatusSnapshot,
    RuntimeGuardedFeedbackChannelPosture, RuntimeHostAudioPumpSummary, RuntimeHostAudioStreamState,
    RuntimeHostAudioTransferPolicy, RuntimeHostClockDiscontinuityState, RuntimeHostClockDomain,
    RuntimeHostClockDriftState, RuntimeHostClockFallbackState, RuntimeHostClockSource,
    RuntimeHostClockTransitionState, RuntimeHostClockingSummary, RuntimeHostDuplexMismatchState,
    RuntimeHostEndpointTopology, RuntimeHostHardwareSummary, RuntimeHostIoSummary,
    RuntimeHostLatencySummary, RuntimeHostLifecycleOwnership, RuntimeHostObservationReport,
    RuntimeHostRestartPolicy, RuntimeHostSupervisorReport, RuntimeInterruptionClass,
    RuntimeInterruptionSummary, RuntimeJackClientRole, RuntimeJackCoordinationSnapshot,
    RuntimeJackGraphCoordinationState, RuntimeJackGuardedCoordinationState,
    RuntimeJackTransportPosture, RuntimeLifecycleApi, RuntimeLinuxAudioBackendClockingParityBand,
    RuntimeLinuxAudioBackendDuplexParityState, RuntimeLinuxAudioBackendEndpointTopologyParityState,
    RuntimeLinuxAudioBackendIdentity, RuntimeLinuxAudioBackendPortabilityBand,
    RuntimeLinuxBackendDeviceClaimPosture, RuntimeLinuxBackendOwnershipFallbackState,
    RuntimeLinuxBackendSessionLifecycleState, RuntimeLinuxBackendSessionOwnership,
    RuntimeLinuxBackendSessionRole, RuntimeLinuxBackendSessionSnapshot,
    RuntimeMarkerAnalysisClipSnapshot, RuntimeMarkerAnalysisInvalidationState,
    RuntimeMarkerAnalysisReadiness, RuntimeMarkerAnalysisSnapshot,
    RuntimeMediaAnalysisDescriptorState, RuntimeMediaAnalysisFamilyState,
    RuntimeMediaAssetRegistration, RuntimeMediaAssetSnapshot, RuntimeMediaAssetState,
    RuntimeMediaCharacterDescriptor, RuntimeMediaIndexingState, RuntimeMediaLibraryAssetDescriptor,
    RuntimeMediaLibraryServiceSnapshot, RuntimeMediaLoudnessDescriptor,
    RuntimeMediaPipelineSnapshot, RuntimeMediaPreviewState, RuntimeMediaServiceSnapshot,
    RuntimeMeterSourceRole, RuntimeMeterSourceSnapshot, RuntimeMeteringSnapshot,
    RuntimeMultichannelIoSummary, RuntimeMultichannelLayoutSummary, RuntimeObservationApi,
    RuntimeObservationDiagnostics, RuntimeObservationReport, RuntimeOfflineFreezeArtifactPreview,
    RuntimeOfflineFreezeArtifactRequest, RuntimeOfflineFreezeArtifactResult,
    RuntimeOfflinePluginDelegatedExecutionMerge, RuntimeOfflinePluginDelegatedExecutionOutcome,
    RuntimeOfflinePluginDelegatedExecutionReceipt, RuntimeOfflinePluginDelegatedExecutionRequest,
    RuntimeOfflinePluginDelegatedExecutionStageReceipt,
    RuntimeOfflinePluginDelegatedExecutionStageRequest,
    RuntimeOfflinePluginDelegatedExecutionStatus,
    RuntimeOfflinePluginDelegatedFreezeArtifactOutput, RuntimeOfflinePluginDelegatedStemOutput,
    RuntimeOfflinePluginExecutionBoundary, RuntimeOfflinePluginExecutionOwner,
    RuntimeOfflinePluginExecutionStageBoundary, RuntimeOfflinePluginOverrideState,
    RuntimeOfflineRenderArtifactKind, RuntimeOfflineRenderArtifactReceipt,
    RuntimeOfflineRenderCheckpointReceipt, RuntimeOfflineRenderCheckpointStage,
    RuntimeOfflineRenderComplexIoStageSummary, RuntimeOfflineRenderContractPreview,
    RuntimeOfflineRenderExecutionCancellationReceipt, RuntimeOfflineRenderExecutionProgressReceipt,
    RuntimeOfflineRenderExecutionReceipt, RuntimeOfflineRenderExecutionState,
    RuntimeOfflineRenderManifest, RuntimeOfflineRenderProfilingReceipt,
    RuntimeOfflineRenderPurgeReceipt, RuntimeOfflineRenderPurgeRequest,
    RuntimeOfflineRenderQueueProgressReceipt, RuntimeOfflineRenderQueueResult,
    RuntimeOfflineRenderReportReceipt, RuntimeOfflineRenderRequest, RuntimeOfflineRenderResult,
    RuntimeOfflineRenderSoakReceipt, RuntimeOfflineRenderSpatialStageSummary,
    RuntimeOfflineRenderStemPreview, RuntimeOfflineRenderStemResult,
    RuntimeOfflineRenderStemTarget, RuntimeOfflineRenderTargetKind, RuntimePerformanceSnapshot,
    RuntimePerformanceTraceReceipt, RuntimePluginAraContextSnapshot,
    RuntimePluginAraDocumentContext, RuntimePluginAraRegionContext, RuntimePluginAraSourceContext,
    RuntimePluginBusCapableFxClass, RuntimePluginCapabilityCoverageSummary,
    RuntimePluginChainSnapshot, RuntimePluginChainStageSnapshot, RuntimePluginCompensationState,
    RuntimePluginComplexIoSummary, RuntimePluginDiscoveredTypeRecord,
    RuntimePluginDiscoverySnapshot, RuntimePluginDispatchState, RuntimePluginEventSnapshot,
    RuntimePluginExecutionChainSummary, RuntimePluginFormatCoverageRecord,
    RuntimePluginFormatParityRecord, RuntimePluginFormatPlatformCoverageRecord,
    RuntimePluginHostPlatform, RuntimePluginInterchangeSnapshot, RuntimePluginIsolationOutcome,
    RuntimePluginLifecycleSnapshot, RuntimePluginLifecycleState, RuntimePluginParityBand,
    RuntimePluginPlacementPolicy, RuntimePluginPlacementRule, RuntimePluginPlacementRuleMatcher,
    RuntimePluginPortClass, RuntimePluginPresetDescriptor, RuntimePluginPresetOrigin,
    RuntimePluginRecallHandoffSelection, RuntimePluginRecallHandoffSnapshot,
    RuntimePluginRecallHandoffStage, RuntimePluginRecallHandoffStageId, RuntimePluginRecallPayload,
    RuntimePluginRecallPortabilityClass, RuntimePluginRecallSnapshot, RuntimePluginRecallState,
    RuntimePluginSandboxSnapshot, RuntimePluginScanReceipt, RuntimePluginTopologyAttachmentPolicy,
    RuntimePluginTopologyFallbackOutcome, RuntimePreviewTransformClipSnapshot,
    RuntimePreviewTransformDegradedState, RuntimePreviewTransformFallbackKind,
    RuntimePreviewTransformReadiness, RuntimePreviewTransformServiceClass,
    RuntimePreviewTransformServiceSnapshot, RuntimePreworkBacklogClass, RuntimePreworkCacheState,
    RuntimePreworkForecastMode, RuntimePreworkForecastPolicy, RuntimePreworkForecastProfile,
    RuntimePreworkForecastProfileSelection, RuntimePreworkForecastProfileSource,
    RuntimePreworkFreshnessState, RuntimePreworkInvalidationReason, RuntimePreworkRetirementReason,
    RuntimePreworkServicePressure, RuntimePreworkServiceSemanticPolicy, RuntimePreworkServiceState,
    RuntimePreworkWindowTarget, RuntimeProfilingReceipt, RuntimeProjectionApi, RuntimeReadiness,
    RuntimeRecordingCaptureCheckpointClass, RuntimeRecordingCaptureCheckpointSnapshot,
    RuntimeRecordingCaptureCommitReceipt, RuntimeRecordingCaptureKind,
    RuntimeRecordingCaptureSnapshot, RuntimeRecordingCaptureStartRequest,
    RuntimeRecordingCaptureState, RuntimeRecoveryState, RuntimeSchedulerSnapshot,
    RuntimeSchedulerState, RuntimeSchedulerTopologyIssue, RuntimeSchedulerTopologySummary,
    RuntimeScriptingSafeDevicePolicyPosture, RuntimeSecondaryInputAttachmentPolicy,
    RuntimeSecondaryInputContractProjection, RuntimeSecondaryInputFallbackOutcome,
    RuntimeSecondaryInputRouteSummary, RuntimeSecondaryInputSourceKind,
    RuntimeSecondaryInputTargetKind, RuntimeSoakReceipt, RuntimeSpatialActivationPolicy,
    RuntimeSpatialAdapterClass, RuntimeSpatialBedClass, RuntimeSpatialControlFamily,
    RuntimeSpatialExecutionMode, RuntimeSpatialExecutionSummary,
    RuntimeSpatialExpandedFallbackOutcome, RuntimeSpatialFallbackOutcome, RuntimeSpatialMixPolicy,
    RuntimeSpatialObjectRole, RuntimeSpatialRenderScope, RuntimeSpatialTargetEnvironment,
    RuntimeStretchClipSnapshot, RuntimeStretchEngineClass, RuntimeStretchEngineSnapshot,
    RuntimeStretchFallbackKind, RuntimeStretchReadiness, RuntimeSupervisionSnapshot,
    RuntimeSupervisorApi, RuntimeSupervisorReport, RuntimeTempoAssistHintSource,
    RuntimeTempoAssistPosture, RuntimeTempoMapInterpolation, RuntimeTempoMapProjection,
    RuntimeTempoMapSegmentProjection, RuntimeTempoMapSegmentSnapshot, RuntimeTempoMapSnapshot,
    RuntimeTempoSource, RuntimeTimelineSnapshot, RuntimeTransformArtifactClipSnapshot,
    RuntimeTransformArtifactInvalidationState, RuntimeTransformArtifactReadiness,
    RuntimeTransformArtifactReuseState, RuntimeTransformArtifactSnapshot,
    RuntimeTransportConcurrencySnapshot, RuntimeTransportObservationSnapshot,
    RuntimeTransportTransitionKind, RuntimeWarpClipRegistration, RuntimeWarpClipSnapshot,
    RuntimeWarpMode, RuntimeWarpPipelineSnapshot, RuntimeWarpReadiness, RuntimeWatchdogTrigger,
    SafeModeRequest, SandboxHandle, SandboxOperationFailureRecord, SandboxOperationFailureStage,
    ScanHandle, ScheduleProjection, StopReason, SubscriptionHandle, TransportAttachIntent,
    TransportDispatchState, TransportFaultBoundaryMode, TransportFaultPhase, TransportFaultRecord,
    TransportFaultResource, TransportFaultSource, TransportFaultStage, TransportFaultSummary,
    TransportHeartbeatFreshness, TransportProjection, TransportSessionBoundaryMode,
    TransportSessionProvenance, TransportSessionState, TransportSessionSummary,
    WatchdogRestartRecord,
};
pub use runtime::{RuntimeConfig, RuntimeProfile, SignalRuntime};
