use super::*;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RuntimePluginChainStageSnapshot {
    pub node_id: String,
    pub stage_index: usize,
    pub sandbox_id: Option<String>,
    pub sandbox_group_key: Option<String>,
    pub track_lane_id: Option<String>,
    pub bus_group_id: Option<String>,
    pub console_group_id: Option<String>,
    pub send_return_id: Option<String>,
    pub placement_outcome: RuntimePluginIsolationOutcome,
    pub placement_rule_id: Option<String>,
    pub shared_boundary_member_count: usize,
    pub continuity_class: RuntimeInterruptionClass,
    pub rebindable: bool,
    pub io_layout: RuntimeMultichannelIoSummary,
    pub complex_io_summary: RuntimePluginComplexIoSummary,
    pub secondary_input: Option<RuntimeSecondaryInputRouteSummary>,
    pub spatial_execution: Option<RuntimeSpatialExecutionSummary>,
    pub lifecycle_state: Option<RuntimePluginLifecycleState>,
    pub lifecycle_stage: Option<PluginSandboxLifecycleStage>,
    pub transport_stage: Option<PluginSandboxTransportStage>,
    pub recall_state: RuntimePluginRecallState,
    pub recall: RuntimePluginRecallSnapshot,
    pub compensation_state: RuntimePluginCompensationState,
    pub planned_latency_samples: u32,
    pub realized_latency_samples: Option<u32>,
    pub tail_samples: Option<u32>,
    pub bypassed: bool,
    pub active_transport: bool,
    pub degraded_reasons: Vec<String>,
    pub summary: String,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RuntimePluginExecutionChainSummary {
    pub chain_id: String,
    pub track_lane_id: Option<String>,
    pub bus_group_id: Option<String>,
    pub console_group_id: Option<String>,
    pub send_return_id: Option<String>,
    pub stage_count: usize,
    pub shared_sandbox_stage_count: usize,
    pub isolated_sandbox_stage_count: usize,
    pub in_process_stage_count: usize,
    pub pending_render_stage_count: usize,
    pub settling_stage_count: usize,
    pub compensated_stage_count: usize,
    pub degraded_stage_count: usize,
    pub bypassed_stage_count: usize,
    pub missing_binding_stage_count: usize,
    pub rebindable_stage_count: usize,
    pub terminal_stage_count: usize,
    pub total_planned_latency_samples: u32,
    pub total_realized_latency_samples: u32,
    pub total_tail_samples: u32,
    pub stages: Vec<RuntimePluginChainStageSnapshot>,
    pub summary: String,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RuntimePluginChainSnapshot {
    pub chain_count: usize,
    pub stage_count: usize,
    pub shared_sandbox_stage_count: usize,
    pub isolated_sandbox_stage_count: usize,
    pub in_process_stage_count: usize,
    pub pending_render_stage_count: usize,
    pub settling_stage_count: usize,
    pub compensated_stage_count: usize,
    pub degraded_stage_count: usize,
    pub bypassed_stage_count: usize,
    pub missing_binding_stage_count: usize,
    pub rebindable_stage_count: usize,
    pub terminal_stage_count: usize,
    pub total_planned_latency_samples: u32,
    pub total_realized_latency_samples: u32,
    pub total_tail_samples: u32,
    pub chains: Vec<RuntimePluginExecutionChainSummary>,
    pub summary: String,
}
