use super::*;

pub(crate) fn render_runtime_supervisor_report_event_history_json(
    report: &RuntimeSupervisorReport,
) -> String {
    let last_fault = report.observation.observation.plugin_faults.last();
    let last_plugin_instance_state = report.observation.observation.last_plugin_instance_state();
    format!(
        concat!(
            "\"event_stream\":{},",
            "\"supervision_updates\":{},",
            "\"plugin_faults\":{},",
            "\"plugin_instance_state_events\":{},",
            "\"recovery_events\":{},",
            "\"lifecycle_events\":{},",
            "\"transport_events\":{},",
            "\"heartbeat_events\":{},",
            "\"block_dispatch_events\":{},",
            "\"lease_rollover_events\":{},",
            "\"invalidation_events\":{},",
            "\"completion_slot_events\":{},",
            "\"transport_fault_events\":{},",
            "\"broker_failure_events\":{},",
            "\"sandbox_operation_failure_events\":{},",
            "\"last_watchdog\":{},",
            "\"last_fault\":{},",
            "\"last_plugin_instance_state\":{},",
            "\"last_recovery\":{},",
            "\"last_lifecycle\":{},",
            "\"last_transport\":{},",
            "\"last_heartbeat\":{},",
            "\"last_dispatch\":{},",
            "\"last_rollover\":{},",
            "\"last_invalidation\":{},",
            "\"last_completion_slot\":{},",
            "\"last_transport_fault\":{},",
            "\"last_broker_failure\":{},",
            "\"last_sandbox_operation_failure\":{},",
            "\"recovery_sequence\":{},",
            "\"lifecycle_sequence\":{},",
            "\"transport_sequence\":{},",
            "\"heartbeat_sequence\":{},",
            "\"block_dispatch_sequence\":{},",
            "\"lease_rollover_sequence\":{},",
            "\"invalidation_sequence\":{},",
            "\"completion_slot_sequence\":{},",
            "\"transport_fault_sequence\":{},",
            "\"broker_failure_sequence\":{},",
            "\"sandbox_operation_failure_sequence\":{},",
            "\"plugin_instance_state_sequence\":{}"
        ),
        report.event_count(),
        report.supervision_update_count(),
        report.plugin_fault_count(),
        report.plugin_instance_state_event_count(),
        report.recovery_event_count(),
        report.lifecycle_event_count(),
        report.transport_event_count(),
        report.heartbeat_event_count(),
        report.block_dispatch_event_count(),
        report.lease_rollover_event_count(),
        report.invalidation_event_count(),
        report.completion_slot_event_count(),
        report.transport_fault_event_count(),
        report.broker_failure_event_count(),
        report.sandbox_operation_failure_event_count(),
        json_option_string(
            report
                .last_watchdog_trigger()
                .map(|trigger| format!("{trigger:?}"))
                .as_deref(),
        ),
        json_option_string(
            last_fault
                .map(|fault| format!("{}:{:?}", fault.sandbox_id, fault.kind))
                .as_deref(),
        ),
        json_plugin_instance_state_record(last_plugin_instance_state),
        json_recovery_record(report.observation.observation.last_recovery_event()),
        json_lifecycle_record(report.observation.observation.last_lifecycle_event()),
        json_transport_record(report.observation.observation.last_transport_event()),
        json_heartbeat_record(report.observation.observation.last_heartbeat_event()),
        json_block_dispatch_record(report.observation.observation.last_block_dispatch_event()),
        json_lease_rollover_record(report.observation.observation.last_lease_rollover_event()),
        json_broker_invalidation_record(report.observation.observation.last_invalidation_event()),
        json_completion_slot_record(report.observation.observation.last_completion_slot_event()),
        json_transport_fault_record(report.observation.observation.last_transport_fault_event()),
        json_broker_failure_record(report.observation.observation.last_broker_failure_event()),
        json_sandbox_operation_failure_record(
            report
                .observation
                .observation
                .last_sandbox_operation_failure_event(),
        ),
        json_recovery_record_vec(&report.observation.observation.recovery_events),
        json_lifecycle_record_vec(&report.observation.observation.lifecycle_events),
        json_transport_record_vec(&report.observation.observation.transport_events),
        json_heartbeat_record_vec(&report.observation.observation.heartbeat_events),
        json_block_dispatch_record_vec(&report.observation.observation.block_dispatch_events),
        json_lease_rollover_record_vec(&report.observation.observation.lease_rollover_events),
        json_broker_invalidation_record_vec(&report.observation.observation.invalidation_events),
        json_completion_slot_record_vec(&report.observation.observation.completion_slot_events),
        json_transport_fault_record_vec(&report.observation.observation.transport_fault_events),
        json_broker_failure_record_vec(&report.observation.observation.broker_failure_events),
        json_sandbox_operation_failure_record_vec(
            &report
                .observation
                .observation
                .sandbox_operation_failure_events,
        ),
        json_plugin_instance_state_record_vec(
            &report.observation.observation.plugin_instance_states
        ),
    )
}
