use super::*;

pub(crate) fn render_runtime_supervisor_report_core_json(
    report: &RuntimeSupervisorReport,
    deferred_service: &str,
    automation: &str,
    plugin_events: &str,
) -> String {
    let timeline = &report
        .observation
        .timeline_snapshot
        .block_sequence_continuity;
    format!(
        concat!(
            "\"readiness\":{},",
            "\"sample_rate\":{},",
            "\"block_size\":{},",
            "\"control\":{},",
            "\"xruns\":{},",
            "\"active_sandboxes\":{},",
            "\"safe_mode\":{},",
            "\"next_block_sequence\":{},",
            "\"sequence_segments\":{},",
            "\"sequence_segment_epochs\":{},",
            "\"sequence_first_block\":{},",
            "\"sequence_last_block\":{},",
            "\"sequence_gaps\":{},",
            "\"sequence_lease_rollovers\":{},",
            "\"transport_epoch\":{},",
            "\"transport_transition\":{},",
            "\"transport_transition_epoch\":{},",
            "\"transport_transition_block\":{},",
            "\"transport_playing\":{},",
            "\"transport_tempo_bpm\":{},",
            "\"transport_timeline_position_samples\":{},",
            "\"transport_loop_start_samples\":{},",
            "\"transport_loop_end_samples\":{},",
            "\"transport_last_block_start_samples\":{},",
            "\"transport_last_block_end_samples\":{},",
            "\"transport_loop_wrap_count\":{},",
            "\"engine_block_snapshot\":{},",
            "\"scheduler_snapshot\":{},",
            "\"scheduler_summary\":{},",
            "\"block_summary\":{},",
            "\"fault_status\":{},",
            "\"fault_diagnostic_receipt\":{},",
            "\"interruption_summary\":{},",
            "\"device_supervision_snapshot\":{},",
            "\"external_io_snapshot\":{},",
            "\"linux_backend_session_snapshot\":{},",
            "\"pipewire_alsa_parity_snapshot\":{},",
            "\"jack_coordination_snapshot\":{},",
            "\"external_midi_snapshot\":{},",
            "\"control_surface_snapshot\":{},",
            "\"advanced_hardware_snapshot\":{},",
            "\"degradation_summary\":{},",
            "\"tempo_map_snapshot\":{},",
            "\"warp_pipeline_snapshot\":{},",
            "\"clip_processing_pipeline_snapshot\":{},",
            "\"stretch_engine_snapshot\":{},",
            "\"marker_analysis_snapshot\":{},",
            "\"transform_artifact_snapshot\":{},",
            "\"preview_transform_snapshot\":{},",
            "\"recording_capture_snapshot\":{},",
            "\"media_pipeline_snapshot\":{},",
            "\"media_service_snapshot\":{},",
            "\"media_library_snapshot\":{},",
            "\"offline_render_session_snapshot\":{},",
            "\"plugin_discovery_snapshot\":{},",
            "\"plugin_lifecycle_snapshot\":{},",
            "\"lv2_extension_snapshot\":{},",
            "\"plugin_pin_matrix_snapshot\":{},",
            "\"plugin_chain_snapshot\":{},",
            "\"metering_snapshot\":{},",
            "\"execution_topology_summary\":{},",
            "\"transport_concurrency_snapshot\":{},",
            "\"transport_fault_summary\":{},",
            "\"transport_session_summary\":{},",
            "\"last_deferred_service\":{},",
            "\"automation\":{},",
            "\"plugin_events\":{}"
        ),
        json_escape_string(&format!("{:?}", report.observation.readiness)),
        report.observation.effective_config.sample_rate.0,
        report.observation.effective_config.block_size,
        json_runtime_control_snapshot(&report.observation.control_snapshot),
        report.observation.diagnostics_snapshot.xruns,
        report
            .observation
            .diagnostics_snapshot
            .active_plugin_sandboxes,
        report.observation.supervision_snapshot.safe_mode_enabled,
        report.observation.timeline_snapshot.next_block_sequence,
        timeline.segment_count(),
        json_u64_vec(&timeline.segment_epochs()),
        json_option_u64(timeline.first_block_sequence()),
        json_option_u64(timeline.last_block_sequence()),
        timeline.sequence_gaps,
        timeline.lease_rollovers,
        report.observation.timeline_snapshot.transport_epoch,
        json_option_string(
            report
                .observation
                .timeline_snapshot
                .last_transport_transition
                .map(|transition| format!("{transition:?}"))
                .as_deref(),
        ),
        json_option_u64(
            report
                .observation
                .timeline_snapshot
                .last_transport_transition_processing_epoch,
        ),
        json_option_u64(
            report
                .observation
                .timeline_snapshot
                .last_transport_transition_block_sequence,
        ),
        match report.observation.timeline_snapshot.last_transport_playing {
            Some(value) => value.to_string(),
            None => "null".into(),
        },
        json_option_f64(
            report
                .observation
                .timeline_snapshot
                .last_transport_tempo_bpm
        ),
        json_option_i64(
            report
                .observation
                .timeline_snapshot
                .last_transport_timeline_position_samples,
        ),
        json_option_i64(
            report
                .observation
                .timeline_snapshot
                .last_transport_loop_start_samples,
        ),
        json_option_i64(
            report
                .observation
                .timeline_snapshot
                .last_transport_loop_end_samples,
        ),
        json_option_i64(
            report
                .observation
                .timeline_snapshot
                .last_engine_block_start_samples,
        ),
        json_option_i64(
            report
                .observation
                .timeline_snapshot
                .last_engine_block_end_samples,
        ),
        report.observation.timeline_snapshot.loop_wrap_count,
        json_runtime_engine_block_snapshot(&report.observation.engine_block_snapshot),
        json_runtime_scheduler_snapshot(&report.observation.scheduler_snapshot),
        json_runtime_scheduler_export_summary(&report.observation.scheduler_summary),
        json_runtime_block_execution_summary(&report.observation.block_summary),
        json_runtime_fault_status(&report.observation.fault_status),
        json_runtime_fault_diagnostic_receipt(&report.observation.fault_diagnostic_receipt),
        json_runtime_interruption_summary(&report.observation.interruption_summary),
        json_runtime_device_supervision_snapshot(&report.observation.device_supervision_snapshot),
        json_runtime_external_io_snapshot(&report.observation.external_io_snapshot),
        json_runtime_linux_backend_session_snapshot(
            &report.observation.linux_backend_session_snapshot,
        ),
        json_runtime_pipewire_alsa_parity_snapshot(
            &report.observation.pipewire_alsa_parity_snapshot,
        ),
        json_runtime_jack_coordination_snapshot(&report.observation.jack_coordination_snapshot),
        json_runtime_external_midi_snapshot(&report.observation.external_midi_snapshot),
        json_runtime_control_surface_snapshot(&report.observation.control_surface_snapshot),
        json_runtime_advanced_hardware_snapshot(&report.observation.advanced_hardware_snapshot),
        json_runtime_degradation_summary(&report.observation.degradation_summary),
        json_runtime_tempo_map_snapshot(&report.observation.tempo_map_snapshot),
        json_runtime_warp_pipeline_snapshot(&report.observation.warp_pipeline_snapshot),
        json_runtime_clip_processing_pipeline_snapshot(
            &report.observation.clip_processing_pipeline_snapshot,
        ),
        json_runtime_stretch_engine_snapshot(&report.observation.stretch_engine_snapshot),
        json_runtime_marker_analysis_snapshot(&report.observation.marker_analysis_snapshot),
        json_runtime_transform_artifact_snapshot(&report.observation.transform_artifact_snapshot),
        json_runtime_preview_transform_service_snapshot(
            &report.observation.preview_transform_snapshot,
        ),
        json_runtime_recording_capture_snapshot(&report.observation.recording_capture_snapshot),
        json_runtime_media_pipeline_snapshot(&report.observation.media_pipeline_snapshot),
        json_runtime_media_service_snapshot(&report.observation.media_service_snapshot),
        json_runtime_media_library_service_snapshot(&report.observation.media_library_snapshot),
        json_runtime_offline_render_session_snapshot(
            &report.observation.offline_render_session_snapshot,
        ),
        json_runtime_plugin_discovery_snapshot(&report.observation.plugin_discovery_snapshot),
        json_runtime_plugin_lifecycle_snapshot(&report.observation.plugin_lifecycle_snapshot),
        json_runtime_lv2_extension_snapshot(&report.observation.lv2_extension_snapshot),
        json_runtime_plugin_pin_matrix_snapshot(&report.observation.plugin_pin_matrix_snapshot),
        json_runtime_plugin_chain_snapshot(&report.observation.plugin_chain_snapshot),
        json_runtime_metering_snapshot(&report.observation.metering_snapshot),
        json_runtime_execution_topology_summary(&report.observation.execution_topology_summary),
        json_runtime_transport_concurrency_snapshot(
            &report.observation.transport_concurrency_snapshot,
        ),
        json_transport_fault_summary(&report.observation.transport_fault_summary),
        json_transport_session_summary(&report.observation.transport_session_summary),
        deferred_service,
        automation,
        plugin_events,
    )
}
