use super::*;

pub(crate) fn format_runtime_external_io_snapshot_compact(
    snapshot: &RuntimeExternalIoSnapshot,
) -> String {
    format!(
        " external_io={:?}/{:?}/{:?}/{:?}/{:?} linux_backend={:?}/{:?}/{:?}/{:?}/{:?} backend={} device={} stream={:?} endpoint={:?} fallback={} device_losses={} restart_attempts={} restart_failures={}",
        snapshot.health_state,
        snapshot.device_change_state,
        snapshot.primary_role,
        snapshot.monitoring_state,
        snapshot.loopback_state,
        snapshot.linux_backend_identity,
        snapshot.linux_backend_portability,
        snapshot.linux_clocking_parity,
        snapshot.linux_duplex_parity,
        snapshot.linux_endpoint_topology_parity,
        snapshot.backend_name,
        snapshot.active_output_device_id,
        snapshot.stream_state,
        snapshot.endpoint_topology,
        snapshot.fallback_active,
        snapshot.device_loss_count,
        snapshot.restart_attempt_count,
        snapshot.restart_failure_count,
    )
}

pub(crate) fn format_runtime_external_io_snapshot_multiline(
    snapshot: &RuntimeExternalIoSnapshot,
) -> String {
    format!(
        concat!(
            "\nexternal_io_health_state={:?}",
            "\nexternal_io_device_change_state={:?}",
            "\nexternal_io_primary_role={:?}",
            "\nexternal_io_monitoring_state={:?}",
            "\nexternal_io_monitoring_tap_point={:?}",
            "\nexternal_io_loopback_state={:?}",
            "\nexternal_io_linux_backend_identity={:?}",
            "\nexternal_io_linux_backend_portability={:?}",
            "\nexternal_io_linux_clocking_parity={:?}",
            "\nexternal_io_linux_duplex_parity={:?}",
            "\nexternal_io_linux_endpoint_topology_parity={:?}",
            "\nexternal_io_backend_name={}",
            "\nexternal_io_active_output_device_id={}",
            "\nexternal_io_active_output_device_name={}",
            "\nexternal_io_stream_state={:?}",
            "\nexternal_io_clock_domain={:?}",
            "\nexternal_io_fallback_state={:?}",
            "\nexternal_io_transition_state={:?}",
            "\nexternal_io_drift_state={:?}",
            "\nexternal_io_discontinuity_state={:?}",
            "\nexternal_io_duplex_mismatch_state={:?}",
            "\nexternal_io_endpoint_topology={:?}",
            "\nexternal_io_partial_availability={}",
            "\nexternal_io_fallback_active={}",
            "\nexternal_io_runtime_graph_id_matches_pump={}",
            "\nexternal_io_output_latency_samples={}",
            "\nexternal_io_estimated_output_latency_samples={}",
            "\nexternal_io_xrun_count={}",
            "\nexternal_io_callback_overrun_count={}",
            "\nexternal_io_device_loss_count={}",
            "\nexternal_io_restart_attempt_count={}",
            "\nexternal_io_restart_failure_count={}",
            "\nexternal_io_summary={}",
        ),
        snapshot.health_state,
        snapshot.device_change_state,
        snapshot.primary_role,
        snapshot.monitoring_state,
        snapshot.monitoring_tap_point,
        snapshot.loopback_state,
        snapshot.linux_backend_identity,
        snapshot.linux_backend_portability,
        snapshot.linux_clocking_parity,
        snapshot.linux_duplex_parity,
        snapshot.linux_endpoint_topology_parity,
        snapshot.backend_name,
        snapshot.active_output_device_id,
        snapshot.active_output_device_name,
        snapshot.stream_state,
        snapshot.clock_domain,
        snapshot.fallback_state,
        snapshot.transition_state,
        snapshot.drift_state,
        snapshot.discontinuity_state,
        snapshot.duplex_mismatch_state,
        snapshot.endpoint_topology,
        snapshot.partial_availability,
        snapshot.fallback_active,
        snapshot.runtime_graph_id_matches_pump,
        snapshot.output_latency_samples,
        snapshot.estimated_output_latency_samples,
        snapshot.xrun_count,
        snapshot.callback_overrun_count,
        snapshot.device_loss_count,
        snapshot.restart_attempt_count,
        snapshot.restart_failure_count,
        snapshot.summary,
    )
}

pub(crate) fn json_runtime_external_io_snapshot(snapshot: &RuntimeExternalIoSnapshot) -> String {
    format!(
        concat!(
            "{{",
            "\"health_state\":{},",
            "\"device_change_state\":{},",
            "\"primary_role\":{},",
            "\"monitoring_state\":{},",
            "\"monitoring_tap_point\":{},",
            "\"loopback_state\":{},",
            "\"io_layout\":{},",
            "\"linux_backend_identity\":{},",
            "\"linux_backend_portability\":{},",
            "\"linux_clocking_parity\":{},",
            "\"linux_duplex_parity\":{},",
            "\"linux_endpoint_topology_parity\":{},",
            "\"backend_name\":{},",
            "\"active_output_device_id\":{},",
            "\"active_output_device_name\":{},",
            "\"stream_state\":{},",
            "\"clock_source\":{},",
            "\"clock_domain\":{},",
            "\"fallback_state\":{},",
            "\"transition_state\":{},",
            "\"drift_state\":{},",
            "\"discontinuity_state\":{},",
            "\"duplex_mismatch_state\":{},",
            "\"endpoint_topology\":{},",
            "\"partial_availability\":{},",
            "\"fallback_active\":{},",
            "\"runtime_graph_id_matches_pump\":{},",
            "\"output_latency_samples\":{},",
            "\"estimated_output_latency_samples\":{},",
            "\"xrun_count\":{},",
            "\"callback_overrun_count\":{},",
            "\"device_loss_count\":{},",
            "\"restart_attempt_count\":{},",
            "\"restart_failure_count\":{},",
            "\"summary\":{}",
            "}}"
        ),
        json_string(&format!("{:?}", snapshot.health_state)),
        json_string(&format!("{:?}", snapshot.device_change_state)),
        json_string(&format!("{:?}", snapshot.primary_role)),
        json_string(&format!("{:?}", snapshot.monitoring_state)),
        json_string(&format!("{:?}", snapshot.monitoring_tap_point)),
        json_string(&format!("{:?}", snapshot.loopback_state)),
        json_runtime_multichannel_io_summary(&snapshot.io_layout),
        json_string(&format!("{:?}", snapshot.linux_backend_identity)),
        json_string(&format!("{:?}", snapshot.linux_backend_portability)),
        json_string(&format!("{:?}", snapshot.linux_clocking_parity)),
        json_string(&format!("{:?}", snapshot.linux_duplex_parity)),
        json_string(&format!("{:?}", snapshot.linux_endpoint_topology_parity)),
        json_option_string(Some(snapshot.backend_name.as_str())),
        json_option_string(Some(snapshot.active_output_device_id.as_str())),
        json_option_string(Some(snapshot.active_output_device_name.as_str())),
        json_string(&format!("{:?}", snapshot.stream_state)),
        json_string(&format!("{:?}", snapshot.clock_source)),
        json_string(&format!("{:?}", snapshot.clock_domain)),
        json_string(&format!("{:?}", snapshot.fallback_state)),
        json_string(&format!("{:?}", snapshot.transition_state)),
        json_string(&format!("{:?}", snapshot.drift_state)),
        json_string(&format!("{:?}", snapshot.discontinuity_state)),
        json_string(&format!("{:?}", snapshot.duplex_mismatch_state)),
        json_string(&format!("{:?}", snapshot.endpoint_topology)),
        snapshot.partial_availability,
        snapshot.fallback_active,
        snapshot.runtime_graph_id_matches_pump,
        snapshot.output_latency_samples,
        snapshot.estimated_output_latency_samples,
        snapshot.xrun_count,
        snapshot.callback_overrun_count,
        snapshot.device_loss_count,
        snapshot.restart_attempt_count,
        snapshot.restart_failure_count,
        json_option_string(Some(snapshot.summary.as_str())),
    )
}
