[package]
name = "signal-plugin-sandbox"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Out-of-process plugin container shell for Signal."

[dependencies]
signal-ipc = { path = "../signal-ipc" }
signal-plugin = { path = "../signal-plugin" }
signal-plugin-au = { path = "../signal-plugin-au" }
signal-plugin-clap = { path = "../signal-plugin-clap" }
signal-plugin-lv2 = { path = "../signal-plugin-lv2" }
signal-plugin-vst3 = { path = "../signal-plugin-vst3" }
