use super::meter_state_continuity_context::MeterStagePlanContext;
use super::meter_state_continuity_plan_shell::{build_recommendation, plan, stage};
use crate::rhythm_policy::*;

pub fn watch_arm(
    ctx: MeterStagePlanContext,
    retained_beats: usize,
) -> MeterContinuityRecommendation {
    build_recommendation(
        ctx,
        plan(
            MeterContinuityAction::Retain,
            MeterContinuitySource::RecoveryWindow,
            MeterContinuityReason::RecoveryWindowSupport,
            retained_beats,
            retained_beats.saturating_div(2).max(4),
            stage(
                retained_beats.saturating_div(2).max(4),
                MeterContinuityAction::Lock,
                MeterContinuitySource::CurrentMeter,
                MeterContinuityReason::StableEvidence,
                0,
            ),
            stage(
                retained_beats.saturating_add(4),
                MeterContinuityAction::Reacquire,
                MeterContinuitySource::RecoveryWindow,
                MeterContinuityReason::RevalidationDecay,
                1,
            ),
            stage(
                retained_beats.saturating_add(8),
                MeterContinuityAction::Clear,
                MeterContinuitySource::Cleared,
                MeterContinuityReason::InsufficientEvidence,
                2,
            ),
        ),
        plan(
            MeterContinuityAction::Reacquire,
            MeterContinuitySource::RecoveryWindow,
            MeterContinuityReason::RecoveryWindowSupport,
            0,
            2,
            stage(
                2,
                MeterContinuityAction::Lock,
                MeterContinuitySource::CurrentMeter,
                MeterContinuityReason::StableEvidence,
                0,
            ),
            stage(
                4,
                MeterContinuityAction::Reacquire,
                MeterContinuitySource::RecoveryWindow,
                MeterContinuityReason::RevalidationDecay,
                1,
            ),
            stage(
                6,
                MeterContinuityAction::Clear,
                MeterContinuitySource::Cleared,
                MeterContinuityReason::InsufficientEvidence,
                2,
            ),
        ),
    )
}

pub fn clear_arm(ctx: MeterStagePlanContext) -> MeterContinuityRecommendation {
    build_recommendation(
        ctx,
        plan(
            MeterContinuityAction::Clear,
            MeterContinuitySource::Cleared,
            MeterContinuityReason::InsufficientEvidence,
            0,
            0,
            stage(
                0,
                MeterContinuityAction::Clear,
                MeterContinuitySource::Cleared,
                MeterContinuityReason::InsufficientEvidence,
                2,
            ),
            stage(
                0,
                MeterContinuityAction::Clear,
                MeterContinuitySource::Cleared,
                MeterContinuityReason::InsufficientEvidence,
                2,
            ),
            stage(
                0,
                MeterContinuityAction::Clear,
                MeterContinuitySource::Cleared,
                MeterContinuityReason::InsufficientEvidence,
                2,
            ),
        ),
        plan(
            MeterContinuityAction::Clear,
            MeterContinuitySource::Cleared,
            MeterContinuityReason::InsufficientEvidence,
            0,
            0,
            stage(
                0,
                MeterContinuityAction::Clear,
                MeterContinuitySource::Cleared,
                MeterContinuityReason::InsufficientEvidence,
                2,
            ),
            stage(
                0,
                MeterContinuityAction::Clear,
                MeterContinuitySource::Cleared,
                MeterContinuityReason::InsufficientEvidence,
                2,
            ),
            stage(
                0,
                MeterContinuityAction::Clear,
                MeterContinuitySource::Cleared,
                MeterContinuityReason::InsufficientEvidence,
                2,
            ),
        ),
    )
}
