use super::meter_state_continuity_context::MeterStagePlanContext;
use super::meter_state_continuity_plan_shell::{build_recommendation, plan, stage};
use crate::rhythm_policy::*;

pub fn lock_arms(
    ctx: MeterStagePlanContext,
    pickup_like_phase: bool,
    retained_beats: usize,
) -> MeterContinuityRecommendation {
    let _ = retained_beats;
    if pickup_like_phase {
        build_recommendation(
            ctx,
            plan(
                MeterContinuityAction::Lock,
                MeterContinuitySource::CurrentMeter,
                MeterContinuityReason::StableEvidence,
                16,
                16,
                stage(
                    16,
                    MeterContinuityAction::Lock,
                    MeterContinuitySource::CurrentMeter,
                    MeterContinuityReason::StableEvidence,
                    0,
                ),
                stage(
                    24,
                    MeterContinuityAction::Retain,
                    MeterContinuitySource::CurrentMeter,
                    MeterContinuityReason::RevalidationDecay,
                    1,
                ),
                stage(
                    32,
                    MeterContinuityAction::Clear,
                    MeterContinuitySource::Cleared,
                    MeterContinuityReason::InsufficientEvidence,
                    2,
                ),
            ),
            plan(
                MeterContinuityAction::Reacquire,
                MeterContinuitySource::CurrentMeter,
                MeterContinuityReason::PhaseDisplacement,
                0,
                2,
                stage(
                    2,
                    MeterContinuityAction::Lock,
                    MeterContinuitySource::CurrentMeter,
                    MeterContinuityReason::StableEvidence,
                    0,
                ),
                stage(
                    4,
                    MeterContinuityAction::Reacquire,
                    MeterContinuitySource::CurrentMeter,
                    MeterContinuityReason::PhaseDisplacement,
                    1,
                ),
                stage(
                    8,
                    MeterContinuityAction::Clear,
                    MeterContinuitySource::Cleared,
                    MeterContinuityReason::InsufficientEvidence,
                    2,
                ),
            ),
        )
    } else {
        build_recommendation(
            ctx,
            plan(
                MeterContinuityAction::Lock,
                MeterContinuitySource::CurrentMeter,
                MeterContinuityReason::StableEvidence,
                16,
                16,
                stage(
                    16,
                    MeterContinuityAction::Lock,
                    MeterContinuitySource::CurrentMeter,
                    MeterContinuityReason::StableEvidence,
                    0,
                ),
                stage(
                    24,
                    MeterContinuityAction::Retain,
                    MeterContinuitySource::CurrentMeter,
                    MeterContinuityReason::RevalidationDecay,
                    1,
                ),
                stage(
                    32,
                    MeterContinuityAction::Clear,
                    MeterContinuitySource::Cleared,
                    MeterContinuityReason::InsufficientEvidence,
                    2,
                ),
            ),
            plan(
                MeterContinuityAction::Lock,
                MeterContinuitySource::CurrentMeter,
                MeterContinuityReason::StableEvidence,
                16,
                16,
                stage(
                    16,
                    MeterContinuityAction::Lock,
                    MeterContinuitySource::CurrentMeter,
                    MeterContinuityReason::StableEvidence,
                    0,
                ),
                stage(
                    24,
                    MeterContinuityAction::Retain,
                    MeterContinuitySource::CurrentMeter,
                    MeterContinuityReason::RevalidationDecay,
                    1,
                ),
                stage(
                    32,
                    MeterContinuityAction::Clear,
                    MeterContinuitySource::Cleared,
                    MeterContinuityReason::InsufficientEvidence,
                    2,
                ),
            ),
        )
    }
}
