use super::*;

pub(super) fn json_runtime_engine_block_prework(snapshot: &RuntimeEngineBlockSnapshot) -> String {
    format!(
        concat!(
            ",\"prework_cache_enabled\":{}",
            ",\"prework_cache_state\":\"{:?}\"",
            ",\"prework_cache_queue_capacity\":{}",
            ",\"prework_cache_queue_depth\":{}",
            ",\"prework_cache_peak_queue_depth\":{}",
            ",\"prework_pending_target_count\":{}",
            ",\"prework_pending_immediate_target_count\":{}",
            ",\"prework_pending_near_term_target_count\":{}",
            ",\"prework_pending_deferred_target_count\":{}",
            ",\"prework_next_pending_target_block_sequence\":{}",
            ",\"prework_service_state\":\"{:?}\"",
            ",\"prework_service_pressure\":\"{:?}\"",
            ",\"prework_service_semantic_policy\":\"{:?}\"",
            ",\"prework_service_active_plugin_sandboxes\":{}",
            ",\"prework_service_bound_plugin_sandboxes\":{}",
            ",\"prework_service_active_bound_plugin_sandboxes\":{}",
            ",\"prework_service_degraded_bound_plugin_sandboxes\":{}",
            ",\"prework_service_missing_bound_plugin_sandboxes\":{}",
            ",\"prework_service_plugin_gate_active\":{}",
            ",\"prework_service_cycle_count\":{}",
            ",\"prework_service_prepared_targets\":{}",
            ",\"prework_service_pause_count\":{}",
            ",\"prework_service_resume_count\":{}",
            ",\"prework_service_starvation_count\":{}",
            ",\"prework_service_throttle_count\":{}",
            ",\"prework_service_yield_count\":{}",
            ",\"last_prework_service_processing_epoch\":{}",
            ",\"last_prework_service_requested_cycles\":{}",
            ",\"last_prework_service_effective_cycles\":{}",
            ",\"last_prework_service_cycle_count\":{}",
            ",\"last_prework_service_budget_per_cycle\":{}",
            ",\"last_prework_service_effective_budget_per_cycle\":{}",
            ",\"last_prework_service_prepared_targets\":{}",
            ",\"last_prework_serviced_target_block_sequence\":{}",
            ",\"last_prework_serviced_backlog_class\":{}",
            ",\"prework_forecast_requested_mode\":\"{:?}\"",
            ",\"prework_forecast_mode\":\"{:?}\"",
            ",\"prework_forecast_policy_configured\":{}",
            ",\"prework_forecast_profile\":{}",
            ",\"prework_forecast_profile_source\":{}",
            ",\"prework_forecast_profile_target_window_override\":{}",
            ",\"prework_forecast_policy_target_window_blocks\":{}",
            ",\"prework_cache_freshness_state\":\"{:?}\"",
            ",\"prework_cache_block_freshness_window\":{}",
            ",\"prework_cache_remaining_valid_blocks\":{}",
            ",\"prework_cache_admissions\":{}",
            ",\"prework_cache_consumptions\":{}",
            ",\"prework_cache_queued_admissions\":{}",
            ",\"prework_cache_queued_consumptions\":{}",
            ",\"prework_cache_hits\":{}",
            ",\"prework_cache_misses\":{}",
            ",\"prework_cache_invalidation_count\":{}",
            ",\"prework_cache_retirement_count\":{}",
            ",\"prework_cache_unconsumed_retirement_count\":{}",
            ",\"prework_cache_consumed_retirement_count\":{}",
            ",\"last_prework_cache_hit\":{}",
            ",\"last_prework_invalidation_reason\":{}",
            ",\"last_prework_retirement_reason\":{}",
            ",\"last_prework_retired_unconsumed\":{}",
            ",\"prework_cache_valid_until_processing_epoch\":{}",
            ",\"prework_cache_valid_until_block_sequence\":{}",
            ",\"last_prework_source_processing_epoch\":{}",
            ",\"last_prework_source_block_sequence\":{}",
            ",\"last_prework_admission_processing_epoch\":{}",
            ",\"last_prework_admission_block_sequence\":{}",
            ",\"last_prework_admitted_from_block_sequence\":{}",
            ",\"last_prework_consumption_processing_epoch\":{}",
            ",\"last_prework_consumption_block_sequence\":{}",
            ",\"last_prework_consumed_from_block_sequence\":{}",
            ",\"last_prework_retirement_processing_epoch\":{}",
            ",\"last_prework_retirement_block_sequence\":{}"
        ),
        snapshot.prework_cache_enabled,
        snapshot.prework_cache_state,
        snapshot.prework_cache_queue_capacity,
        snapshot.prework_cache_queue_depth,
        snapshot.prework_cache_peak_queue_depth,
        snapshot.prework_pending_target_count,
        snapshot.prework_pending_immediate_target_count,
        snapshot.prework_pending_near_term_target_count,
        snapshot.prework_pending_deferred_target_count,
        json_option_u64(snapshot.prework_next_pending_target_block_sequence),
        snapshot.prework_service_state,
        snapshot.prework_service_pressure,
        snapshot.prework_service_semantic_policy,
        snapshot.prework_service_active_plugin_sandboxes,
        snapshot.prework_service_bound_plugin_sandboxes,
        snapshot.prework_service_active_bound_plugin_sandboxes,
        snapshot.prework_service_degraded_bound_plugin_sandboxes,
        snapshot.prework_service_missing_bound_plugin_sandboxes,
        snapshot.prework_service_plugin_gate_active,
        snapshot.prework_service_cycle_count,
        snapshot.prework_service_prepared_targets,
        snapshot.prework_service_pause_count,
        snapshot.prework_service_resume_count,
        snapshot.prework_service_starvation_count,
        snapshot.prework_service_throttle_count,
        snapshot.prework_service_yield_count,
        json_option_u64(snapshot.last_prework_service_processing_epoch),
        snapshot.last_prework_service_requested_cycles,
        snapshot.last_prework_service_effective_cycles,
        snapshot.last_prework_service_cycle_count,
        match snapshot.last_prework_service_budget_per_cycle {
            Some(value) => value.to_string(),
            None => "null".into(),
        },
        match snapshot.last_prework_service_effective_budget_per_cycle {
            Some(value) => value.to_string(),
            None => "null".into(),
        },
        snapshot.last_prework_service_prepared_targets,
        json_option_u64(snapshot.last_prework_serviced_target_block_sequence),
        json_option_string(
            snapshot
                .last_prework_serviced_backlog_class
                .map(|backlog| format!("{backlog:?}"))
                .as_deref(),
        ),
        snapshot.prework_forecast_requested_mode,
        snapshot.prework_forecast_mode,
        snapshot.prework_forecast_policy_configured,
        json_option_string(
            snapshot
                .prework_forecast_profile
                .map(|profile| format!("{profile:?}"))
                .as_deref(),
        ),
        json_option_string(
            snapshot
                .prework_forecast_profile_source
                .map(|source| format!("{source:?}"))
                .as_deref(),
        ),
        match snapshot.prework_forecast_profile_target_window_override {
            Some(value) => value.to_string(),
            None => "null".into(),
        },
        match snapshot.prework_forecast_policy_target_window_blocks {
            Some(value) => value.to_string(),
            None => "null".into(),
        },
        snapshot.prework_cache_freshness_state,
        snapshot.prework_cache_block_freshness_window,
        json_option_u64(snapshot.prework_cache_remaining_valid_blocks),
        snapshot.prework_cache_admissions,
        snapshot.prework_cache_consumptions,
        snapshot.prework_cache_queued_admissions,
        snapshot.prework_cache_queued_consumptions,
        snapshot.prework_cache_hits,
        snapshot.prework_cache_misses,
        snapshot.prework_cache_invalidation_count,
        snapshot.prework_cache_retirement_count,
        snapshot.prework_cache_unconsumed_retirement_count,
        snapshot.prework_cache_consumed_retirement_count,
        snapshot.last_prework_cache_hit,
        json_option_string(
            snapshot
                .last_prework_invalidation_reason
                .map(|reason| format!("{reason:?}"))
                .as_deref(),
        ),
        json_option_string(
            snapshot
                .last_prework_retirement_reason
                .map(|reason| format!("{reason:?}"))
                .as_deref(),
        ),
        match snapshot.last_prework_retired_unconsumed {
            Some(value) => value.to_string(),
            None => "null".into(),
        },
        json_option_u64(snapshot.prework_cache_valid_until_processing_epoch),
        json_option_u64(snapshot.prework_cache_valid_until_block_sequence),
        json_option_u64(snapshot.last_prework_source_processing_epoch),
        json_option_u64(snapshot.last_prework_source_block_sequence),
        json_option_u64(snapshot.last_prework_admission_processing_epoch),
        json_option_u64(snapshot.last_prework_admission_block_sequence),
        json_option_u64(snapshot.last_prework_admitted_from_block_sequence),
        json_option_u64(snapshot.last_prework_consumption_processing_epoch),
        json_option_u64(snapshot.last_prework_consumption_block_sequence),
        json_option_u64(snapshot.last_prework_consumed_from_block_sequence),
        json_option_u64(snapshot.last_prework_retirement_processing_epoch),
        json_option_u64(snapshot.last_prework_retirement_block_sequence),
    )
}
