use super::super::super::super::*;

pub(super) fn assert_timeout_topology_dispatch(
    supervisor: &signal_runtime::RuntimeSupervisorReport,
) {
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .last_execution_context
            .as_ref()
            .map(|context| context.projection_epoch),
        Some(2)
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .last_execution_context
            .as_ref()
            .map(|context| context.transport_playing),
        Some(true)
    );
    assert!(
        supervisor
            .observation
            .engine_block_snapshot
            .last_execution_context
            .as_ref()
            .map(|context| context.timeline_position_samples)
            .unwrap_or_default()
            > 0
    );
    assert_eq!(supervisor.observation.engine_block_snapshot.node_count, 4);
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .stateful_node_count,
        4
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .latency_node_count,
        1
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .plugin_backed_node_count,
        1
    );
    assert!(
        supervisor
            .observation
            .engine_block_snapshot
            .anticipative_planning_enabled
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .inline_realtime_node_count,
        0
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .stateful_realtime_node_count,
        3
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .anticipative_eligible_node_count,
        1
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .prework_service_semantic_policy,
        signal_runtime::RuntimePreworkServiceSemanticPolicy::PluginConstrained
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .prework_service_active_plugin_sandboxes,
        1
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .prework_service_bound_plugin_sandboxes,
        1
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .prework_service_active_bound_plugin_sandboxes,
        1
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .prework_service_degraded_bound_plugin_sandboxes,
        0
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .prework_service_missing_bound_plugin_sandboxes,
        0
    );
    assert!(
        !supervisor
            .observation
            .engine_block_snapshot
            .prework_service_plugin_gate_active
    );
    assert!(supervisor
        .observation
        .engine_block_snapshot
        .planned_nodes
        .iter()
        .any(|node| node.node_id == "plugin-insert"
            && node.plugin_sandbox_id.as_deref() == Some("local-default-sandbox")));
    assert_eq!(supervisor.observation.engine_block_snapshot.phase_count, 2);
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .anticipative_phase_count,
        1
    );
    assert_eq!(supervisor.observation.engine_block_snapshot.lane_count, 2);
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .anticipative_lane_count,
        1
    );
    assert_eq!(
        supervisor.observation.engine_block_snapshot.dispatch_count,
        2
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .dispatch_boundary_count,
        1
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .prepared_dispatch_count,
        1
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .realtime_dispatch_count,
        1
    );
    assert_eq!(
        supervisor
            .observation
            .engine_block_snapshot
            .dispatch_handoff_count,
        1
    );
}
