use super::*;

#[test]
fn beat_tracker_calibrates_transition_meter_state_actions_for_meterless_cases() {
    let (_, dropout_heavy) = analyze_preset(RhythmPreset::Dropout120(DropoutVariant::Heavy));
    let (_, accelerating_reset) = analyze_preset(RhythmPreset::BarTransition120(
        BarTransitionVariant::ReentryAcceleratingHarmonyReset,
    ));
    let (_, modulation_extended) = analyze_preset(RhythmPreset::BarTransition120(
        BarTransitionVariant::ModulationDenseFillExtended,
    ));

    assert!(dropout_heavy.meter.is_none());
    assert!(accelerating_reset.meter.is_none());
    assert!(modulation_extended.meter.is_none());

    assert_eq!(
        dropout_heavy.meter_state.action,
        super::MeterStateAction::Hold
    );
    assert_eq!(
        dropout_heavy.meter_state.reason,
        super::MeterStateReason::DestabilizedHold
    );
    assert_eq!(
        dropout_heavy.meter_state.continuity.bar_length.action,
        super::MeterContinuityAction::Retain
    );
    assert_eq!(
        dropout_heavy.meter_state.continuity.downbeat_phase.action,
        super::MeterContinuityAction::Retain
    );
    assert_eq!(
        dropout_heavy.meter_state.continuity.bar_length.source,
        super::MeterContinuitySource::PriorMeter
    );
    assert_eq!(
        dropout_heavy
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .refresh
            .action,
        super::MeterContinuityAction::Retain
    );
    assert_eq!(
        dropout_heavy
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .decay[0]
            .action,
        super::MeterContinuityAction::Reacquire
    );
    assert_eq!(
        dropout_heavy
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .decay[1]
            .action,
        super::MeterContinuityAction::Clear
    );
    assert_eq!(
        accelerating_reset.meter_state.action,
        super::MeterStateAction::Watch
    );
    assert_eq!(
        accelerating_reset.meter_state.reason,
        super::MeterStateReason::RecoveryEmerging
    );
    assert_eq!(
        accelerating_reset.meter_state.continuity.bar_length.action,
        super::MeterContinuityAction::Retain
    );
    assert_eq!(
        accelerating_reset
            .meter_state
            .continuity
            .downbeat_phase
            .action,
        super::MeterContinuityAction::Reacquire
    );
    assert_eq!(
        accelerating_reset.meter_state.continuity.bar_length.source,
        super::MeterContinuitySource::RecoveryWindow
    );
    assert_eq!(
        accelerating_reset
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .refresh
            .action,
        super::MeterContinuityAction::Lock
    );
    assert_eq!(
        accelerating_reset
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .decay[0]
            .action,
        super::MeterContinuityAction::Reacquire
    );
    assert_eq!(
        accelerating_reset
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .decay[1]
            .action,
        super::MeterContinuityAction::Clear
    );
    assert_eq!(
        modulation_extended.meter_state.action,
        super::MeterStateAction::Clear
    );
    assert_eq!(
        modulation_extended.meter_state.reason,
        super::MeterStateReason::MeterCleared
    );
    assert_eq!(
        modulation_extended.meter_state.continuity.bar_length.action,
        super::MeterContinuityAction::Clear
    );
    assert_eq!(
        modulation_extended
            .meter_state
            .continuity
            .downbeat_phase
            .action,
        super::MeterContinuityAction::Clear
    );
    assert_eq!(
        modulation_extended.meter_state.continuity.bar_length.source,
        super::MeterContinuitySource::Cleared
    );
    assert_eq!(
        modulation_extended
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .refresh
            .action,
        super::MeterContinuityAction::Clear
    );
    assert_eq!(
        modulation_extended
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .decay[0]
            .action,
        super::MeterContinuityAction::Clear
    );
    assert_eq!(
        modulation_extended
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .decay[1]
            .action,
        super::MeterContinuityAction::Clear
    );
    assert!(
        dropout_heavy.meter_state.confidence.0
            >= modulation_extended.meter_state.confidence.0 - 0.05
    );
    assert!(
        accelerating_reset.meter_state.confidence.0 > modulation_extended.meter_state.confidence.0
    );
}
