use super::*;

#[test]
fn beat_tracker_calibrates_meter_continuity_provenance_and_expiry_windows() {
    let (_, dropout_heavy) = analyze_preset(RhythmPreset::Dropout120(DropoutVariant::Heavy));
    let (_, dropout_extended) =
        analyze_preset(RhythmPreset::Dropout120(DropoutVariant::ExtendedHeavy));
    let (_, pickup) = analyze_preset(RhythmPreset::BarTransition120(BarTransitionVariant::Pickup));
    let (_, pickup_extended) = analyze_preset(RhythmPreset::BarTransition120(
        BarTransitionVariant::PickupExtended,
    ));
    let (_, sustained_reset) = analyze_preset(RhythmPreset::BarTransition120(
        BarTransitionVariant::ReentryAcceleratingHarmonySustainedReset,
    ));
    let (_, long_sustained_reset) = analyze_preset(RhythmPreset::BarTransition120(
        BarTransitionVariant::ReentryAcceleratingHarmonyLongSustainedReset,
    ));

    assert!(dropout_heavy.meter.is_none());
    assert!(dropout_extended.meter.is_none());
    assert!(pickup.meter.is_some());
    assert!(pickup_extended.meter.is_some());
    assert!(sustained_reset.meter.is_some());
    assert!(long_sustained_reset.meter.is_some());

    assert_eq!(
        dropout_heavy.meter_state.continuity.bar_length.source,
        super::MeterContinuitySource::PriorMeter
    );
    assert_eq!(
        dropout_heavy
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .refresh
            .action,
        super::MeterContinuityAction::Retain
    );
    assert_eq!(
        dropout_heavy
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .decay[0]
            .action,
        super::MeterContinuityAction::Reacquire
    );
    assert_eq!(
        dropout_extended.meter_state.continuity.bar_length.source,
        super::MeterContinuitySource::RecoveryWindow
    );
    assert_eq!(
        dropout_extended
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .refresh
            .action,
        super::MeterContinuityAction::Lock
    );
    assert_eq!(
        dropout_extended
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .decay[0]
            .action,
        super::MeterContinuityAction::Reacquire
    );
    assert!(
        dropout_extended
            .meter_state
            .continuity
            .bar_length
            .trusted_beats
            <= dropout_heavy
                .meter_state
                .continuity
                .bar_length
                .trusted_beats
    );
    assert!(
        dropout_extended
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .decay[1]
            .after_beats
            >= dropout_extended
                .meter_state
                .continuity
                .bar_length
                .trusted_beats
    );
    assert!(
        dropout_extended
            .meter_state
            .continuity
            .downbeat_phase
            .trusted_beats
            <= dropout_heavy
                .meter_state
                .continuity
                .downbeat_phase
                .trusted_beats
    );
    assert_eq!(
        dropout_extended
            .meter_state
            .continuity
            .downbeat_phase
            .source,
        super::MeterContinuitySource::RecoveryWindow
    );

    assert_eq!(
        pickup.meter_state.continuity.bar_length.source,
        super::MeterContinuitySource::CurrentMeter
    );
    assert_eq!(
        pickup_extended.meter_state.continuity.downbeat_phase.source,
        super::MeterContinuitySource::CurrentMeter
    );
    assert_eq!(
        pickup_extended
            .meter_state
            .continuity
            .downbeat_phase
            .lifecycle
            .refresh
            .action,
        super::MeterContinuityAction::Lock
    );
    assert_eq!(
        pickup_extended
            .meter_state
            .continuity
            .downbeat_phase
            .lifecycle
            .decay[0]
            .action,
        super::MeterContinuityAction::Reacquire
    );
    assert_eq!(
        pickup.meter_state.continuity.downbeat_phase.trusted_beats,
        0
    );
    assert_eq!(
        pickup_extended
            .meter_state
            .continuity
            .downbeat_phase
            .trusted_beats,
        0
    );
    assert!(
        pickup_extended
            .meter_state
            .continuity
            .downbeat_phase
            .revalidate_after_beats
            <= pickup
                .meter_state
                .continuity
                .downbeat_phase
                .revalidate_after_beats
    );

    assert_eq!(
        sustained_reset.meter_state.continuity.bar_length.source,
        super::MeterContinuitySource::RecoveryWindow
    );
    assert_eq!(
        sustained_reset
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .refresh
            .action,
        super::MeterContinuityAction::Lock
    );
    assert_eq!(
        sustained_reset
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .decay[0]
            .action,
        super::MeterContinuityAction::Reacquire
    );
    assert_eq!(
        long_sustained_reset
            .meter_state
            .continuity
            .bar_length
            .source,
        super::MeterContinuitySource::RecoveryWindow
    );
    assert!(
        long_sustained_reset
            .meter_state
            .continuity
            .bar_length
            .trusted_beats
            > sustained_reset
                .meter_state
                .continuity
                .bar_length
                .trusted_beats
    );
    assert!(
        long_sustained_reset
            .meter_state
            .continuity
            .bar_length
            .revalidate_after_beats
            >= sustained_reset
                .meter_state
                .continuity
                .bar_length
                .revalidate_after_beats
    );
    assert!(
        long_sustained_reset
            .meter_state
            .continuity
            .bar_length
            .lifecycle
            .decay[1]
            .after_beats
            > sustained_reset
                .meter_state
                .continuity
                .bar_length
                .lifecycle
                .decay[1]
                .after_beats
    );
}
