use super::*;

#[test]
fn tempo_continuity_calibrates_causes_and_unresolved_spans() {
    let integer = super::tempo_state_recommendation(
        synthetic_tempo_interpretation(
            super::TempoRecommendation::SnapInteger,
            super::TempoTrustLevel::Stable,
            super::TempoInterpretationReason::NearIntegerPulse,
            120.0,
            Some(120.0),
            0.86,
            0.08,
            0.22,
            0.82,
        ),
        super::Confidence::new(0.9),
        super::Confidence::new(0.12),
    );
    let core_window = super::tempo_state_recommendation(
        synthetic_tempo_interpretation(
            super::TempoRecommendation::UseCoreWindow,
            super::TempoTrustLevel::Guarded,
            super::TempoInterpretationReason::StableCoreWindow,
            90.0,
            None,
            0.64,
            0.07,
            0.72,
            0.64,
        ),
        super::Confidence::new(0.72),
        super::Confidence::new(0.18),
    );
    let guarded_refined = super::tempo_state_recommendation(
        synthetic_tempo_interpretation(
            super::TempoRecommendation::UseRefined,
            super::TempoTrustLevel::Guarded,
            super::TempoInterpretationReason::StableRefinedPulse,
            117.8,
            None,
            0.61,
            0.09,
            0.32,
            0.62,
        ),
        super::Confidence::new(0.71),
        super::Confidence::new(0.21),
    );
    let deferred = super::tempo_state_recommendation(
        synthetic_tempo_interpretation(
            super::TempoRecommendation::Defer,
            super::TempoTrustLevel::Tentative,
            super::TempoInterpretationReason::UnstableTempo,
            89.9,
            None,
            0.38,
            0.03,
            0.8,
            0.3,
        ),
        super::Confidence::new(0.42),
        super::Confidence::new(0.55),
    );

    assert_eq!(
        integer.continuity.trigger,
        super::TempoContinuityTrigger::StableRevalidation
    );
    assert_eq!(
        integer.continuity.unresolved,
        super::TempoContinuityUnresolvedSpan {
            beats: 0,
            failed_revalidations: 0,
        }
    );
    assert_eq!(
        integer.continuity.causes.primary,
        super::TempoContinuityCause::StableTempoEvidence
    );
    assert_eq!(
        core_window.continuity.trigger,
        super::TempoContinuityTrigger::BoundaryDrift
    );
    assert_eq!(
        core_window.continuity.unresolved,
        super::TempoContinuityUnresolvedSpan {
            beats: 8,
            failed_revalidations: 2,
        }
    );
    assert_eq!(
        core_window.continuity.causes.primary,
        super::TempoContinuityCause::BoundaryDrift
    );
    assert!(core_window
        .continuity
        .causes
        .secondary
        .into_iter()
        .flatten()
        .any(|cause| cause == super::TempoContinuityCause::CoreWindowCarry));
    assert_eq!(
        guarded_refined.continuity.trigger,
        super::TempoContinuityTrigger::AmbiguityCarry
    );
    assert_eq!(
        guarded_refined.continuity.unresolved,
        super::TempoContinuityUnresolvedSpan {
            beats: 4,
            failed_revalidations: 1,
        }
    );
    assert_eq!(
        guarded_refined.continuity.causes.primary,
        super::TempoContinuityCause::TempoAmbiguity
    );
    assert_eq!(
        deferred.continuity.trigger,
        super::TempoContinuityTrigger::EvidenceLoss
    );
    assert_eq!(deferred.continuity.unresolved.beats, 0);
    assert_eq!(
        deferred.continuity.causes.primary,
        super::TempoContinuityCause::TempoAmbiguity
    );
    assert!(deferred
        .continuity
        .causes
        .secondary
        .into_iter()
        .flatten()
        .any(|cause| cause == super::TempoContinuityCause::EvidenceLoss));
}

#[test]
fn tempo_continuity_calibrates_arcs_and_arc_support() {
    let integer = super::tempo_state_recommendation(
        synthetic_tempo_interpretation(
            super::TempoRecommendation::SnapInteger,
            super::TempoTrustLevel::Stable,
            super::TempoInterpretationReason::NearIntegerPulse,
            120.0,
            Some(120.0),
            0.86,
            0.08,
            0.22,
            0.82,
        ),
        super::Confidence::new(0.9),
        super::Confidence::new(0.12),
    );
    let core_window = super::tempo_state_recommendation(
        synthetic_tempo_interpretation(
            super::TempoRecommendation::UseCoreWindow,
            super::TempoTrustLevel::Guarded,
            super::TempoInterpretationReason::StableCoreWindow,
            90.0,
            None,
            0.64,
            0.07,
            0.72,
            0.64,
        ),
        super::Confidence::new(0.72),
        super::Confidence::new(0.18),
    );
    let guarded_refined = super::tempo_state_recommendation(
        synthetic_tempo_interpretation(
            super::TempoRecommendation::UseRefined,
            super::TempoTrustLevel::Guarded,
            super::TempoInterpretationReason::StableRefinedPulse,
            117.8,
            None,
            0.61,
            0.09,
            0.32,
            0.62,
        ),
        super::Confidence::new(0.71),
        super::Confidence::new(0.21),
    );
    let deferred = super::tempo_state_recommendation(
        synthetic_tempo_interpretation(
            super::TempoRecommendation::Defer,
            super::TempoTrustLevel::Tentative,
            super::TempoInterpretationReason::UnstableTempo,
            89.9,
            None,
            0.38,
            0.03,
            0.8,
            0.3,
        ),
        super::Confidence::new(0.42),
        super::Confidence::new(0.55),
    );

    assert_eq!(
        integer.continuity.arc,
        super::TempoContinuityArc::Recovering
    );
    assert_eq!(
        core_window.continuity.arc,
        super::TempoContinuityArc::Stalling
    );
    assert_eq!(
        guarded_refined.continuity.arc,
        super::TempoContinuityArc::Recovering
    );
    assert_eq!(
        deferred.continuity.arc,
        super::TempoContinuityArc::Collapsing
    );
    assert_eq!(
        integer.continuity.arc_rationale,
        super::TempoContinuityArcRationale::RefreshStrength
    );
    assert_eq!(
        integer.continuity.arc_decision.recommendation,
        super::TempoContinuityArcRecommendation::KeepLock
    );
    assert_eq!(
        integer.continuity.arc_decision.action,
        super::TempoContinuityArcAction::LockCurrentTempo
    );
    assert_eq!(
        integer.continuity.arc_decision.severity,
        super::TempoContinuitySeverity::Confirmed
    );
    assert_eq!(
        integer.continuity.arc_decision.fallback_action,
        super::TempoContinuityArcAction::ReacquireCurrentTempo
    );
    assert_eq!(
        integer.continuity.arc_decision.downgrade_rationale,
        super::TempoContinuityArcDowngradeRationale::StabilityWindowEnd
    );
    assert_eq!(
        integer.continuity.arc_decision.downgrade_trend,
        super::TempoContinuityArcDowngradeTrend::Easing
    );
    assert_eq!(
        integer.continuity.arc_decision.downgrade_trend_rationale,
        super::TempoContinuityArcDowngradeTrendRationale::StabilityWindowCarry
    );
    assert_eq!(
        integer.continuity.arc_decision.downgrade_inflection.stage,
        super::TempoContinuityArcDowngradeInflectionStage::NextStage
    );
    assert_eq!(
        integer
            .continuity
            .arc_decision
            .downgrade_inflection
            .competing_stage,
        Some(super::TempoContinuityArcDowngradeInflectionStage::TerminalClear)
    );
    assert_eq!(
        integer
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .primary
            .dominant,
        super::TempoContinuityArcDowngradeStageRationale::StabilityWindow
    );
    assert!(matches!(
        integer
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .competing
            .map(|weights| weights.dominant),
        Some(super::TempoContinuityArcDowngradeStageRationale::EvidenceLoss)
            | Some(super::TempoContinuityArcDowngradeStageRationale::StabilityWindow)
            | None
    ));
    assert!(
        integer
            .continuity
            .arc_decision
            .downgrade_inflection
            .balance
            .competing_weight
            .0
            >= 0.0
    );
    assert!(
        integer
            .continuity
            .arc_decision
            .downgrade_support
            .stability_window_pressure
            .0
            > integer
                .continuity
                .arc_decision
                .downgrade_support
                .failed_revalidation_pressure
                .0
    );
    assert_eq!(
        integer.continuity.arc_decision.provenance,
        super::TempoContinuityProvenance::IntegerSnap
    );
    assert_eq!(
        core_window.continuity.arc_rationale,
        super::TempoContinuityArcRationale::BoundaryDrift
    );
    assert_eq!(
        core_window.continuity.arc_decision.recommendation,
        super::TempoContinuityArcRecommendation::MonitorRecovery
    );
    assert_eq!(
        core_window.continuity.arc_decision.action,
        super::TempoContinuityArcAction::PreferCoreWindowTempo
    );
    assert_eq!(
        core_window.continuity.arc_decision.severity,
        super::TempoContinuitySeverity::Guarded
    );
    assert_eq!(
        core_window.continuity.arc_decision.fallback_action,
        super::TempoContinuityArcAction::PreservePriorTempo
    );
    assert_eq!(
        core_window.continuity.arc_decision.downgrade_rationale,
        super::TempoContinuityArcDowngradeRationale::BoundaryDrift
    );
    assert_eq!(
        core_window.continuity.arc_decision.downgrade_trend,
        super::TempoContinuityArcDowngradeTrend::Rising
    );
    assert_eq!(
        core_window
            .continuity
            .arc_decision
            .downgrade_trend_rationale,
        super::TempoContinuityArcDowngradeTrendRationale::BoundaryEscalation
    );
    assert_eq!(
        core_window
            .continuity
            .arc_decision
            .downgrade_inflection
            .stage,
        super::TempoContinuityArcDowngradeInflectionStage::NextStage
    );
    assert_eq!(
        core_window
            .continuity
            .arc_decision
            .downgrade_inflection
            .competing_stage,
        Some(super::TempoContinuityArcDowngradeInflectionStage::TerminalClear)
    );
    assert_eq!(
        core_window
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .primary
            .dominant,
        super::TempoContinuityArcDowngradeStageRationale::BoundaryDrift
    );
    assert!(matches!(
        core_window
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .competing
            .map(|weights| weights.dominant),
        Some(super::TempoContinuityArcDowngradeStageRationale::EvidenceLoss)
            | Some(super::TempoContinuityArcDowngradeStageRationale::BoundaryDrift)
            | Some(super::TempoContinuityArcDowngradeStageRationale::StabilityWindow)
            | None
    ));
    assert!(
        core_window
            .continuity
            .arc_decision
            .downgrade_inflection
            .balance
            .primary_weight
            .0
            >= core_window
                .continuity
                .arc_decision
                .downgrade_inflection
                .balance
                .competing_weight
                .0
    );
    assert!(
        core_window
            .continuity
            .arc_decision
            .downgrade_support
            .boundary_drift_pressure
            .0
            > core_window
                .continuity
                .arc_decision
                .downgrade_support
                .stability_window_pressure
                .0
    );
    assert_eq!(
        core_window.continuity.arc_decision.provenance,
        super::TempoContinuityProvenance::CoreWindowEstimate
    );
    assert_eq!(
        guarded_refined.continuity.arc_rationale,
        super::TempoContinuityArcRationale::RefreshStrength
    );
    assert_eq!(
        guarded_refined.continuity.arc_decision.recommendation,
        super::TempoContinuityArcRecommendation::MonitorRecovery
    );
    assert_eq!(
        guarded_refined.continuity.arc_decision.action,
        super::TempoContinuityArcAction::ReacquireCurrentTempo
    );
    assert_eq!(
        guarded_refined.continuity.arc_decision.severity,
        super::TempoContinuitySeverity::Fragile
    );
    assert_eq!(
        guarded_refined.continuity.arc_decision.fallback_action,
        super::TempoContinuityArcAction::ClearTempo
    );
    assert_eq!(
        guarded_refined.continuity.arc_decision.downgrade_rationale,
        super::TempoContinuityArcDowngradeRationale::AmbiguityCarry
    );
    assert_eq!(
        guarded_refined.continuity.arc_decision.downgrade_trend,
        super::TempoContinuityArcDowngradeTrend::Easing
    );
    assert_eq!(
        guarded_refined
            .continuity
            .arc_decision
            .downgrade_trend_rationale,
        super::TempoContinuityArcDowngradeTrendRationale::AmbiguityCarry
    );
    assert_eq!(
        guarded_refined
            .continuity
            .arc_decision
            .downgrade_inflection
            .stage,
        super::TempoContinuityArcDowngradeInflectionStage::NextStage
    );
    assert_eq!(
        guarded_refined
            .continuity
            .arc_decision
            .downgrade_inflection
            .competing_stage,
        Some(super::TempoContinuityArcDowngradeInflectionStage::TerminalClear)
    );
    assert_eq!(
        guarded_refined
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .primary
            .dominant,
        super::TempoContinuityArcDowngradeStageRationale::AmbiguityCarry
    );
    assert!(matches!(
        guarded_refined
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .competing
            .map(|weights| weights.dominant),
        Some(super::TempoContinuityArcDowngradeStageRationale::EvidenceLoss)
            | Some(super::TempoContinuityArcDowngradeStageRationale::AmbiguityCarry)
            | Some(super::TempoContinuityArcDowngradeStageRationale::StabilityWindow)
            | None
    ));
    assert!(
        guarded_refined
            .continuity
            .arc_decision
            .downgrade_inflection
            .balance
            .competing_weight
            .0
            >= 0.0
    );
    assert!(
        guarded_refined
            .continuity
            .arc_decision
            .downgrade_support
            .ambiguity_pressure
            .0
            > guarded_refined
                .continuity
                .arc_decision
                .downgrade_support
                .failed_revalidation_pressure
                .0
    );
    assert_eq!(
        guarded_refined.continuity.arc_decision.provenance,
        super::TempoContinuityProvenance::GuardedRefinedEstimate
    );
    assert_eq!(
        deferred.continuity.arc_rationale,
        super::TempoContinuityArcRationale::EvidenceLoss
    );
    assert_eq!(
        deferred.continuity.arc_decision.recommendation,
        super::TempoContinuityArcRecommendation::Clear
    );
    assert_eq!(
        deferred.continuity.arc_decision.action,
        super::TempoContinuityArcAction::ClearTempo
    );
    assert_eq!(
        deferred.continuity.arc_decision.severity,
        super::TempoContinuitySeverity::Cleared
    );
    assert_eq!(
        deferred.continuity.arc_decision.fallback_action,
        super::TempoContinuityArcAction::ClearTempo
    );
    assert_eq!(
        deferred.continuity.arc_decision.downgrade_rationale,
        super::TempoContinuityArcDowngradeRationale::EvidenceLoss
    );
    assert_eq!(
        deferred.continuity.arc_decision.downgrade_trend,
        super::TempoContinuityArcDowngradeTrend::Stable
    );
    assert_eq!(
        deferred.continuity.arc_decision.downgrade_trend_rationale,
        super::TempoContinuityArcDowngradeTrendRationale::FlatCollapse
    );
    assert_eq!(
        deferred.continuity.arc_decision.downgrade_inflection.stage,
        super::TempoContinuityArcDowngradeInflectionStage::FlatWindow
    );
    assert_eq!(
        deferred
            .continuity
            .arc_decision
            .downgrade_inflection
            .competing_stage,
        None
    );
    assert_eq!(
        deferred
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .primary
            .dominant,
        super::TempoContinuityArcDowngradeStageRationale::EvidenceLoss
    );
    assert_eq!(
        deferred
            .continuity
            .arc_decision
            .downgrade_inflection
            .rationale_balance
            .competing,
        None
    );
    assert_eq!(
        deferred
            .continuity
            .arc_decision
            .downgrade_inflection
            .balance
            .unattributed_weight,
        super::Confidence::new(1.0)
    );
    assert!(
        deferred
            .continuity
            .arc_decision
            .downgrade_support
            .evidence_loss_pressure
            .0
            > deferred
                .continuity
                .arc_decision
                .downgrade_support
                .ambiguity_pressure
                .0
    );
    assert_eq!(
        deferred.continuity.arc_decision.provenance,
        super::TempoContinuityProvenance::NoTempo
    );
    assert_eq!(
        core_window
            .continuity
            .arc_decision
            .expiry
            .max_failed_revalidations,
        2
    );
    assert_eq!(
        guarded_refined
            .continuity
            .arc_decision
            .expiry
            .fallback_after_beats,
        12
    );
    assert!(
        integer.continuity.arc_support.refresh_strength.0
            > core_window.continuity.arc_support.refresh_strength.0
    );
    assert!(
        core_window.continuity.arc_support.drift_pressure.0
            > integer.continuity.arc_support.drift_pressure.0
    );
    assert!(
        deferred.continuity.arc_support.instability_pressure.0
            > guarded_refined
                .continuity
                .arc_support
                .instability_pressure
                .0
    );
    assert!(
        integer.continuity.arc_decision.confidence.0
            > guarded_refined.continuity.arc_decision.confidence.0
    );
    assert!(
        deferred.continuity.arc_decision.confidence.0
            > core_window.continuity.arc_decision.confidence.0
    );
    assert!(
        core_window
            .continuity
            .arc_decision
            .downgrade_trend_support
            .next_stage_pressure
            .0
            > core_window
                .continuity
                .arc_decision
                .downgrade_trend_support
                .current_pressure
                .0
    );
    assert!(
        integer
            .continuity
            .arc_decision
            .downgrade_trend_support
            .terminal_pressure
            .0
            > integer
                .continuity
                .arc_decision
                .downgrade_trend_support
                .current_pressure
                .0
    );
    assert!(
        core_window
            .continuity
            .arc_decision
            .downgrade_support
            .failed_revalidation_pressure
            .0
            > integer
                .continuity
                .arc_decision
                .downgrade_support
                .failed_revalidation_pressure
                .0
    );
}
