use super::{assert_rejects_positionals, assert_supports_describe};
use crate::CliMode;

#[test]
fn parse_args_supports_device_and_media_boundary_modes() {
    assert_supports_describe(
        "--describe-external-midi-boundary",
        CliMode::DescribeExternalMidiBoundary,
    );
    assert_supports_describe(
        "--describe-generic-event-boundary",
        CliMode::DescribeGenericEventBoundary,
    );
    assert_supports_describe(
        "--describe-controller-expression-boundary",
        CliMode::DescribeControllerExpressionBoundary,
    );
    assert_supports_describe(
        "--describe-control-surface-boundary",
        CliMode::DescribeControlSurfaceBoundary,
    );
    assert_supports_describe(
        "--describe-advanced-hardware-boundary",
        CliMode::DescribeAdvancedHardwareBoundary,
    );
    assert_supports_describe(
        "--describe-recall-portability-boundary",
        CliMode::DescribeRecallPortabilityBoundary,
    );
    assert_supports_describe(
        "--describe-device-supervision-boundary",
        CliMode::DescribeDeviceSupervisionBoundary,
    );
    assert_supports_describe(
        "--describe-clock-topology-boundary",
        CliMode::DescribeClockTopologyBoundary,
    );
    assert_supports_describe(
        "--describe-external-io-boundary",
        CliMode::DescribeExternalIoBoundary,
    );
    assert_supports_describe(
        "--describe-media-service-boundary",
        CliMode::DescribeMediaServiceBoundary,
    );
    assert_supports_describe(
        "--describe-analysis-metadata-boundary",
        CliMode::DescribeAnalysisMetadataBoundary,
    );
    assert_supports_describe(
        "--describe-multichannel-boundary",
        CliMode::DescribeMultichannelBoundary,
    );
    assert_supports_describe(
        "--describe-multi-bus-boundary",
        CliMode::DescribeMultiBusBoundary,
    );
    assert_supports_describe(
        "--describe-sidechain-boundary",
        CliMode::DescribeSidechainBoundary,
    );
    assert_supports_describe(
        "--describe-complex-io-boundary",
        CliMode::DescribeComplexIoBoundary,
    );
    assert_supports_describe(
        "--describe-spatial-boundary",
        CliMode::DescribeSpatialBoundary,
    );
    assert_supports_describe(
        "--describe-stretch-boundary",
        CliMode::DescribeStretchBoundary,
    );
    assert_supports_describe(
        "--describe-marker-analysis-boundary",
        CliMode::DescribeMarkerAnalysisBoundary,
    );
    assert_supports_describe(
        "--describe-transform-artifact-boundary",
        CliMode::DescribeTransformArtifactBoundary,
    );
    assert_supports_describe(
        "--describe-preview-transform-boundary",
        CliMode::DescribePreviewTransformBoundary,
    );
}

#[test]
fn parse_args_rejects_positionals_with_device_and_media_boundary_modes() {
    assert_rejects_positionals("--describe-external-midi-boundary");
    assert_rejects_positionals("--describe-generic-event-boundary");
    assert_rejects_positionals("--describe-controller-expression-boundary");
    assert_rejects_positionals("--describe-control-surface-boundary");
    assert_rejects_positionals("--describe-advanced-hardware-boundary");
    assert_rejects_positionals("--describe-recall-portability-boundary");
    assert_rejects_positionals("--describe-device-supervision-boundary");
    assert_rejects_positionals("--describe-clock-topology-boundary");
    assert_rejects_positionals("--describe-external-io-boundary");
    assert_rejects_positionals("--describe-media-service-boundary");
    assert_rejects_positionals("--describe-analysis-metadata-boundary");
    assert_rejects_positionals("--describe-multichannel-boundary");
    assert_rejects_positionals("--describe-multi-bus-boundary");
    assert_rejects_positionals("--describe-sidechain-boundary");
    assert_rejects_positionals("--describe-complex-io-boundary");
    assert_rejects_positionals("--describe-spatial-boundary");
    assert_rejects_positionals("--describe-stretch-boundary");
    assert_rejects_positionals("--describe-marker-analysis-boundary");
    assert_rejects_positionals("--describe-transform-artifact-boundary");
    assert_rejects_positionals("--describe-preview-transform-boundary");
}
