use crate::interfaces::{
    json_option_f32, json_option_i64, json_option_u64, json_option_usize, json_string, json_u64_vec,
};

#[derive(Clone, Debug, Default, PartialEq)]
pub struct RuntimeAutomationSnapshot {
    pub lane_count: usize,
    pub point_count: usize,
    pub projected_segment_count: usize,
    pub mapped_lane_count: usize,
    pub unmapped_lane_count: usize,
    pub hold_lane_count: usize,
    pub linear_lane_count: usize,
    pub last_batch_epoch: Option<u64>,
    pub last_batch_event_count: usize,
    pub last_batch_ignored_event_count: usize,
    pub last_batch_sub_block_count: usize,
    pub last_batch_coalesced_event_count: usize,
    pub last_batch_strategy_max_sub_blocks: usize,
    pub last_batch_min_ramp_step_samples: Option<usize>,
    pub last_batch_max_sample_offset: Option<usize>,
    pub last_block_sequence: Option<u64>,
    pub last_timeline_position_samples: Option<i64>,
    pub transport_playing: Option<bool>,
    pub parameter_id: u32,
    pub value_events: usize,
    pub modulation_events: usize,
    pub gesture_begin_events: usize,
    pub gesture_end_events: usize,
    pub first_value: Option<f32>,
    pub last_value: Option<f32>,
    pub last_modulation: Option<f32>,
    pub first_epoch: Option<u64>,
    pub last_epoch: Option<u64>,
    pub segment_count: usize,
    pub segment_epochs: Vec<u64>,
    pub lease_rollovers: usize,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RuntimePluginEventSnapshot {
    pub last_processing_epoch: Option<u64>,
    pub last_block_sequence: Option<u64>,
    pub last_generated_event_bytes: u32,
    pub last_batch_total_events: usize,
    pub last_batch_parameter_value_events: usize,
    pub last_batch_parameter_modulation_events: usize,
    pub last_batch_parameter_gesture_events: usize,
    pub last_batch_note_events: usize,
    pub last_batch_note_expression_events: usize,
    pub last_batch_note_expression_pressure_events: usize,
    pub last_batch_note_expression_timbre_events: usize,
    pub last_batch_note_expression_tuning_events: usize,
    pub last_batch_midi_events: usize,
    pub total_events: usize,
    pub parameter_value_events: usize,
    pub parameter_modulation_events: usize,
    pub parameter_gesture_events: usize,
    pub note_events: usize,
    pub note_expression_events: usize,
    pub note_expression_pressure_events: usize,
    pub note_expression_timbre_events: usize,
    pub note_expression_tuning_events: usize,
    pub midi_events: usize,
    pub mpe_posture: RuntimeControllerExpressionMpePosture,
    pub midi2_posture: RuntimeControllerExpressionMidi2Posture,
    pub first_epoch: Option<u64>,
    pub last_epoch: Option<u64>,
    pub segment_count: usize,
    pub segment_epochs: Vec<u64>,
    pub lease_rollovers: usize,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum RuntimeControllerExpressionMpePosture {
    #[default]
    Unsupported,
    Guarded,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum RuntimeControllerExpressionMidi2Posture {
    #[default]
    Unsupported,
    Guarded,
}

pub(crate) fn json_runtime_automation_snapshot(snapshot: &RuntimeAutomationSnapshot) -> String {
    format!(
        concat!(
            "{{",
            "\"lane_count\":{},",
            "\"point_count\":{},",
            "\"projected_segment_count\":{},",
            "\"mapped_lane_count\":{},",
            "\"unmapped_lane_count\":{},",
            "\"hold_lane_count\":{},",
            "\"linear_lane_count\":{},",
            "\"last_batch_epoch\":{},",
            "\"last_batch_event_count\":{},",
            "\"last_batch_ignored_event_count\":{},",
            "\"last_batch_sub_block_count\":{},",
            "\"last_batch_coalesced_event_count\":{},",
            "\"last_batch_strategy_max_sub_blocks\":{},",
            "\"last_batch_min_ramp_step_samples\":{},",
            "\"last_batch_max_sample_offset\":{},",
            "\"last_block_sequence\":{},",
            "\"last_timeline_position_samples\":{},",
            "\"transport_playing\":{},",
            "\"parameter_id\":{},",
            "\"value_events\":{},",
            "\"modulation_events\":{},",
            "\"gesture_begin_events\":{},",
            "\"gesture_end_events\":{},",
            "\"first_value\":{},",
            "\"last_value\":{},",
            "\"last_modulation\":{},",
            "\"first_epoch\":{},",
            "\"last_epoch\":{},",
            "\"segment_count\":{},",
            "\"segment_epochs\":{},",
            "\"lease_rollovers\":{}",
            "}}"
        ),
        snapshot.lane_count,
        snapshot.point_count,
        snapshot.projected_segment_count,
        snapshot.mapped_lane_count,
        snapshot.unmapped_lane_count,
        snapshot.hold_lane_count,
        snapshot.linear_lane_count,
        json_option_u64(snapshot.last_batch_epoch),
        snapshot.last_batch_event_count,
        snapshot.last_batch_ignored_event_count,
        snapshot.last_batch_sub_block_count,
        snapshot.last_batch_coalesced_event_count,
        snapshot.last_batch_strategy_max_sub_blocks,
        json_option_usize(snapshot.last_batch_min_ramp_step_samples),
        json_option_usize(snapshot.last_batch_max_sample_offset),
        json_option_u64(snapshot.last_block_sequence),
        json_option_i64(snapshot.last_timeline_position_samples),
        match snapshot.transport_playing {
            Some(value) => value.to_string(),
            None => "null".into(),
        },
        snapshot.parameter_id,
        snapshot.value_events,
        snapshot.modulation_events,
        snapshot.gesture_begin_events,
        snapshot.gesture_end_events,
        json_option_f32(snapshot.first_value),
        json_option_f32(snapshot.last_value),
        json_option_f32(snapshot.last_modulation),
        json_option_u64(snapshot.first_epoch),
        json_option_u64(snapshot.last_epoch),
        snapshot.segment_count,
        json_u64_vec(&snapshot.segment_epochs),
        snapshot.lease_rollovers,
    )
}

pub(crate) fn json_runtime_plugin_event_snapshot(snapshot: &RuntimePluginEventSnapshot) -> String {
    format!(
        concat!(
            "{{",
            "\"last_processing_epoch\":{},",
            "\"last_block_sequence\":{},",
            "\"last_generated_event_bytes\":{},",
            "\"last_batch_total_events\":{},",
            "\"last_batch_parameter_value_events\":{},",
            "\"last_batch_parameter_modulation_events\":{},",
            "\"last_batch_parameter_gesture_events\":{},",
            "\"last_batch_note_events\":{},",
            "\"last_batch_note_expression_events\":{},",
            "\"last_batch_note_expression_pressure_events\":{},",
            "\"last_batch_note_expression_timbre_events\":{},",
            "\"last_batch_note_expression_tuning_events\":{},",
            "\"last_batch_midi_events\":{},",
            "\"total_events\":{},",
            "\"parameter_value_events\":{},",
            "\"parameter_modulation_events\":{},",
            "\"parameter_gesture_events\":{},",
            "\"note_events\":{},",
            "\"note_expression_events\":{},",
            "\"note_expression_pressure_events\":{},",
            "\"note_expression_timbre_events\":{},",
            "\"note_expression_tuning_events\":{},",
            "\"midi_events\":{},",
            "\"mpe_posture\":{},",
            "\"midi2_posture\":{},",
            "\"first_epoch\":{},",
            "\"last_epoch\":{},",
            "\"segment_count\":{},",
            "\"segment_epochs\":{},",
            "\"lease_rollovers\":{}",
            "}}"
        ),
        json_option_u64(snapshot.last_processing_epoch),
        json_option_u64(snapshot.last_block_sequence),
        snapshot.last_generated_event_bytes,
        snapshot.last_batch_total_events,
        snapshot.last_batch_parameter_value_events,
        snapshot.last_batch_parameter_modulation_events,
        snapshot.last_batch_parameter_gesture_events,
        snapshot.last_batch_note_events,
        snapshot.last_batch_note_expression_events,
        snapshot.last_batch_note_expression_pressure_events,
        snapshot.last_batch_note_expression_timbre_events,
        snapshot.last_batch_note_expression_tuning_events,
        snapshot.last_batch_midi_events,
        snapshot.total_events,
        snapshot.parameter_value_events,
        snapshot.parameter_modulation_events,
        snapshot.parameter_gesture_events,
        snapshot.note_events,
        snapshot.note_expression_events,
        snapshot.note_expression_pressure_events,
        snapshot.note_expression_timbre_events,
        snapshot.note_expression_tuning_events,
        snapshot.midi_events,
        json_string(&format!("{:?}", snapshot.mpe_posture)),
        json_string(&format!("{:?}", snapshot.midi2_posture)),
        json_option_u64(snapshot.first_epoch),
        json_option_u64(snapshot.last_epoch),
        snapshot.segment_count,
        json_u64_vec(&snapshot.segment_epochs),
        snapshot.lease_rollovers,
    )
}
