use super::*;

pub(super) fn empty_runtime_performance_trace_receipt() -> RuntimePerformanceTraceReceipt {
    RuntimePerformanceTraceReceipt {
        observation_count: 0,
        first_block_sequence: None,
        last_block_sequence: None,
        processed_block_span: 0,
        peak_cpu_load_percent: 0.0,
        peak_graph_latency_ms: 0.0,
        peak_block_execution_time_ns: 0,
        peak_block_budget_utilization_percent: 0.0,
        peak_block_budget_overrun_ns: 0,
        peak_pending_prework_target_count: 0,
        peak_prework_queue_depth: 0,
        peak_background_queued_work_item_count: 0,
        peak_background_deferred_work_item_count: 0,
        playback_active_observation_count: 0,
        recording_active_observation_count: 0,
        background_service_run_count: 0,
        background_service_defer_count: 0,
        background_service_throttle_count: 0,
        background_service_abort_count: 0,
        background_service_while_playing_count: 0,
        background_service_while_recording_count: 0,
        background_starvation_observation_count: 0,
        peak_background_starved_work_item_count: 0,
        background_cancellation_observation_count: 0,
        peak_background_cancelled_work_item_count: 0,
        background_realtime_backpressure_observation_count: 0,
        background_recovery_backpressure_observation_count: 0,
        topology_incompatible_observation_count: 0,
        elevated_deadline_pressure_observation_count: 0,
        critical_deadline_pressure_observation_count: 0,
        overrun_deadline_pressure_observation_count: 0,
        budget_overrun_count_delta: 0,
        xrun_count_delta: 0,
        prework_service_starvation_count_delta: 0,
        prework_service_throttle_count_delta: 0,
        prework_service_yield_count_delta: 0,
        peak_hot_latency_node_id: None,
        peak_hot_latency_node_group: None,
        peak_hot_latency_node_samples: 0,
        peak_hot_latency_group: None,
        peak_hot_latency_group_node_count: 0,
        peak_hot_latency_group_total_samples: 0,
        peak_critical_path_lane: None,
        peak_critical_path_lane_node_count: 0,
        peak_critical_path_lane_plugin_backed_node_count: 0,
        peak_critical_path_lane_total_latency_samples: 0,
        summary: "observations=0".to_string(),
    }
}

pub(super) fn seed_runtime_performance_trace_receipt(
    observation_count: usize,
    first_snapshot: &RuntimePerformanceSnapshot,
) -> RuntimePerformanceTraceReceipt {
    RuntimePerformanceTraceReceipt {
        observation_count,
        first_block_sequence: first_snapshot.last_block_sequence,
        last_block_sequence: first_snapshot.last_block_sequence,
        processed_block_span: 0,
        peak_cpu_load_percent: first_snapshot.cpu_load_percent,
        peak_graph_latency_ms: first_snapshot.graph_latency_ms,
        peak_block_execution_time_ns: first_snapshot.peak_block_execution_time_ns,
        peak_block_budget_utilization_percent: first_snapshot.peak_block_budget_utilization_percent,
        peak_block_budget_overrun_ns: first_snapshot.peak_block_budget_overrun_ns,
        peak_pending_prework_target_count: first_snapshot.pending_prework_target_count,
        peak_prework_queue_depth: first_snapshot.prework_queue_depth,
        peak_background_queued_work_item_count: first_snapshot.background_queued_work_item_count,
        peak_background_deferred_work_item_count: first_snapshot
            .background_deferred_work_item_count,
        playback_active_observation_count: 0,
        recording_active_observation_count: 0,
        background_service_run_count: 0,
        background_service_defer_count: 0,
        background_service_throttle_count: 0,
        background_service_abort_count: 0,
        background_service_while_playing_count: 0,
        background_service_while_recording_count: 0,
        background_starvation_observation_count: 0,
        peak_background_starved_work_item_count: 0,
        background_cancellation_observation_count: 0,
        peak_background_cancelled_work_item_count: 0,
        background_realtime_backpressure_observation_count: 0,
        background_recovery_backpressure_observation_count: 0,
        topology_incompatible_observation_count: 0,
        elevated_deadline_pressure_observation_count: 0,
        critical_deadline_pressure_observation_count: 0,
        overrun_deadline_pressure_observation_count: 0,
        budget_overrun_count_delta: 0,
        xrun_count_delta: 0,
        prework_service_starvation_count_delta: 0,
        prework_service_throttle_count_delta: 0,
        prework_service_yield_count_delta: 0,
        peak_hot_latency_node_id: first_snapshot.hot_latency_node_id.clone(),
        peak_hot_latency_node_group: first_snapshot.hot_latency_node_group.clone(),
        peak_hot_latency_node_samples: first_snapshot.hot_latency_node_samples,
        peak_hot_latency_group: first_snapshot.hot_latency_group.clone(),
        peak_hot_latency_group_node_count: first_snapshot.hot_latency_group_node_count,
        peak_hot_latency_group_total_samples: first_snapshot.hot_latency_group_total_samples,
        peak_critical_path_lane: first_snapshot.critical_path_lane.clone(),
        peak_critical_path_lane_node_count: first_snapshot.critical_path_lane_node_count,
        peak_critical_path_lane_plugin_backed_node_count: first_snapshot
            .critical_path_lane_plugin_backed_node_count,
        peak_critical_path_lane_total_latency_samples: first_snapshot
            .critical_path_lane_total_latency_samples,
        summary: String::new(),
    }
}
