use super::*;

pub(crate) fn transport_fault_record_from_event(
    event: RuntimeEvent,
) -> Option<TransportFaultRecord> {
    match event {
        RuntimeEvent::BrokerFailure {
            sandbox_id,
            lease_id,
            processing_epoch,
            block_sequence,
            stage,
            detail: _,
        } => Some(TransportFaultRecord {
            sandbox_id,
            lease_id,
            processing_epoch,
            block_sequence,
            source: TransportFaultSource::HostBroker,
            stage: map_broker_failure_stage(stage),
            phase: map_broker_failure_phase(stage),
            resource: map_broker_failure_resource(stage),
            operation: broker_failure_operation(stage).into(),
            error_kind: None,
        }),
        RuntimeEvent::SandboxOperationFailure {
            sandbox_id,
            lease_id,
            processing_epoch,
            operation,
            error_kind,
            stage,
            detail: _,
        } => Some(TransportFaultRecord {
            sandbox_id,
            lease_id,
            processing_epoch,
            block_sequence: None,
            source: TransportFaultSource::SandboxOperation,
            stage: map_sandbox_operation_failure_stage(stage),
            phase: map_sandbox_operation_failure_phase(stage),
            resource: map_sandbox_operation_failure_resource(stage),
            operation,
            error_kind: Some(error_kind),
        }),
        RuntimeEvent::PluginSandboxTransport {
            sandbox_id,
            lease_id,
            stage: PluginSandboxTransportStage::DetachRequested,
            processing_epoch,
            ..
        } => Some(TransportFaultRecord {
            sandbox_id,
            lease_id: Some(lease_id),
            processing_epoch,
            block_sequence: None,
            source: TransportFaultSource::HostBroker,
            stage: TransportFaultStage::TransportDetachRequested,
            phase: TransportFaultPhase::Teardown,
            resource: TransportFaultResource::SharedMemoryLease,
            operation: "transport.detach_request".into(),
            error_kind: None,
        }),
        RuntimeEvent::PluginSandboxTransport {
            sandbox_id,
            lease_id,
            stage: PluginSandboxTransportStage::Detached,
            processing_epoch,
            ..
        } => Some(TransportFaultRecord {
            sandbox_id,
            lease_id: Some(lease_id),
            processing_epoch,
            block_sequence: None,
            source: TransportFaultSource::HostBroker,
            stage: TransportFaultStage::TransportDetached,
            phase: TransportFaultPhase::Teardown,
            resource: TransportFaultResource::SharedMemoryLease,
            operation: "transport.detached".into(),
            error_kind: None,
        }),
        RuntimeEvent::PluginSandboxTransport {
            sandbox_id,
            lease_id,
            stage: PluginSandboxTransportStage::DetachFault,
            processing_epoch,
            ..
        } => Some(TransportFaultRecord {
            sandbox_id,
            lease_id: Some(lease_id),
            processing_epoch,
            block_sequence: None,
            source: TransportFaultSource::HostBroker,
            stage: TransportFaultStage::TransportDetachFault,
            phase: TransportFaultPhase::Teardown,
            resource: TransportFaultResource::SharedMemoryLease,
            operation: "transport.detach_fault".into(),
            error_kind: None,
        }),
        RuntimeEvent::BrokerInvalidation {
            sandbox_id,
            lease_id,
            processing_epoch,
            block_sequence,
            stage,
            reason: _,
        } => Some(TransportFaultRecord {
            sandbox_id,
            lease_id: Some(lease_id),
            processing_epoch: Some(processing_epoch),
            block_sequence,
            source: TransportFaultSource::RuntimeDispatch,
            stage: map_broker_invalidation_stage(stage),
            phase: TransportFaultPhase::Teardown,
            resource: map_broker_invalidation_resource(stage),
            operation: broker_invalidation_operation(stage).into(),
            error_kind: None,
        }),
        RuntimeEvent::CompletionSlotTransition {
            sandbox_id,
            lease_id,
            processing_epoch,
            block_sequence,
            stage: CompletionSlotStage::TimedOut,
        } => Some(TransportFaultRecord {
            sandbox_id,
            lease_id: Some(lease_id),
            processing_epoch: Some(processing_epoch),
            block_sequence: Some(block_sequence),
            source: TransportFaultSource::RuntimeDispatch,
            stage: TransportFaultStage::CompletionSlotTimedOut,
            phase: TransportFaultPhase::Dispatch,
            resource: TransportFaultResource::CompletionSlot,
            operation: "completion_slot.timeout".into(),
            error_kind: None,
        }),
        RuntimeEvent::CompletionSlotTransition {
            sandbox_id,
            lease_id,
            processing_epoch,
            block_sequence,
            stage: CompletionSlotStage::Invalidated,
        } => Some(TransportFaultRecord {
            sandbox_id,
            lease_id: Some(lease_id),
            processing_epoch: Some(processing_epoch),
            block_sequence: Some(block_sequence),
            source: TransportFaultSource::RuntimeDispatch,
            stage: TransportFaultStage::CompletionSlotInvalidated,
            phase: TransportFaultPhase::Dispatch,
            resource: TransportFaultResource::CompletionSlot,
            operation: "completion_slot.invalidate".into(),
            error_kind: None,
        }),
        RuntimeEvent::CompletionSlotTransition {
            sandbox_id,
            lease_id,
            processing_epoch,
            block_sequence,
            stage: CompletionSlotStage::FallbackApplied,
        } => Some(TransportFaultRecord {
            sandbox_id,
            lease_id: Some(lease_id),
            processing_epoch: Some(processing_epoch),
            block_sequence: Some(block_sequence),
            source: TransportFaultSource::RuntimeDispatch,
            stage: TransportFaultStage::FallbackApplied,
            phase: TransportFaultPhase::Dispatch,
            resource: TransportFaultResource::CompletionSlot,
            operation: "completion_slot.fallback_apply".into(),
            error_kind: None,
        }),
        _ => None,
    }
}
